// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.COMMSG12110;
import ktcmdwscsconnector.customs.MessageClass;

public class GetCommsg12110 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetCommsg12110(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		COMMSG12110 msg = new COMMSG12110(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 0;
			msgClass.MessageString = this.messageString;
			
			msg.setCMTI(msgClass.getMessageString(4,false));
			msg.setCBIT(msgClass.getMessageString(48,false));
			msg.setC2(msgClass.getMessageNumber(19,0));
			msg.setC3(msgClass.getMessageString(6,false));
			msg.setC4(msgClass.getMessageNumber(17,2));
			msg.setC5(msgClass.getMessageNumber(17,2));
			msg.setC6(msgClass.getMessageNumber(17,2));
			msg.setC7(msgClass.getMessageNumber(15,0));
			msg.setC8(msgClass.getMessageNumber(8,0));
			msg.setC9(msgClass.getMessageNumber(8,0));
			msg.setC10(msgClass.getMessageNumber(8,0));
			msg.setC11(msgClass.getMessageNumber(6,0));
			msg.setC12(msgClass.getMessageNumber(25,0));
			msg.setC13(msgClass.getMessageNumber(6,0));
			msg.setC14(msgClass.getMessageNumber(4,0));
			msg.setC15(msgClass.getMessageNumber(4,0));
			msg.setC16(msgClass.getMessageNumber(4,0));
			msg.setC17(msgClass.getMessageNumber(4,0));
			msg.setC18(msgClass.getMessageNumber(4,0));
			msg.setC19(msgClass.getMessageNumber(3,0));
			msg.setC20(msgClass.getMessageNumber(3,0));
			msg.setC21(msgClass.getMessageNumber(3,0));
			msg.setC22(msgClass.getMessageNumber(3,0,true));
			msg.setC23(msgClass.getMessageNumber(3,0));
			msg.setC24(msgClass.getMessageNumber(3,0));
			msg.setC25(msgClass.getMessageNumber(2,0));
			msg.setC26(msgClass.getMessageNumber(2,0));
			msg.setC27(msgClass.getMessageNumber(1,0));
			msg.setC28(msgClass.getMessageNumber(8,0));
			msg.setC29(msgClass.getMessageNumber(8,0));
			msg.setC30(msgClass.getMessageNumber(8,0));
			msg.setC31(msgClass.getMessageNumber(8,0));
			msg.setC32(msgClass.getMessageNumber(11,0));
			msg.setC33(msgClass.getMessageNumber(11,0));
			msg.setC34(msgClass.getMessageNumber(28,0));
			msg.setC35(msgClass.getMessageString(42,false));
			msg.setC36(msgClass.getMessageString(4,false));
			msg.setC37(msgClass.getMessageString(12,false));
			msg.setC38(msgClass.getMessageString(6,false));
			msg.setC39(msgClass.getMessageString(2,false));
			msg.setC40(msgClass.getMessageString(3,false));
			msg.setC41(msgClass.getMessageString(8,false));
			msg.setC42(msgClass.getMessageString(15,false));
			msg.setC43(msgClass.getMessageString(40,false));
			msg.setC44(msgClass.getMessageString(25,false));
			msg.setC45(msgClass.getMessageString(76,false));
			msg.setC46(msgClass.getMessageString(55,false));
			msg.setC47(msgClass.getMessageString(55,false));
			msg.setC48(msgClass.getMessageString(55,false));
			msg.setC49(msgClass.getMessageNumber(3,0));
			msg.setC50(msgClass.getMessageNumber(3,0));
			msg.setC51(msgClass.getMessageNumber(3,0));
			msg.setC52(msgClass.getMessageString(16,false));
			msg.setC53(msgClass.getMessageString(18,false));
			msg.setC54(msgClass.getMessageString(28,false));
			msg.setC55(msgClass.getMessageString(55,false));
			msg.setC56(msgClass.getMessageString(55,false));
			msg.setC57(msgClass.getMessageString(55,false));
			msg.setC58(msgClass.getMessageString(55,false));
			msg.setC59(msgClass.getMessageString(55,false));
			msg.setC60(msgClass.getMessageString(55,false));
			msg.setC61(msgClass.getMessageString(55,false));
			msg.setC62(msgClass.getMessageString(55,false));
			msg.setC63(msgClass.getMessageString(55,false));
			msg.setC64(msgClass.getMessageString(16,false));
			msg.setC65(msgClass.getMessageNumber(1,0));
			msg.setC66(msgClass.getMessageNumber(1,0));
			msg.setC67(msgClass.getMessageNumber(2,0));
			msg.setC68(msgClass.getMessageNumber(3,0));
			msg.setC69(msgClass.getMessageNumber(3,0));
			msg.setC70(msgClass.getMessageNumber(3,0));
			msg.setC71(msgClass.getMessageNumber(4,0));
			msg.setC72(msgClass.getMessageNumber(4,0));
			msg.setC73(msgClass.getMessageNumber(6,0));
			msg.setC74(msgClass.getMessageNumber(11,0));
			msg.setC75(msgClass.getMessageNumber(11,0));
			msg.setC76(msgClass.getMessageNumber(11,0));
			msg.setC77(msgClass.getMessageNumber(11,0));
			msg.setC78(msgClass.getMessageNumber(11,0));
			msg.setC79(msgClass.getMessageNumber(11,0));
			msg.setC80(msgClass.getMessageNumber(11,0));
			msg.setC81(msgClass.getMessageNumber(11,0));
			msg.setC82(msgClass.getMessageNumber(12,0));
			msg.setC83(msgClass.getMessageNumber(12,0));
			msg.setC84(msgClass.getMessageNumber(12,0));
			msg.setC85(msgClass.getMessageNumber(12,0));
			msg.setC86(msgClass.getMessageNumber(17,2));
			msg.setC87(msgClass.getMessageNumber(17,2));
			msg.setC88(msgClass.getMessageNumber(17,2));
			msg.setC89(msgClass.getMessageNumber(17,2));
			msg.setC90(msgClass.getMessageString(42,false));
			msg.setC91(msgClass.getMessageString(1,false));
			msg.setC92(msgClass.getMessageString(2,false));
			msg.setC93(msgClass.getMessageString(5,false));
			msg.setC94(msgClass.getMessageString(7,false));
			msg.setC95(msgClass.getMessageString(42,false));
			msg.setC96(msgClass.getMessageString(8,false));
			msg.setC97(msgClass.getMessageNumber(17,2));
			msg.setC98(msgClass.getMessageString(25,false));
			msg.setC99(msgClass.getMessageNumber(11,0));
			msg.setC100(msgClass.getMessageNumber(11,0));
			msg.setC101(msgClass.getMessageString(17,false));
			msg.setC102(msgClass.getMessageString(28,false));
			msg.setC103(msgClass.getMessageString(28,false));
			msg.setC104(msgClass.getMessageString(55,false));
			msg.setC105(msgClass.getMessageString(55,false));
			msg.setC106(msgClass.getMessageString(55,false));
			msg.setC107(msgClass.getMessageString(55,false));
			msg.setC108(msgClass.getMessageString(55,false));
			msg.setC109(msgClass.getMessageString(55,false));
			msg.setC110(msgClass.getMessageString(55,false));
			msg.setC111(msgClass.getMessageString(55,false));
			msg.setC112(msgClass.getMessageString(55,false));
			msg.setC113(msgClass.getMessageString(55,false));
			msg.setC114(msgClass.getMessageString(55,false));
			msg.setC115(msgClass.getMessageString(55,false));
			msg.setC116(msgClass.getMessageString(55,false));
			msg.setC117(msgClass.getMessageString(55,false));
			msg.setC118(msgClass.getMessageString(55,false));
			msg.setC119(msgClass.getMessageString(55,false));
			msg.setC120(msgClass.getMessageString(28,false));
			msg.setC121(msgClass.getMessageString(55,false));
			msg.setC122(msgClass.getMessageString(55,false));
			msg.setC123(msgClass.getMessageString(55,false));
			msg.setC124(msgClass.getMessageString(35,false));
			msg.setC125(msgClass.getMessageString(55,false));
			msg.setC126(msgClass.getMessageString(55,false));
			msg.setC127(msgClass.getMessageString(55,false));
			msg.setC128(msgClass.getMessageString(64,false));
			msg.setC130(msgClass.getMessageString(24,false));
			msg.setC131(msgClass.getMessageString(40,false));
			msg.setC132(msgClass.getMessageString(8,false));
			msg.setC133(msgClass.getMessageString(8,false));
			msg.setC134(msgClass.getMessageString(82,false));
			msg.setC135(msgClass.getMessageString(30,false));
			msg.setC136(msgClass.getMessageString(16,false));
			msg.setC137(msgClass.getMessageString(4,false));
			msg.setC138(msgClass.getMessageString(16,false));
			msg.setC139(msgClass.getMessageString(32,false));
			msg.setC142(msgClass.getMessageString(10,false));
			msg.setC143(msgClass.getMessageString(40,false));
			msg.setC144(msgClass.getMessageNumber(2,0));
			msg.setC145(msgClass.getMessageNumber(3,0));
			msg.setC146(msgClass.getMessageNumber(6,0));
			msg.setC147(msgClass.getMessageNumber(12,0));
			msg.setC148(msgClass.getMessageNumber(3,0));
			msg.setC149(msgClass.getMessageNumber(12,0));
			msg.setC150(msgClass.getMessageString(16,false));
			msg.setC151(msgClass.getMessageNumber(24,0));
			msg.setC152(msgClass.getMessageString(16,false));
			msg.setC192(msgClass.getMessageString(64,false));
			msg.setC257(msgClass.getMessageString(16,false));
			msg.setC258(msgClass.getMessageString(20,false));
			msg.setC259(msgClass.getMessageString(20,false));
			msg.setC261(msgClass.getMessageString(32,false));
			
			msg.setCode("OK");
			msg.setDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setCode("ER");
			msg.setDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetCommsg12110";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
