// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC2229_LMTCTL08DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC2229 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC2229(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC2229_LMTCTL08DS msg = new TC2229_LMTCTL08DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setLMKIPN(msgClass.getMessageNumber(19,0));
			msg.setIPLSNM(msgClass.getMessageString(40));
			msg.setIPINIT(msgClass.getMessageString(40));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPNAM2(msgClass.getMessageString(40));
			msg.setIPADR1(msgClass.getMessageString(40));
			msg.setIPADR2(msgClass.getMessageString(40));
			msg.setIPADR3(msgClass.getMessageString(40));
			msg.setIPADR4(msgClass.getMessageString(40));
			msg.setWDKIPN(msgClass.getMessageNumber(19,0));
			msg.setWDLSNM(msgClass.getMessageString(40));
			msg.setWDINIT(msgClass.getMessageString(40));
			msg.setWDNAME(msgClass.getMessageString(40));
			msg.setWDNAM2(msgClass.getMessageString(40));
			msg.setIPOLIC(msgClass.getMessageString(40));
			msg.setLMGBAC(msgClass.getMessageNumber(19,0));
			msg.setLMSPKD(msgClass.getMessageNumber(1,0));
			msg.setLMSPRK(msgClass.getMessageString(2));
			msg.setLMGNUM(msgClass.getMessageNumber(19,0));
			msg.setIGNAME(msgClass.getMessageString(40));
			msg.setIGACTV(msgClass.getMessageString(1));
			msg.setIPFDAT(msgClass.getMessageNumber(8,0));
			msg.setLMLNUM(msgClass.getMessageNumber(19,0));
			msg.setLMLLVL(msgClass.getMessageNumber(3,0));
			msg.setLMDESC(msgClass.getMessageString(25));
			msg.setLMSHRD(msgClass.getMessageString(1));
			msg.setLMBKRD(msgClass.getMessageNumber(11,0));
			msg.setLMCRCC(msgClass.getMessageString(3));
			msg.setWDAVAI(msgClass.getMessageNumber(15,2));
			msg.setLMPRBO(msgClass.getMessageNumber(15,2));
			msg.setLMEARM(msgClass.getMessageNumber(15,2));
			msg.setLMUSGA(msgClass.getMessageNumber(15,2));
			msg.setLMDBAL(msgClass.getMessageNumber(15,2));
			msg.setLMSALC(msgClass.getMessageNumber(11,0));
			msg.setWDSAAV(msgClass.getMessageNumber(11,0));
			msg.setLMCALC(msgClass.getMessageNumber(11,0));
			msg.setWDCAAV(msgClass.getMessageNumber(11,0));
			msg.setLMGLMN(msgClass.getMessageNumber(19,0));
			msg.setLMDTTM(msgClass.getMessageNumber(14,0));
			msg.setLMBKRT(msgClass.getMessageNumber(19,0));

			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC2229";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
