// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9409_GIRINSDS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC9409 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9409(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9409_GIRINSDS msg = new TC9409_GIRINSDS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setGIKNTN(msgClass.getMessageNumber(19,0));
			msg.setKRUPDT(msgClass.getMessageNumber(8,0));
			msg.setGIAVST(msgClass.getMessageNumber(3,0));
			msg.setKRPGRP(msgClass.getMessageString(3));
			msg.setGIINST(msgClass.getMessageString(1));
			msg.setGIFIXP(msgClass.getMessageNumber(15,2));
			msg.setKRSKUT(msgClass.getMessageNumber(8,0));
			msg.setKRNPPD(msgClass.getMessageNumber(8,0));
			msg.setGISTDT(msgClass.getMessageNumber(8,0));
			msg.setGIERDT(msgClass.getMessageNumber(8,0));
			msg.setGIEFDT(msgClass.getMessageNumber(8,0));
			msg.setGITMOD(msgClass.getMessageString(3));
			msg.setGITMRS(msgClass.getMessageString(3));
			msg.setGILETA(msgClass.getMessageNumber(15,2));
			msg.setGILETD(msgClass.getMessageNumber(8,0));
			msg.setGIDBB(msgClass.getMessageString(6));
			msg.setGIDBR(msgClass.getMessageString(5));
			msg.setGIDBAN(msgClass.getMessageString(19));
			msg.setGIDBAT(msgClass.getMessageString(3));
			msg.setGIMAXA(msgClass.getMessageNumber(15,2));
			msg.setGIMINA(msgClass.getMessageNumber(15,2));
			msg.setGIDDAN(msgClass.getMessageString(12));
			msg.setGIRSEQ(msgClass.getMessageNumber(5,0));
			msg.setGIRMK(msgClass.getMessageString(25));
			msg.setGIDTTM(msgClass.getMessageNumber(14,0));
			msg.setKTKRTN(msgClass.getMessageNumber(19,0));
			msg.setKRKNST(msgClass.getMessageNumber(3,0));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPOLIC(msgClass.getMessageString(40));
			msg.setIPNWIC(msgClass.getMessageString(40));
			msg.setKRKAID(msgClass.getMessageString(3));
			msg.setKADESC(msgClass.getMessageString(25));
			msg.setWDNFND(msgClass.getMessageString(1));
			msg.setGILEFT(msgClass.getMessageNumber(8,0));
			msg.setGIDDMD(msgClass.getMessageNumber(2,0));

			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9409";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
