// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5029_KNTUTD03DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5029 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5029(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5029_KNTUTD03DS msg = new TC5029_KNTUTD03DS(this.getContext());
				
				msg.setKUKNTN(msgClass.getMessageNumber(19, 0, false));
				msg.setKUPERI(msgClass.getMessageNumber(5, 0, false));
				msg.setTRTYP(msgClass.getMessageNumber(1, 0, false));
				msg.setTRBNTN(msgClass.getMessageNumber(9, 0, true));
				msg.setTRBLON(msgClass.getMessageNumber(7, 0, true));
				msg.setTRTRDT(msgClass.getMessageNumber(8, 0, false));
				msg.setTRBDAT(msgClass.getMessageNumber(8, 0, false));
				msg.setTRCANM(msgClass.getMessageString(40));
				msg.setTRTTYP(msgClass.getMessageNumber(4, 0, true));
				msg.setDPSTAS(msgClass.getMessageString(1));
				msg.setTRBELB(msgClass.getMessageNumber(15, 2, false));
				msg.setLINTYP(msgClass.getMessageNumber(1, 0, false));
				msg.setKTKRTN(msgClass.getMessageNumber(19, 0, false));
				msg.setTRQRPI(msgClass.getMessageString(3));
				msg.setTRMPAN(msgClass.getMessageNumber(19, 0));
				msg.setWDDEVC(msgClass.getMessageString(5));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5029_KNTUTD03DS msg = new TC5029_KNTUTD03DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5029";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
