// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5430_KNTUTD02DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5430 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5430(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC5430_KNTUTD02DS msg = new TC5430_KNTUTD02DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;

			msg.setKUKNTN(msgClass.getMessageNumber(19, 0));
			msg.setKUPERI(msgClass.getMessageNumber(5, 0));
			msg.setKUSTMD(msgClass.getMessageNumber(8, 0));
			msg.setKUSKUT(msgClass.getMessageNumber(8, 0));
			msg.setKUSLMT(msgClass.getMessageNumber(11, 0));
			msg.setKUISLD(msgClass.getMessageNumber(15, 2));
			msg.setKUUSLD(msgClass.getMessageNumber(15, 2));
			msg.setKURES1(msgClass.getMessageNumber(15, 2));
			msg.setWDMTHA(msgClass.getMessageNumber(15, 2));
			msg.setKULBET(msgClass.getMessageNumber(15, 2));
			msg.setWDINDI(msgClass.getMessageString(1));
			msg.setKRUSGA(msgClass.getMessageNumber(15, 2));
			msg.setKRUSG2(msgClass.getMessageNumber(15, 2));
			msg.setKRSLDO(msgClass.getMessageNumber(15, 2));
			msg.setKRSTGR(msgClass.getMessageString(1));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5430";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
