// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC8738_KNTAVTDS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC8738 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC8738(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC8738_KNTAVTDS msg = new TC8738_KNTAVTDS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKAKAID(msgClass.getMessageString(3));
			msg.setKACCDE(msgClass.getMessageString(3));
			msg.setKADESC(msgClass.getMessageString(25));
			msg.setKALIMI(msgClass.getMessageNumber(11, 0));
			msg.setKALIMA(msgClass.getMessageNumber(11, 0));
			msg.setKALIRE(msgClass.getMessageNumber(1, 0));
			msg.setKAAVGN(msgClass.getMessageNumber(15, 2));
			msg.setKAAVGP(msgClass.getMessageNumber(15, 2));
			msg.setKAKSOT(msgClass.getMessageString(1));
			msg.setKANOLA(msgClass.getMessageNumber(15, 2));
			msg.setKAAVR(msgClass.getMessageNumber(5, 0));
			msg.setKABETS(msgClass.getMessageNumber(2, 0));
			msg.setKABETF(msgClass.getMessageNumber(5, 2));
			msg.setKALALA(msgClass.getMessageNumber(15, 2));
			msg.setKARSTB(msgClass.getMessageNumber(15, 2));
			msg.setKAKNTF(msgClass.getMessageNumber(3, 0));
			msg.setKAAVIF(msgClass.getMessageNumber(1, 0));
			msg.setKAPRIO(msgClass.getMessageNumber(2, 0));
			msg.setKAGLPR(msgClass.getMessageNumber(2, 0));
			msg.setKASPER(msgClass.getMessageString(12));
			msg.setKAABFM(msgClass.getMessageNumber(1, 0));
			msg.setKABFR1(msgClass.getMessageNumber(3, 0));
			msg.setKABFR2(msgClass.getMessageNumber(3, 0));
			msg.setKAUTKD(msgClass.getMessageNumber(1, 0));
			msg.setKAMRKD(msgClass.getMessageNumber(1, 0));
			msg.setKARDGR(msgClass.getMessageNumber(15, 2));
			msg.setKAMCAP(msgClass.getMessageNumber(15, 2));
			msg.setKASCAP(msgClass.getMessageString(1));
			msg.setKAPCAP(msgClass.getMessageString(1));
			msg.setKAAPID(msgClass.getMessageString(3));
			msg.setKAUPKR(msgClass.getMessageNumber(15, 2));
			msg.setKAOPKR(msgClass.getMessageNumber(15, 2));
			msg.setKASKKR(msgClass.getMessageNumber(15, 2));
			msg.setKAAAV(msgClass.getMessageNumber(1, 0));
			msg.setKAFSM1(msgClass.getMessageString(3));
			msg.setKAFSM2(msgClass.getMessageString(3));
			msg.setKAVLDM(msgClass.getMessageNumber(3, 0));
			msg.setKAITPN(msgClass.getMessageString(1));
			msg.setKAAAB(msgClass.getMessageNumber(15, 2));
			msg.setKAACKR(msgClass.getMessageNumber(15, 2));
			msg.setKARAKR(msgClass.getMessageNumber(15, 2));
			msg.setKAKBKR(msgClass.getMessageNumber(15, 2));
			msg.setKAKAKR(msgClass.getMessageNumber(15, 2));
			msg.setKAAAKR(msgClass.getMessageNumber(15, 2));
			msg.setKAPNRC(msgClass.getMessageNumber(15, 2));
			msg.setKANOD(msgClass.getMessageNumber(1, 0));
			msg.setKAMUPR(msgClass.getMessageNumber(3, 2));
			msg.setKAWACD(msgClass.getMessageString(1));
			msg.setKASSTS(msgClass.getMessageString(1));
			msg.setKASTDT(msgClass.getMessageNumber(8, 0));
			msg.setKAAGEM(msgClass.getMessageNumber(1, 0));
			msg.setKARMOD(msgClass.getMessageNumber(1, 0));
			msg.setKARDAY(msgClass.getMessageNumber(3, 0));
			msg.setKAGBET(msgClass.getMessageNumber(3, 0));
			msg.setKAGBEF(msgClass.getMessageNumber(15, 2));
			msg.setKAAAY(msgClass.getMessageNumber(3, 0));
			msg.setKAAPPA(msgClass.getMessageNumber(5, 3));
			msg.setKAAPVA(msgClass.getMessageNumber(15, 2));
			msg.setKAFLST(msgClass.getMessageString(1));
			msg.setKAWINT(msgClass.getMessageString(1));
			msg.setKAAPPI(msgClass.getMessageNumber(5, 3));
			msg.setKAAPVI(msgClass.getMessageNumber(15, 2));
			msg.setKAGRCL(msgClass.getMessageNumber(3, 0));
			msg.setKAPGRD(msgClass.getMessageNumber(3, 0));
			msg.setKAYBSE(msgClass.getMessageNumber(1, 0));
			msg.setKAIFDY(msgClass.getMessageNumber(3, 0));
			msg.setKAMALD(msgClass.getMessageNumber(3, 0));
			msg.setKAMOLI(msgClass.getMessageNumber(15, 2));
			msg.setKAMRND(msgClass.getMessageNumber(5, 0));
			msg.setKAMALV(msgClass.getMessageNumber(3, 0));
			msg.setKARNDI(msgClass.getMessageString(1));
			msg.setKAOTBM(msgClass.getMessageString(1));
			msg.setKAMARR(msgClass.getMessageNumber(15, 2));
			msg.setKAMAXR(msgClass.getMessageNumber(15, 2));
			msg.setKAMAXO(msgClass.getMessageNumber(15, 2));
			msg.setKAMSLM(msgClass.getMessageNumber(11, 0));
			msg.setKANSLM(msgClass.getMessageNumber(11, 0));
			msg.setKADTTM(msgClass.getMessageNumber(14, 0));
			msg.setKAAAY1(msgClass.getMessageNumber(3, 0));
			msg.setAIDRPR(msgClass.getMessageNumber(5, 3));
			msg.setAIERPR(msgClass.getMessageNumber(5, 3));
			msg.setAIICDE(msgClass.getMessageString(3));
			msg.setAIMRPR(msgClass.getMessageNumber(5, 3));
			msg.setAIOTPR(msgClass.getMessageNumber(5, 3));
			msg.setAITRPR(msgClass.getMessageNumber(5, 3));
			msg.setWDCOPY(msgClass.getMessageNumber(1, 0));
			msg.setWDKAID(msgClass.getMessageString(3));
			msg.setICMRPR(msgClass.getMessageNumber(5, 3));
			msg.setICTRPR(msgClass.getMessageNumber(5, 3));
			msg.setICDRPR(msgClass.getMessageNumber(5, 3));
			msg.setICOTPR(msgClass.getMessageNumber(5, 3));
			msg.setICUSGR(msgClass.getMessageNumber(5, 3));
			msg.setKASTFS(msgClass.getMessageString(3));
			msg.setAISMRP(msgClass.getMessageNumber(5, 3));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC8738";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
