// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5013_CUSSPODS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5013 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5013(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5013_CUSSPODS msg = new TC5013_CUSSPODS(this.getContext());
				
				msg.setIPKIPN(msgClass.getMessageNumber(19, 0));
				msg.setIPRLSP(msgClass.getMessageString(6));
				msg.setIPSEQ1(msgClass.getMessageNumber(4, 0));
				msg.setIPRLNM(msgClass.getMessageString(40));
				msg.setIPOLI3(msgClass.getMessageString(40));
				msg.setIPITP3(msgClass.getMessageString(3));
				msg.setIPRAD1(msgClass.getMessageString(40));
				msg.setIPRAD2(msgClass.getMessageString(40));
				msg.setIPRAD3(msgClass.getMessageString(40));
				msg.setIPRAD4(msgClass.getMessageString(40));
				msg.setIPRPNR(msgClass.getMessageString(9));
				msg.setIPRCTY(msgClass.getMessageString(40));
				msg.setIPRSTE(msgClass.getMessageString(3));
				msg.setIPRCNC(msgClass.getMessageString(3));
				msg.setIPEMLP(msgClass.getMessageString(100));
				msg.setIPNWI4(msgClass.getMessageString(40));
				msg.setIPTELJ(msgClass.getMessageString(20));
				msg.setIPTELK(msgClass.getMessageString(20));
				msg.setIPTEL3(msgClass.getMessageString(20));
				msg.setIPOCC1(msgClass.getMessageString(6));
				msg.setIPANVE(msgClass.getMessageNumber(8, 0));
				msg.setIPOCC2(msgClass.getMessageString(6));
				msg.setIPODT2(msgClass.getMessageNumber(8, 0));
				msg.setIPSPNM(msgClass.getMessageString(32));
				msg.setIPRCTP(msgClass.getMessageString(1));
				msg.setIPITP4(msgClass.getMessageString(3));
				msg.setIPNATI(msgClass.getMessageString(3));
				msg.setIPTELJE(msgClass.getMessageNumber(7, 0));
				msg.setIPTELKE(msgClass.getMessageNumber(7, 0));
				msg.setIPDTTM(msgClass.getMessageNumber(14, 0));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				
				list.add(msg.getMendixObject());
				
			}
		}
		catch (Exception ex)
		{
			TC5013_CUSSPODS msg = new TC5013_CUSSPODS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5013";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
