// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5919_KNTUT201DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5919 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5919(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5919_KNTUT201DS msg = new TC5919_KNTUT201DS(this.getContext());
				
				msg.setKUKNTN(msgClass.getMessageNumber(19,0));
				msg.setKUPERI(msgClass.getMessageNumber(5,0));
				msg.setKUAINB(msgClass.getMessageNumber(15,2));
				msg.setKUPTHP(msgClass.getMessageNumber(15,2));
				msg.setKUPTHI(msgClass.getMessageNumber(15,2));
				msg.setKUPTHU(msgClass.getMessageNumber(15,2));
				msg.setKUPTHC(msgClass.getMessageNumber(15,2));
				msg.setKUPTHV(msgClass.getMessageNumber(15,2));
				msg.setKUINNB(msgClass.getMessageNumber(5,0));
				msg.setKUAAMT(msgClass.getMessageNumber(15,2));
				msg.setKUCANM(msgClass.getMessageString(40));
				msg.setKUDTTM(msgClass.getMessageNumber(14,0));
				msg.setKUDESC(msgClass.getMessageString(25));
				msg.setKUSEQN(msgClass.getMessageNumber(5,0));

				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				
				list.add(msg.getMendixObject());				
			}
		}
		catch (Exception ex)
		{
			TC5919_KNTUT201DS msg = new TC5919_KNTUT201DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5919";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
