// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1405_KNTPPD01DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1405 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC1405(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC1405_KNTPPD01DS msg = new TC1405_KNTPPD01DS(this.getContext());
				
				msg.setLPSEQN(msgClass.getMessageNumber(5,0));
				msg.setLPTERM(msgClass.getMessageNumber(5,0));
				msg.setLPICDE(msgClass.getMessageString(3));
				msg.setLPRAT1(msgClass.getMessageNumber(5,3));
				msg.setLPRAT2(msgClass.getMessageNumber(5,3));
				msg.setLPIVR1(msgClass.getMessageNumber(5,3));
				msg.setLPSTFV(msgClass.getMessageNumber(5,3));
				msg.setLPEFIR(msgClass.getMessageNumber(5,3));
				msg.setLPEFFR(msgClass.getMessageNumber(5,3));
				msg.setLPEFTR(msgClass.getMessageNumber(5,3));
				msg.setLPGACC(msgClass.getMessageNumber(19,0));
				msg.setLPKNTN(msgClass.getMessageNumber(19,0));
				msg.setLPPPID(msgClass.getMessageString(6));
				msg.setLPPPNT(msgClass.getMessageString(10));
				msg.setLPPPNM(msgClass.getMessageString(1));
				msg.setLPSTDT(msgClass.getMessageNumber(8,0));
				msg.setLPENDT(msgClass.getMessageNumber(8,0));
				msg.setLPTMPR(msgClass.getMessageNumber(5,0));
				msg.setLPDTTM(msgClass.getMessageNumber(14,0));
				msg.setLPDISR(msgClass.getMessageNumber(5,2));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				
				list.add(msg.getMendixObject());

			}
		}
		catch (Exception ex)
		{
			TC1405_KNTPPD01DS msg = new TC1405_KNTPPD01DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1405";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
