// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9207_CUSCNODS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC9207 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9207(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9207_CUSCNODS msg = new TC9207_CUSCNODS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;

			msg.setCTKIPN(msgClass.getMessageNumber(19,0));
			msg.setCTPHNT(msgClass.getMessageString(6));
			msg.setCTSEQ1(msgClass.getMessageNumber(4,0));
			msg.setCTTELN(msgClass.getMessageString(20));
			msg.setCTEFDT(msgClass.getMessageNumber(8,0));
			msg.setCTEXDT(msgClass.getMessageNumber(8,0));
			msg.setCTDTTM(msgClass.getMessageNumber(14,0));
			msg.setWDDESC(msgClass.getMessageString(25));
			msg.setWDNAME(msgClass.getMessageString(32));



			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9207";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
