// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC2406_KNTUTP01DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC2406 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC2406(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC2406_KNTUTP01DS msg = new TC2406_KNTUTP01DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setUPKNTN(msgClass.getMessageNumber(19,0));
			msg.setUPDUDT(msgClass.getMessageNumber(8,0));
			msg.setUPSEQN(msgClass.getMessageNumber(5,0));
			msg.setUPAAMT(msgClass.getMessageNumber(15,2));
			msg.setUPPTOT(msgClass.getMessageNumber(15,2));
			msg.setUPPTOD(msgClass.getMessageNumber(15,2));
			msg.setUPAPRN(msgClass.getMessageNumber(15,2));
			msg.setUPAIN1(msgClass.getMessageNumber(15,2));
			msg.setUPAIN2(msgClass.getMessageNumber(15,2));
			msg.setUPALC(msgClass.getMessageNumber(15,2));
			msg.setUPOTHF(msgClass.getMessageNumber(15,2));
			msg.setUPCVAT(msgClass.getMessageNumber(15,2));
			msg.setUPPPRN(msgClass.getMessageNumber(15,2));
			msg.setUPPIN1(msgClass.getMessageNumber(15,2));
			msg.setUPPIN2(msgClass.getMessageNumber(15,2));
			msg.setUPPOTH(msgClass.getMessageNumber(15,2));
			msg.setUPAVDT(msgClass.getMessageNumber(8,0));
			msg.setLAINAM(msgClass.getMessageNumber(15,2));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC2406";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
