// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1651_ADDRESDS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1651 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC1651(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC1651_ADDRESDS msg = new TC1651_ADDRESDS(this.getContext());
				
				msg.setAXKIPN(msgClass.getMessageNumber(19, false));
				msg.setAXADTP(msgClass.getMessageString(1));
				msg.setAXDESC(msgClass.getMessageString(25));
				msg.setAXSEQ1(msgClass.getMessageNumber(4, false));
				msg.setAXADR1(msgClass.getMessageString(40));
				msg.setAXADR2(msgClass.getMessageString(40));
				msg.setAXADR3(msgClass.getMessageString(40));
				msg.setAXADR4(msgClass.getMessageString(40));
				msg.setAXPNR(msgClass.getMessageString(9));
				msg.setAXCITY(msgClass.getMessageString(40));
				msg.setAXLSTE(msgClass.getMessageString(3));
				msg.setAXCNCD(msgClass.getMessageString(3));
				msg.setAXADRF(msgClass.getMessageString(1));
				msg.setWDCBIL(msgClass.getMessageString(1));
				msg.setAXDTTM(msgClass.getMessageNumber(14, true));
				msg.setWDINDC(msgClass.getMessageString(1));
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				
				if (!msg.getAXKIPN().toString().equals(""))
				{
					list.add(msg.getMendixObject());
				}
			}
		}
		catch (Exception ex)
		{
			TC1651_ADDRESDS msg = new TC1651_ADDRESDS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1651";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
