// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5272_CUSBNK01DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5272 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5272(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5272_CUSBNK01DS msg = new TC5272_CUSBNK01DS(this.getContext());

	            msg.setIDKIPN(msgClass.getMessageNumber(19, 0));     	// Customer Number
	            msg.setIDDBB(msgClass.getMessageString(6));     		// Bank Code
	            msg.setIDDBAT(msgClass.getMessageString(3));            // Bank Account Type
	            msg.setIDDBAN(msgClass.getMessageString(19));           // Bank Account Number
	            msg.setIDDBSQ(msgClass.getMessageNumber(2, 0));			// Bank Acc Seq. No.
	            msg.setIDDBST(msgClass.getMessageString(1));            // Bank Account Status
	            msg.setIDDTTM(msgClass.getMessageNumber(14, 0));        // Date and Time
	            msg.setIDCDTM(msgClass.getMessageNumber(14, 0));        // Create Date and Time
	            msg.setIDOFLG(msgClass.getMessageString(3));            // Account Owner flag
	            msg.setIDOLIC(msgClass.getMessageString(40));           // OTH Payee ID
	            msg.setIDOITP(msgClass.getMessageString(3));            // OTH Payee ID Type
	            msg.setIDOADR(msgClass.getMessageString(200));          // OTH Payee ID Address
	            msg.setIDONAM(msgClass.getMessageString(80));           // OTH Payee ID Name
	            msg.setIDCHNL(msgClass.getMessageString(3));            // Channel
	            msg.setSearchkey(this.searchKey);
	            msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5272_CUSBNK01DS msg = new TC5272_CUSBNK01DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5272";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
