// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5087_INBETR05DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5087 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5087(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5087_INBETR05DS msg = new TC5087_INBETR05DS(this.getContext());				

				msg.setINBNTN(msgClass.getMessageNumber(9, 0, true));
				msg.setINBLON(msgClass.getMessageNumber(7, 0, true));
				msg.setINTTYP(msgClass.getMessageNumber(4, 0));
				msg.setINKRTN(msgClass.getMessageNumber(19, 0));
				msg.setINKNTN(msgClass.getMessageNumber(19, 0));
				msg.setINTRDT(msgClass.getMessageNumber(8, 0));
				msg.setINVLDT(msgClass.getMessageNumber(8, 0));
				msg.setINBDAT(msgClass.getMessageNumber(8, 0));
				msg.setINTRST(msgClass.getMessageNumber(3, 0, true));
				msg.setINBUST(msgClass.getMessageNumber(3, 0));
				msg.setINFKOD(msgClass.getMessageString(15));
				msg.setINBKID(msgClass.getMessageNumber(11, 0));
				msg.setINRKID(msgClass.getMessageString(6));
				msg.setINBKMK(msgClass.getMessageNumber(19, 0));
				msg.setINBEL(msgClass.getMessageNumber(15, 2));
				msg.setINCCDE(msgClass.getMessageString(3));
				msg.setINUBNT(msgClass.getMessageNumber(9, 0, true));
				msg.setINUBLO(msgClass.getMessageNumber(7, 0, true));
				msg.setINDTTM(msgClass.getMessageNumber(14, 0));
				msg.setWDTTY2(msgClass.getMessageNumber(4, 0));
				msg.setWDKRT2(msgClass.getMessageNumber(19, 0));
				msg.setWDBKM2(msgClass.getMessageNumber(19, 0));
				msg.setWDBEL2(msgClass.getMessageNumber(15, 2));
				msg.setWDCCD2(msgClass.getMessageString(3));
				msg.setWDBKI2(msgClass.getMessageNumber(11, 0));
				msg.setWDRKI2(msgClass.getMessageString(6));
				msg.setWDTRD2(msgClass.getMessageNumber(8, 0));
				msg.setWDVLD2(msgClass.getMessageNumber(8, 0));
				msg.setWDTRS2(msgClass.getMessageNumber(3, 0));
				msg.setWDATKD(msgClass.getMessageString(1));
				msg.setINAMT1(msgClass.getMessageNumber(15, 2));
				msg.setINAMT2(msgClass.getMessageNumber(15, 2));
				msg.setINSTRDT(msgClass.getMessageNumber(8, 0));
				msg.setINENDDT(msgClass.getMessageNumber(8, 0));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
								
				list.add(msg.getMendixObject());
				
			}
		}
		catch (Exception ex)
		{
			TC5087_INBETR05DS msg = new TC5087_INBETR05DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5087";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
