// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5059_KNTUTD04DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5059 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5059(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5059_KNTUTD04DS msg = new TC5059_KNTUTD04DS(this.getContext());
				
				msg.setKUKNTN(msgClass.getMessageNumber(19, 0));
				msg.setKUPERI(msgClass.getMessageNumber(5, 0));
				msg.setKRTCGR(msgClass.getMessageString(3));
				msg.setKUISLD(msgClass.getMessageNumber(15, 2));
				msg.setKUATRA(msgClass.getMessageNumber(15, 2));
				msg.setKUAINB(msgClass.getMessageNumber(15, 2));
				msg.setKUARNT(msgClass.getMessageNumber(15, 2));
				msg.setWDARNT(msgClass.getMessageNumber(15, 2));
				msg.setKUUSLD(msgClass.getMessageNumber(15, 2));
				msg.setRABEL(msgClass.getMessageNumber(15, 2));
				msg.setTPGRTP(msgClass.getMessageNumber(2, 0));
				msg.setWDFROM(msgClass.getMessageString(1));
				msg.setTPDESC(msgClass.getMessageString(25));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5059_KNTUTD04DS msg = new TC5059_KNTUTD04DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5059";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
