// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9106_TMPTRA01DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC9106 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9106(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9106_TMPTRA01DS msg = new TC9106_TMPTRA01DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;

			msg.setTRBNTN(msgClass.getMessageNumber(9, 0));
			msg.setTRBLON(msgClass.getMessageNumber(7, 0));
			msg.setTRPEK(msgClass.getMessageNumber(7, 0));
			msg.setTRTTYP(msgClass.getMessageNumber(4, 0));
			msg.setTRBDAT(msgClass.getMessageNumber(8, 0));
			msg.setTRBKID(msgClass.getMessageNumber(11, 0));
			msg.setTRBEL(msgClass.getMessageNumber(15, 2));
			msg.setTRCCDE(msgClass.getMessageString(3));
			msg.setTRREF(msgClass.getMessageString(15));
			msg.setTRCHID(msgClass.getMessageString(1));
			msg.setTRMTIN(msgClass.getMessageString(1));
			msg.setTRREFN(msgClass.getMessageString(15));
			msg.setTRBR(msgClass.getMessageNumber(5, 0));
			msg.setTRCANM(msgClass.getMessageString(40));
			msg.setTRRGKR(msgClass.getMessageString(1));
			msg.setTRDTTM(msgClass.getMessageNumber(14, 0));
			msg.setWDBBEL(msgClass.getMessageNumber(15, 2));
			msg.setWDBANT(msgClass.getMessageNumber(7, 0));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9106";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
