// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC8436_KNTRSK08DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC8436 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC8436(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC8436_KNTRSK08DS msg = new TC8436_KNTRSK08DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKRKNTN(msgClass.getMessageNumber(19,0));
			msg.setKRRKID(msgClass.getMessageString(6));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setKRUPDT(msgClass.getMessageNumber(8,0));
			msg.setKRPGRP(msgClass.getMessageString(3));
			msg.setKRSCOL(msgClass.getMessageString(1));
			msg.setWDPGR1(msgClass.getMessageString(3));
			msg.setWDPGR2(msgClass.getMessageString(3));
			msg.setKRDTTM(msgClass.getMessageNumber(14,0));


			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC8436";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
