// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5403_KNTAVT01DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5403 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5403(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC5403_KNTAVT01DS msg = new TC5403_KNTAVT01DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKRKNTN(msgClass.getMessageNumber(19,0));
			msg.setKAUPKR(msgClass.getMessageNumber(15,2));
			msg.setKAOPKR(msgClass.getMessageNumber(15,2));
			msg.setKAPNRC(msgClass.getMessageNumber(15,2));
			msg.setKAKBKR(msgClass.getMessageNumber(15,2));
			msg.setKAAAKR(msgClass.getMessageNumber(15,2));
			msg.setKAACKR(msgClass.getMessageNumber(15,2));
			msg.setPFLCML(msgClass.getMessageString(1));
			msg.setKAGRCL(msgClass.getMessageNumber(3,0));
			msg.setKAGBET(msgClass.getMessageNumber(3,0));
			msg.setKAGBEF(msgClass.getMessageNumber(15,2));
			msg.setPFPCHA(msgClass.getMessageNumber(5,3));
			msg.setPFCHAM(msgClass.getMessageNumber(1,0));
			msg.setPFMINA(msgClass.getMessageNumber(15,2));
			msg.setPFMAXA(msgClass.getMessageNumber(15,2));
			msg.setKAAAV(msgClass.getMessageNumber(1,0));
			msg.setKAAAB(msgClass.getMessageNumber(15,2));
			msg.setKAAAY(msgClass.getMessageNumber(3,0));
			msg.setKAAAY1(msgClass.getMessageNumber(3,0));
			msg.setKAKAKR(msgClass.getMessageNumber(15,2));
			msg.setKAWACD(msgClass.getMessageString(1));
			msg.setKAVLDM(msgClass.getMessageNumber(3,0));
			msg.setKAFSM1(msgClass.getMessageString(3));
			msg.setKAFSM2(msgClass.getMessageString(3));
			msg.setFSFSMD(msgClass.getMessageString(3));
			msg.setWDFMT1(msgClass.getMessageString(1));
			msg.setWDLIN1(msgClass.getMessageNumber(3, 0));
			msg.setWDBEL1(msgClass.getMessageNumber(15,2));
			msg.setWDLIN2(msgClass.getMessageNumber(3,0));
			msg.setWDBEL2(msgClass.getMessageNumber(15,2));
			msg.setWDLIN3(msgClass.getMessageNumber(3,0));
			msg.setWDBEL3(msgClass.getMessageNumber(15,2));
			msg.setWDLIN4(msgClass.getMessageNumber(3,0));
			msg.setWDBEL4(msgClass.getMessageNumber(15,2));
			msg.setWDLIN5(msgClass.getMessageNumber(3,0));
			msg.setWDBEL5(msgClass.getMessageNumber(15,2));
			msg.setWDLIN6A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL6A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN7A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL7A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN8A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL8A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN9A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL9A(msgClass.getMessageNumber(15,2));
			msg.setWDFMT6(msgClass.getMessageString(1));
			msg.setWDLIN6(msgClass.getMessageNumber(3,0));
			msg.setWDBEL6(msgClass.getMessageNumber(15,2));
			msg.setWDLIN7(msgClass.getMessageNumber(3,0));
			msg.setWDBEL7(msgClass.getMessageNumber(15,2));
			msg.setWDLIN8(msgClass.getMessageNumber(3,0));
			msg.setWDBEL8(msgClass.getMessageNumber(15,2));
			msg.setWDLIN9(msgClass.getMessageNumber(3,0));
			msg.setWDBEL9(msgClass.getMessageNumber(15,2));
			msg.setWDLI10(msgClass.getMessageNumber(3,0));
			msg.setWDBE10(msgClass.getMessageNumber(15,2));
			msg.setWDLIN11A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL11A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN12A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL12A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN13A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL13A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN14A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL14A(msgClass.getMessageNumber(15,2));
			msg.setWDFM11(msgClass.getMessageString(1));
			msg.setWDLI11(msgClass.getMessageNumber(3,0));
			msg.setWDBE11(msgClass.getMessageNumber(15,2));
			msg.setWDLI12(msgClass.getMessageNumber(3,0));
			msg.setWDBE12(msgClass.getMessageNumber(15,2));
			msg.setWDLI13(msgClass.getMessageNumber(3,0));
			msg.setWDBE13(msgClass.getMessageNumber(15,2));
			msg.setWDLI14(msgClass.getMessageNumber(3,0));
			msg.setWDBE14(msgClass.getMessageNumber(15,2));
			msg.setWDLI15(msgClass.getMessageNumber(3,0));
			msg.setWDBE15(msgClass.getMessageNumber(15,2));
			msg.setWDLIN16A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL16A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN17A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL17A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN18A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL18A(msgClass.getMessageNumber(15,2));
			msg.setWDLIN19A(msgClass.getMessageNumber(3,0));
			msg.setWDBEL19A(msgClass.getMessageNumber(15,2));
			msg.setWDFSM2(msgClass.getMessageString(3));
			msg.setWDFMA1(msgClass.getMessageString(1));
			msg.setWDLIA1(msgClass.getMessageNumber(3,0));
			msg.setWDBEA1(msgClass.getMessageNumber(15,2));
			msg.setWDLIA2(msgClass.getMessageNumber(3,0));
			msg.setWDBEA2(msgClass.getMessageNumber(15,2));
			msg.setWDLIA3(msgClass.getMessageNumber(3,0));
			msg.setWDBEA3(msgClass.getMessageNumber(15,2));
			msg.setWDLIA4(msgClass.getMessageNumber(3,0));
			msg.setWDBEA4(msgClass.getMessageNumber(15,2));
			msg.setWDLIA5(msgClass.getMessageNumber(3,0));
			msg.setWDBEA5(msgClass.getMessageNumber(15,2));
			msg.setWDLIA6A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA6A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA7A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA7A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA8A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA8A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA9A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA9A(msgClass.getMessageNumber(15,2));
			msg.setWDFMA6(msgClass.getMessageString(1));
			msg.setWDLIA6(msgClass.getMessageNumber(3,0));
			msg.setWDBEA6(msgClass.getMessageNumber(15,2));
			msg.setWDLIA7(msgClass.getMessageNumber(3,0));
			msg.setWDBEA7(msgClass.getMessageNumber(15,2));
			msg.setWDLIA8(msgClass.getMessageNumber(3,0));
			msg.setWDBEA8(msgClass.getMessageNumber(15,2));
			msg.setWDLIA9(msgClass.getMessageNumber(3,0));
			msg.setWDBEA9(msgClass.getMessageNumber(15,2));
			msg.setWDLIA10(msgClass.getMessageNumber(3,0));
			msg.setWDBEA10(msgClass.getMessageNumber(15,2));
			msg.setWDLIA11A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA11A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA12A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA12A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA13A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA13A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA14A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA14A(msgClass.getMessageNumber(15,2));
			msg.setWDFMA11(msgClass.getMessageString(1));
			msg.setWDLIA11(msgClass.getMessageNumber(3,0));
			msg.setWDBEA11(msgClass.getMessageNumber(15,2));
			msg.setWDLIA12(msgClass.getMessageNumber(3,0));
			msg.setWDBEA12(msgClass.getMessageNumber(15,2));
			msg.setWDLIA13(msgClass.getMessageNumber(3,0));
			msg.setWDBEA13(msgClass.getMessageNumber(15,2));
			msg.setWDLIA14(msgClass.getMessageNumber(3,0));
			msg.setWDBEA14(msgClass.getMessageNumber(15,2));
			msg.setWDLIA15(msgClass.getMessageNumber(3,0));
			msg.setWDBEA15(msgClass.getMessageNumber(15,2));
			msg.setWDLIA16A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA16A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA17A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA17A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA18A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA18A(msgClass.getMessageNumber(15,2));
			msg.setWDLIA19A(msgClass.getMessageNumber(3,0));
			msg.setWDBEA19A(msgClass.getMessageNumber(15,2));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5403";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
