// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1404_KNTLNA01DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1404 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC1404(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC1404_KNTLNA01DS msg = new TC1404_KNTLNA01DS(this.getContext());
				
				msg.setLAKNTN(msgClass.getMessageNumber(19, 0));
				msg.setLASEQN(msgClass.getMessageNumber(5, 0));
				msg.setLADUDT(msgClass.getMessageNumber(8, 0));
				msg.setLACBAL(msgClass.getMessageNumber(15, 2));
				msg.setLAINAM(msgClass.getMessageNumber(15, 2));
				msg.setLARAT1(msgClass.getMessageNumber(5, 3));
				msg.setLARAT2(msgClass.getMessageNumber(5, 3));
				msg.setLANDAY(msgClass.getMessageNumber(5, 0));
				msg.setLAPRAM(msgClass.getMessageNumber(15, 2));
				msg.setLAINA1(msgClass.getMessageNumber(15, 2));
				msg.setLAINA2(msgClass.getMessageNumber(15, 2));
				msg.setLAAMPD(msgClass.getMessageNumber(15, 2));
				msg.setLAPRP(msgClass.getMessageNumber(15, 2));
				msg.setLAINP1(msgClass.getMessageNumber(15, 2));
				msg.setLAINP2(msgClass.getMessageNumber(15, 2));
				msg.setLAOHPD(msgClass.getMessageNumber(15, 2));
				msg.setLAOSBA(msgClass.getMessageNumber(15, 2));
				msg.setLAICDE(msgClass.getMessageString(3));
				msg.setLAIVR1(msgClass.getMessageNumber(5, 3));
				msg.setLAIVR2(msgClass.getMessageNumber(5, 3));
				msg.setLAPPID(msgClass.getMessageString(6));
				msg.setLAPPNT(msgClass.getMessageString(10));
				msg.setLASTDT(msgClass.getMessageNumber(8, 0));
				msg.setLASTFV(msgClass.getMessageNumber(5, 3));
				msg.setLANCPI(msgClass.getMessageNumber(19, 7));
				msg.setLAXRTA(msgClass.getMessageNumber(19, 7));
				msg.setLAXMPR1(msgClass.getMessageNumber(7, 5));
				msg.setLAXMPR2(msgClass.getMessageNumber(7, 5));
				msg.setLAXMPR(msgClass.getMessageNumber(7, 5));
				msg.setLADTTM(msgClass.getMessageNumber(14, 0));
				msg.setLAINDI(msgClass.getMessageString(1));
				msg.setUPAVDT(msgClass.getMessageNumber(8, 0));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setCode("OK");
				msg.setDescription("Successfully.");
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC1404_KNTLNA01DS msg = new TC1404_KNTLNA01DS(this.getContext());
			msg.setCode("ER");
			msg.setDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1404";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
