// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9047_IPPORD04DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC9047 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9047(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9047_IPPORD04DS msg = new TC9047_IPPORD04DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setPPBNTN(msgClass.getMessageNumber(9, 0));
			msg.setPPBLON(msgClass.getMessageNumber(7, 0));
			msg.setPPORNO(msgClass.getMessageNumber(7, 0));
			msg.setPPORLN(msgClass.getMessageNumber(3, 0));
			msg.setPPBKID(msgClass.getMessageNumber(11, 0));
			msg.setPPMCTC(msgClass.getMessageNumber(4, 0));
			msg.setPPCCDE(msgClass.getMessageString(3));
			msg.setPPINTC(msgClass.getMessageNumber(4, 0));
			msg.setPPNBRI(msgClass.getMessageNumber(3, 0));
			msg.setPPORDT(msgClass.getMessageNumber(8, 0));
			msg.setPPORAM(msgClass.getMessageNumber(15, 2));
			msg.setPPORST(msgClass.getMessageString(1));
			msg.setPPCCRS(msgClass.getMessageString(3));
			msg.setPPEREF(msgClass.getMessageString(15));
			msg.setPPKRTN(msgClass.getMessageNumber(19, 0));
			msg.setPPPYFQ(msgClass.getMessageString(1));
			msg.setPPKNTR(msgClass.getMessageString(6));
			msg.setPPIPSV(msgClass.getMessageString(3));
			msg.setPPPGDS(msgClass.getMessageString(40));
			msg.setPPAUST(msgClass.getMessageString(1));
			msg.setPPPRBO(msgClass.getMessageNumber(15, 2));
			msg.setPPORBL(msgClass.getMessageNumber(15, 2));
			msg.setPPBLSQ(msgClass.getMessageNumber(3, 0));
			msg.setPPNBDT(msgClass.getMessageNumber(8, 0));
			msg.setPPDTTM(msgClass.getMessageNumber(14, 0));
			msg.setPPTMID(msgClass.getMessageString(8));
			msg.setPPTMBT(msgClass.getMessageString(8));
			msg.setPPMODP(msgClass.getMessageString(6));
			msg.setMXARJC(msgClass.getMessageString(4));
			msg.setTRBNTN(msgClass.getMessageNumber(9, 0));
			msg.setTRBLON(msgClass.getMessageNumber(7, 0));
			msg.setTRTTYP(msgClass.getMessageNumber(4, 0));
			msg.setTRKORR(msgClass.getMessageString(1));
			msg.setTRTRST(msgClass.getMessageNumber(3, 0));
			msg.setTRBDAT(msgClass.getMessageNumber(8, 0));
			msg.setTRCANM(msgClass.getMessageString(40));
			msg.setKTSPKD(msgClass.getMessageNumber(1, 0));
			msg.setKRAVST(msgClass.getMessageNumber(3,true));
			msg.setKTKNTN(msgClass.getMessageNumber(19, 0));
			msg.setKRGACC(msgClass.getMessageNumber(19, 0));
			msg.setKRKNST(msgClass.getMessageNumber(3, true));
			msg.setKRRKID(msgClass.getMessageString(6));
			msg.setKRCCDE(msgClass.getMessageString(3));
			msg.setWDNAME(msgClass.getMessageString(40));
			msg.setWDIBEL(msgClass.getMessageNumber(15, 2));
			msg.setWDPBEL(msgClass.getMessageNumber(15, 2));
			msg.setWDTBEL(msgClass.getMessageNumber(15, 2));
			msg.setPCMMTP(msgClass.getMessageString(2));
			msg.setWDORST(msgClass.getMessageString(1));
			msg.setWDBPNM(msgClass.getMessageString(40));
			msg.setPPINTI(msgClass.getMessageNumber(4, 0));
			msg.setWDUNBL(msgClass.getMessageNumber(15, 2));
			msg.setWDTBIL(msgClass.getMessageNumber(15, 2));
			msg.setPPSTAS(msgClass.getMessageString(1));
			msg.setPPTSRC(msgClass.getMessageString(1));
			msg.setTRVLDT(msgClass.getMessageNumber(8, 0));
			msg.setPPUBNT(msgClass.getMessageNumber(9, 0));
			msg.setPPUBLO(msgClass.getMessageNumber(7, 0));
			msg.setPPIPRT(msgClass.getMessageNumber(5, 3));
			msg.setPPUPBY(msgClass.getMessageString(10));

			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9047";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
