// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1601_KNTRSK21DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1601 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC1601(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC1601_KNTRSK21DS msg = new TC1601_KNTRSK21DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKRKNTN(msgClass.getMessageNumber(19, false));
			msg.setKRUPDT(msgClass.getMessageNumber(8, false));
			msg.setKRBKRD(msgClass.getMessageNumber(11, 0));
			msg.setKRSLMT(msgClass.getMessageNumber(11, 0));
			msg.setKRLMTF(msgClass.getMessageString(1));
			msg.setKROTBM(msgClass.getMessageString(1));
			msg.setKRKAID(msgClass.getMessageString(3));
			msg.setKRCCDE(msgClass.getMessageString(3));
			msg.setKRSLDO(msgClass.getMessageNumber(15, 2));
			msg.setKRUSLD(msgClass.getMessageNumber(15, 2));
			msg.setKRLBET(msgClass.getMessageNumber(15, 2));
			msg.setWDTOTD(msgClass.getMessageNumber(15, 2));
			msg.setWDCURD(msgClass.getMessageNumber(15, 2));
			msg.setKRFSMD(msgClass.getMessageString(3));
			msg.setKRFSM1(msgClass.getMessageString(3));	
			msg.setKRFSM2(msgClass.getMessageString(3));
			msg.setKRF2VF(msgClass.getMessageNumber(6, true));
			msg.setKRAAY(msgClass.getMessageNumber(3, false));
			msg.setKRRSTD(msgClass.getMessageNumber(8, true));
			msg.setKRRLVL(msgClass.getMessageNumber(3, false));
			msg.setKRRES1(msgClass.getMessageNumber(15, 2));
			msg.setKRRES2(msgClass.getMessageNumber(15, 2));
			msg.setKRRES3(msgClass.getMessageNumber(15, 2));
			msg.setKRRES4(msgClass.getMessageNumber(15, 2));
			msg.setKRRES5(msgClass.getMessageNumber(15, 2));
			msg.setKRRES6(msgClass.getMessageNumber(15, 2));
			msg.setKRRES7(msgClass.getMessageNumber(15, 2));
			msg.setKRRES8(msgClass.getMessageNumber(15, 2));
			msg.setKRRES9(msgClass.getMessageNumber(15, 2));
			msg.setKRRES10(msgClass.getMessageNumber(15, 2));
			msg.setKRRES11(msgClass.getMessageNumber(15, 2));
			msg.setKRRES12(msgClass.getMessageNumber(15, 2));
			msg.setKRRES13(msgClass.getMessageNumber(15, 2));
			msg.setKRRES14(msgClass.getMessageNumber(15, 2));
			msg.setKRBPFR(msgClass.getMessageNumber(6, true));
			msg.setKRBETT(msgClass.getMessageNumber(6, true));
			msg.setKRABEL(msgClass.getMessageNumber(15, 2));
			msg.setKRBEL1(msgClass.getMessageNumber(15, 2));
			msg.setKRBEL2(msgClass.getMessageNumber(15, 2));
			msg.setKRBEL3(msgClass.getMessageNumber(15, 2));
			msg.setKRSBPK(msgClass.getMessageNumber(15, 2));
			msg.setKRANTK(msgClass.getMessageNumber(3, false));
			msg.setKRAVST(msgClass.getMessageNumber(3, true));
			msg.setKRAVDT(msgClass.getMessageNumber(8, true));
			msg.setKRMCDE(msgClass.getMessageString(3));
			msg.setKRHSLD(msgClass.getMessageNumber(15, 2));
			msg.setKRHSFP(msgClass.getMessageNumber(15, 2));
			msg.setKRUSC1(msgClass.getMessageString(3));
			msg.setKRUSC2(msgClass.getMessageString(3));
			msg.setKRUSC3(msgClass.getMessageString(3));
			msg.setKRUSC4(msgClass.getMessageString(3));
			msg.setKRCBIL(msgClass.getMessageString(1));
			msg.setKRAVFA(msgClass.getMessageString(1));
			msg.setKRSTGR(msgClass.getMessageString(1));
			msg.setKRBEVK(msgClass.getMessageString(1));
			msg.setKREXDT(msgClass.getMessageNumber(8, true));
			msg.setKRRKID(msgClass.getMessageString(6));
			msg.setKRPGRP(msgClass.getMessageString(3));
			msg.setKRKIPN(msgClass.getMessageNumber(19, false));
			msg.setKRLOPN(msgClass.getMessageNumber(11, false));
			msg.setKRACAT(msgClass.getMessageNumber(2, true));
			msg.setKRAVIF(msgClass.getMessageNumber(1, false));
			msg.setKRNOD(msgClass.getMessageNumber(1, false));
			msg.setKRSVID(msgClass.getMessageString(6));
			msg.setKRSPLV(msgClass.getMessageNumber(3, false));
			msg.setKRKNST(msgClass.getMessageNumber(3, true));
			msg.setKRUTKD(msgClass.getMessageNumber(1, true));
			msg.setKRINTF(msgClass.getMessageNumber(15, 2));
			msg.setKRPRBO(msgClass.getMessageNumber(15, 2));
			msg.setKRAINB(msgClass.getMessageNumber(15, 2));
			msg.setKRAINF(msgClass.getMessageNumber(15, 2));
			msg.setKRACRA(msgClass.getMessageNumber(15, 2));
			msg.setKRACRF(msgClass.getMessageNumber(15, 2));
			msg.setKRACAA(msgClass.getMessageNumber(15, 2));
			msg.setKRACAF(msgClass.getMessageNumber(15, 2));
			msg.setKRACIA(msgClass.getMessageNumber(15, 2));
			msg.setKRACIF(msgClass.getMessageNumber(15, 2));
			msg.setKRATAX(msgClass.getMessageNumber(15, 2));
			msg.setKRATXF(msgClass.getMessageNumber(15, 2));
			msg.setKRKRTS(msgClass.getMessageNumber(3, true));
			msg.setKRBFR1(msgClass.getMessageNumber(3, false));
			msg.setKRBFR2(msgClass.getMessageNumber(3, false));
			msg.setKRFORB(msgClass.getMessageNumber(1, false));
			msg.setKRFBET(msgClass.getMessageNumber(15, 2));
			msg.setKRBKID(msgClass.getMessageNumber(11, false));
			msg.setKRAGDT(msgClass.getMessageNumber(8, true));
			msg.setKRAGIR(msgClass.getMessageNumber(19, false));
			msg.setKRBANM(msgClass.getMessageString(40));
			msg.setKRCACC(msgClass.getMessageNumber(19, false));
			msg.setKRIACC(msgClass.getMessageNumber(19, false));
			msg.setKRREF(msgClass.getMessageString(15));
			msg.setKRFBDT(msgClass.getMessageNumber(8, true));
			msg.setKRSLAD(msgClass.getMessageNumber(8, true));
			msg.setKRLMRJ(msgClass.getMessageNumber(8, true));
			msg.setKRNKDB(msgClass.getMessageNumber(6, true));
			msg.setKRSTDT(msgClass.getMessageNumber(8, true));
			msg.setKRTBDT(msgClass.getMessageNumber(8, true));
			msg.setKRIBDT(msgClass.getMessageNumber(8, false));
			msg.setKRAUDT(msgClass.getMessageNumber(8, true));
			msg.setKRAURJ(msgClass.getMessageNumber(8, true));
			msg.setKRSKKA(msgClass.getMessageNumber(8, true));
			msg.setKRSKUT(msgClass.getMessageNumber(8, false));
			msg.setKRRBDT(msgClass.getMessageNumber(8, true));
			msg.setKRSTMP(msgClass.getMessageNumber(6, true));
			msg.setKRANTA(msgClass.getMessageNumber(5, false));
			msg.setKRLPER(msgClass.getMessageNumber(6, true));
			msg.setKRIKPR(msgClass.getMessageNumber(6, true));
			msg.setKRIBID(msgClass.getMessageString(6));
			msg.setKRSCDT(msgClass.getMessageNumber(8, true));
			msg.setKRSCOR(msgClass.getMessageNumber(5, false));
			msg.setKRAUAP(msgClass.getMessageString(1));
			msg.setKRATML(msgClass.getMessageString(1));
			msg.setKRSATP(msgClass.getMessageString(1));
			msg.setKRSTRC(msgClass.getMessageString(6));
			msg.setKRACT1(msgClass.getMessageString(3));
			msg.setKRKTTP(msgClass.getMessageString(3));
			msg.setKRMISF(msgClass.getMessageString(1));
			msg.setKRATP1(msgClass.getMessageString(1));
			msg.setKRPDAY(msgClass.getMessageNumber(2, false));
			msg.setKRDBAL(msgClass.getMessageNumber(15, 2));
			msg.setKRPLIM(msgClass.getMessageNumber(11, false));
			msg.setKRTLIM(msgClass.getMessageNumber(11, false));
			msg.setKRLFLG(msgClass.getMessageString(1));
			msg.setKRTLDT(msgClass.getMessageNumber(8, true));
			msg.setKRPOFF(msgClass.getMessageString(1));
			msg.setKRNPPD(msgClass.getMessageNumber(8, true));
			msg.setKRLADT(msgClass.getMessageNumber(8, true));
			msg.setKRADAT(msgClass.getMessageNumber(8, true));
			msg.setKRBCDE(msgClass.getMessageString(3));
			msg.setKRBCDT(msgClass.getMessageNumber(8, true));
			msg.setKRNTRD(msgClass.getMessageNumber(3, false));
			msg.setKRNTRC(msgClass.getMessageNumber(3, false));
			msg.setKRTAMD(msgClass.getMessageNumber(15, 2));
			msg.setKRTAMC(msgClass.getMessageNumber(15, 2));
			msg.setKRSPMD(msgClass.getMessageNumber(8, true));
			msg.setKRSPMA(msgClass.getMessageNumber(15, 2));
			msg.setKRSPMN(msgClass.getMessageNumber(3, false));
			msg.setKRSPAM(msgClass.getMessageNumber(15, 2));
			msg.setKRTPDT(msgClass.getMessageNumber(8, true));
			msg.setKRRDAT(msgClass.getMessageNumber(8, true));
			msg.setKRFUDT(msgClass.getMessageNumber(8, true));
			msg.setKRUCIA(msgClass.getMessageNumber(15, 2));
			msg.setKRDTTM(msgClass.getMessageNumber(14, true));
			msg.setKRITFL(msgClass.getMessageNumber(11, false));
			msg.setKRITFB(msgClass.getMessageNumber(15, 2));
			msg.setKRITFO(msgClass.getMessageNumber(15, 2));
			msg.setKRITFA(msgClass.getMessageNumber(15, 2));
			msg.setKRITFP(msgClass.getMessageNumber(15, 2));
			msg.setKRAMTR(msgClass.getMessageNumber(15, 2));
			msg.setKRRTYP(msgClass.getMessageNumber(2, true));
			msg.setKRSTRA(msgClass.getMessageString(1));
			msg.setKRLBIL(msgClass.getMessageString(1));
			msg.setKRSEQ1(msgClass.getMessageNumber(4, false));
			msg.setKRBR(msgClass.getMessageNumber(5, false));
			msg.setWDSTMD(msgClass.getMessageNumber(8, false));
			msg.setWDOTBC(msgClass.getMessageNumber(15, 2));
			msg.setWDOTB0(msgClass.getMessageNumber(15, 2));
			msg.setGIINST(msgClass.getMessageString(1));
			msg.setPHBELP(msgClass.getMessageNumber(15, 2));
			msg.setWDTLIM(msgClass.getMessageNumber(11, false));
			msg.setLPEFDT(msgClass.getMessageNumber(8, false));
			msg.setLPEXDT(msgClass.getMessageNumber(8, false));
			msg.setKQRQDT(msgClass.getMessageNumber(8, false));
			msg.setSKSPRK(msgClass.getMessageString(2));
			msg.setKTSPKD(msgClass.getMessageNumber(1, true));
			msg.setWDBKRC(msgClass.getMessageNumber(11, 0));
			msg.setWDSLDC(msgClass.getMessageNumber(15, 2));
			msg.setWDPSTM(msgClass.getMessageNumber(8, false));
			msg.setWDESTM(msgClass.getMessageString(1));
			msg.setTLSCLF(msgClass.getMessageNumber(2, true));
			msg.setTLLIMA(msgClass.getMessageNumber(11, false));
			msg.setTLSCTL(msgClass.getMessageNumber(11, false));
			msg.setWIAVST(msgClass.getMessageString(1));
			msg.setWDKNTN(msgClass.getMessageNumber(19, false));
			msg.setAPOAMT(msgClass.getMessageNumber(15, 2));
			msg.setAPTMTO(msgClass.getMessageNumber(5, false));
			msg.setAPPAMT(msgClass.getMessageNumber(15, 2));
			msg.setKRUSGA(msgClass.getMessageNumber(15, 2));			//host update attribute KRUSGA:UsageAmount
			msg.setWDIUBL(msgClass.getMessageNumber(15, 2));	    	//host update Total IPP unbilled 
			msg.setSKUSER(msgClass.getMessageString(10));	    	 
			msg.setSKSFDN(msgClass.getMessageNumber(8, 0));	    	 
			msg.setSKSTDN(msgClass.getMessageNumber(8, 0));	    	 
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1601";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
