// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9419_KORTRG02DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC9419 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9419(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9419_KORTRG02DS msg = new TC9419_KORTRG02DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;

			msg.setKTKRTN(msgClass.getMessageNumber(19,0));
			msg.setKTKNTN(msgClass.getMessageNumber(19,0));
			msg.setKTEMNM(msgClass.getMessageString(26));
			msg.setKTEMN1(msgClass.getMessageString(26));
			msg.setWDNAME(msgClass.getMessageString(40));
			msg.setKTKTTP(msgClass.getMessageString(3));
			msg.setKTGTDT(msgClass.getMessageNumber(6,0));
			msg.setKTPNRI(msgClass.getMessageString(1));
			msg.setKTDTTM(msgClass.getMessageNumber(14,0));
			msg.setWDPNR1(msgClass.getMessageString(1));
			msg.setWDPINR(msgClass.getMessageString(1));
			msg.setGNCGEN(msgClass.getMessageString(6));
			msg.setKTCBI3(msgClass.getMessageString(1));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9419";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
