// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5081_PAYPST01DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5081 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5081(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5081_PAYPST01DS msg = new TC5081_PAYPST01DS(this.getContext());
				
				msg.setWDGACC(msgClass.getMessageNumber(19,0));
				msg.setWDKNTN(msgClass.getMessageNumber(19,0));
				msg.setWDKNTN1(msgClass.getMessageNumber(19,0));
				msg.setWDBNTN(msgClass.getMessageNumber(9,0));
				msg.setWDBLON(msgClass.getMessageNumber(7,0));
				msg.setWDTRDT(msgClass.getMessageNumber(8,0));
				msg.setWDBEL(msgClass.getMessageNumber(15,2));
				msg.setWDTTYP(msgClass.getMessageNumber(4,0));
				msg.setWDTSRC(msgClass.getMessageString(1));
				msg.setWDRKID(msgClass.getMessageString(6));
				msg.setWDDESC(msgClass.getMessageString(25));
				msg.setWDKRTN(msgClass.getMessageNumber(19,0));
				msg.setWDBELP(msgClass.getMessageNumber(15,2));
				msg.setWDTCGR(msgClass.getMessageString(3));
				msg.setWDGRTP(msgClass.getMessageNumber(2,0, true));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5081_PAYPST01DS msg = new TC5081_PAYPST01DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5081";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
