// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5484_INPART07DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5484 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5484(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5484_INPART07DS msg = new TC5484_INPART07DS(this.getContext());
				// Start Detail
				msgClass.intIndex = 693;
				msgClass.MessageString = this.messageString;
				
				msg.setKTKRTN(msgClass.getMessageNumber(19, 0));
				msg.setIPKIPN(msgClass.getMessageNumber(19, 0));
				msg.setWDNAME(msgClass.getMessageString(80));
				msg.setIPINIT(msgClass.getMessageString(40));
				msg.setIPLSNM(msgClass.getMessageString(40));
				msg.setIPNAME(msgClass.getMessageString(40));
				msg.setIPNAM2(msgClass.getMessageString(40));
				msg.setWDPHON(msgClass.getMessageString(20));
				msg.setIPTELH(msgClass.getMessageString(20));
				msg.setIPTELA(msgClass.getMessageString(20));
				msg.setIPTEL3(msgClass.getMessageString(20));
				msg.setIPEMNM(msgClass.getMessageString(26));
				msg.setIPEMN1(msgClass.getMessageString(26));
				msg.setWDFDAT(msgClass.getMessageNumber(8, 0));
				msg.setIPFDAT(msgClass.getMessageNumber(8, 0));
				msg.setIPOLIC(msgClass.getMessageString(40));
				msg.setIPNWIC(msgClass.getMessageString(40));
				msg.setIPRCTP(msgClass.getMessageString(1));
				msg.setWDSTRF(msgClass.getMessageString(1));
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");

				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5484_INPART07DS msg = new TC5484_INPART07DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5484";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
