// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC8459_INBETR01DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC8459 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC8459(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC8459_INBETR01DS msg = new TC8459_INBETR01DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setINBNTN(msgClass.getMessageNumber(9, 0, true));
			msg.setINBLON(msgClass.getMessageNumber(7, 0, true));
			msg.setINTTYP(msgClass.getMessageNumber(4, 0));
			msg.setINKRTN(msgClass.getMessageNumber(19, 0));
			msg.setINKNTN(msgClass.getMessageNumber(19, 0));
			msg.setINTRDT(msgClass.getMessageNumber(8, 0));
			msg.setINVLDT(msgClass.getMessageNumber(8, 0));
			msg.setINBDAT(msgClass.getMessageNumber(8, 0));
			msg.setINPERI(msgClass.getMessageNumber(6, 0));
			msg.setINTRST(msgClass.getMessageNumber(3, 0, true));
			msg.setINBUST(msgClass.getMessageNumber(3, 0));
			msg.setINKORR(msgClass.getMessageString(1));
			msg.setINFKOD(msgClass.getMessageString(15));
			msg.setINBKID(msgClass.getMessageNumber(11, 0));
			msg.setINRKID(msgClass.getMessageString(6));
			msg.setINBKMK(msgClass.getMessageNumber(19, 0));
			msg.setINBEL(msgClass.getMessageNumber(15, 2));
			msg.setINCCDE(msgClass.getMessageString(3));
			msg.setINUBNT(msgClass.getMessageNumber(9, 0, true));
			msg.setINUBLO(msgClass.getMessageNumber(7, 0, true));
			msg.setINUTBN(msgClass.getMessageNumber(9, 0, true));
			msg.setINUTBL(msgClass.getMessageNumber(7, 0, true));
			msg.setINREFN(msgClass.getMessageString(15));
			msg.setINREF(msgClass.getMessageString(15));
			msg.setINCHQN(msgClass.getMessageNumber(10, 0));
			msg.setINDTTM(msgClass.getMessageNumber(14, 0));
			msg.setINCANM(msgClass.getMessageString(40));
			msg.setWDDSCC(msgClass.getMessageString(1));
			msg.setWDADES(msgClass.getMessageString(50));
			msg.setWDUSER(msgClass.getMessageString(10));
			msg.setWDDATE(msgClass.getMessageNumber(8, 0));
			msg.setWDTIME(msgClass.getMessageNumber(6, 0));
			msg.setWDTTY2(msgClass.getMessageNumber(4, 0));
			msg.setWDKRT2(msgClass.getMessageNumber(19, 0));
			msg.setWDBKM2(msgClass.getMessageNumber(19, 0));
			msg.setWDBEL2(msgClass.getMessageNumber(15, 2));
			msg.setWDCCD2(msgClass.getMessageString(3));
			msg.setWDBKI2(msgClass.getMessageNumber(11, 0));
			msg.setWDRKI2(msgClass.getMessageString(6));
			msg.setWDTRD2(msgClass.getMessageNumber(8, 0));
			msg.setWDVLD2(msgClass.getMessageNumber(8, 0));
			msg.setWDATKD(msgClass.getMessageString(1));
			msg.setINREAC(msgClass.getMessageString(3));
			msg.setBKBPNM(msgClass.getMessageString(40));
			msg.setBKPNR(msgClass.getMessageString(9));
			msg.setBKCITY(msgClass.getMessageString(25));
			msg.setWDTRS2(msgClass.getMessageNumber(3, 0));


			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC8459";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
