// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC3615_AUTMTA02DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC3615 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC3615(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC3615_AUTMTA02DS msg = new TC3615_AUTMTA02DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setAAAUTG(msgClass.getMessageString(3));
			msg.setAAKRTN(msgClass.getMessageNumber(19, false));
			msg.setAAAMOD(msgClass.getMessageString(2));
			msg.setAAMODI(msgClass.getMessageString(1));
			msg.setAADAMA(msgClass.getMessageNumber(11, false));
			msg.setAADNOD(msgClass.getMessageNumber(3, false));
			msg.setAADAMD(msgClass.getMessageNumber(11, false));
			msg.setAAIAMA(msgClass.getMessageNumber(11, false));
			msg.setAAINOD(msgClass.getMessageNumber(3, false));
			msg.setAAIAMD(msgClass.getMessageNumber(11, false));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC3615";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
