// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1237_IPPORD05DS;
import ktc_scs_schema.proxies.TC1239_ACCPPH02DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1237 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC1237(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC1237_IPPORD05DS msg = new TC1237_IPPORD05DS(this.getContext());
				
				msg.setPPKRTN(msgClass.getMessageNumber(19, 0));
				msg.setPPORDT(msgClass.getMessageNumber(8, 0));
				msg.setPPORAM(msgClass.getMessageNumber(15, 2));
				msg.setPPPYFQ(msgClass.getMessageString(1));
				msg.setPPNBRI(msgClass.getMessageNumber(3, 0));
				msg.setPPBKID(msgClass.getMessageNumber(11, 0));
				msg.setPPORST(msgClass.getMessageString(1));
				msg.setPPBNTN(msgClass.getMessageNumber(9, 0));
				msg.setPPBLON(msgClass.getMessageNumber(7, 0));
				msg.setPPNBDT(msgClass.getMessageNumber(8, 0));
				msg.setPPORNO(msgClass.getMessageNumber(7, 0));
				msg.setPPORLN(msgClass.getMessageNumber(3, 0));
				msg.setWDDESC(msgClass.getMessageString(25));
				msg.setPPSTAS(msgClass.getMessageString(1));
				msg.setPPCANM(msgClass.getMessageString(40));
				msg.setPPTSRC(msgClass.getMessageString(1));
				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setCode("OK");
				msg.setDescription("Successfully.");
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC1239_ACCPPH02DS msg = new TC1239_ACCPPH02DS(this.getContext());
			msg.setCode("ER");
			msg.setDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1237";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
