// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TCLNI8000Rs;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTCLNI8000 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTCLNI8000(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TCLNI8000Rs msg = new TCLNI8000Rs(this.getContext());
		
		try
		{
			// Start Detail for TC
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
		
			msg.setINCIFN(msgClass.getMessageNumber(19, false));
			msg.setINIDT(msgClass.getMessageString(3));
			msg.setININM(msgClass.getMessageString(40));
			msg.setINISCO(msgClass.getMessageString(3));
			msg.setINBIR8(msgClass.getMessageNumber(8, false));
			msg.setINGEN(msgClass.getMessageString(1));
			msg.setINENM1(msgClass.getMessageString(40));
			msg.setINENM2(msgClass.getMessageString(40));
			msg.setINESA1(msgClass.getMessageString(10));
			msg.setINTNM1(msgClass.getMessageString(40));
			msg.setINTNM2(msgClass.getMessageString(40));
			msg.setINESA2(msgClass.getMessageString(10));
			msg.setINHPHN(msgClass.getMessageString(20));
			msg.setINOPHN(msgClass.getMessageString(20));
			msg.setINMPHN(msgClass.getMessageString(20));
			msg.setINEMIL(msgClass.getMessageString(100));
			msg.setINEMPL(msgClass.getMessageString(80));
			msg.setINEMP2(msgClass.getMessageString(80));
			msg.setINRESTY(msgClass.getMessageString(2));
			msg.setINRESP(msgClass.getMessageString(6));
			msg.setINOCCU(msgClass.getMessageString(10));
			msg.setINNAT(msgClass.getMessageString(3));
			msg.setINMARI(msgClass.getMessageString(1));
			msg.setININDI(msgClass.getMessageString(1));
			msg.setINSTAF(msgClass.getMessageString(1));
			msg.setINADTY(msgClass.getMessageString(1));
			msg.setINADD1(msgClass.getMessageString(40));
			msg.setINADD2(msgClass.getMessageString(40));
			msg.setINADD3(msgClass.getMessageString(40));
			msg.setINADD4(msgClass.getMessageString(40));
			msg.setINCITY(msgClass.getMessageString(200));
			msg.setINSTAT(msgClass.getMessageString(3));
			msg.setINZIP(msgClass.getMessageString(9));
			msg.setI2ADTY(msgClass.getMessageString(1));
			msg.setI2ADD1(msgClass.getMessageString(40));
			msg.setI2ADD2(msgClass.getMessageString(40));
			msg.setI2ADD3(msgClass.getMessageString(40));
			msg.setI2ADD4(msgClass.getMessageString(40));
			msg.setI2CITY(msgClass.getMessageString(200));
			msg.setI2STAT(msgClass.getMessageString(3));
			msg.setI2ZIP(msgClass.getMessageString(9));
			msg.setI3ADTY(msgClass.getMessageString(1));
			msg.setI3ADD1(msgClass.getMessageString(40));
			msg.setI3ADD2(msgClass.getMessageString(40));
			msg.setI3ADD3(msgClass.getMessageString(40));
			msg.setI3ADD4(msgClass.getMessageString(40));
			msg.setI3CITY(msgClass.getMessageString(200));
			msg.setI3STAT(msgClass.getMessageString(3));
			msg.setI3ZIP(msgClass.getMessageString(9));
			msg.setI4ADTY(msgClass.getMessageString(1));
			msg.setI4ADD1(msgClass.getMessageString(40));
			msg.setI4ADD2(msgClass.getMessageString(40));
			msg.setI4ADD3(msgClass.getMessageString(40));
			msg.setI4ADD4(msgClass.getMessageString(40));
			msg.setI4CITY(msgClass.getMessageString(200));
			msg.setI4STAT(msgClass.getMessageString(3));
			msg.setI4ZIP(msgClass.getMessageString(9));
			msg.setINTYPE(msgClass.getMessageString(10));
			msg.setINCURR(msgClass.getMessageString(4));
			msg.setINODT8(msgClass.getMessageNumber(8, false));
			msg.setINTERM(msgClass.getMessageNumber(5, false));
			msg.setINTMCD(msgClass.getMessageString(1));
			msg.setINLAMT(msgClass.getMessageNumber(17, 2, false));
			msg.setINPFRE(msgClass.getMessageNumber(3, false));
			msg.setINPFRQ(msgClass.getMessageString(1));
			msg.setINPDUE(msgClass.getMessageNumber(8, false));
			msg.setINPDAY(msgClass.getMessageNumber(2, false));
			msg.setINCARP(msgClass.getMessageString(25));
			msg.setINPROV(msgClass.getMessageString(3));
			msg.setINCARC(msgClass.getMessageString(25));
			msg.setINMAKE(msgClass.getMessageString(5));
			msg.setINMODE(msgClass.getMessageString(5));
			msg.setINCPAM(msgClass.getMessageNumber(17, 2, false));
			msg.setREVAM1(msgClass.getMessageNumber(17, 2, false));
			msg.setREVAM2(msgClass.getMessageNumber(17, 2, false));
			msg.setREVAM3(msgClass.getMessageNumber(17, 2, false));
			msg.setREVAM4(msgClass.getMessageNumber(17, 2, false));
			msg.setREVAM5(msgClass.getMessageNumber(17, 2, false));
			msg.setREVAC1(msgClass.getMessageNumber(19, false));
			msg.setREVAC2(msgClass.getMessageNumber(19, false));
			msg.setREVCOA(msgClass.getMessageString(20));
			msg.setREVCOB(msgClass.getMessageString(20));
			msg.setREVCOC(msgClass.getMessageString(20));
			msg.setREVCO1(msgClass.getMessageString(10));
			msg.setREVCO2(msgClass.getMessageString(10));
			msg.setREVCO3(msgClass.getMessageString(10));
			msg.setINCCINS(msgClass.getMessageString(3));
			msg.setINCTOV(msgClass.getMessageNumber(3, false));
			msg.setININS8(msgClass.getMessageNumber(8, false));
			msg.setINENS8(msgClass.getMessageNumber(8, false));
			msg.setINIAMT(msgClass.getMessageNumber(17, 2, false));
			msg.setINPMAT(msgClass.getMessageNumber(17, 2, false));
			msg.setINACT(msgClass.getMessageString(3));
			msg.setINCST8(msgClass.getMessageNumber(8, false));
			msg.setINCEN8(msgClass.getMessageNumber(8, false));
			msg.setINACTA(msgClass.getMessageNumber(17, 2, false));
			msg.setMATDT8(msgClass.getMessageNumber(8, false));
			msg.setINCOM(msgClass.getMessageNumber(2, false));
			msg.setINBRN(msgClass.getMessageNumber(5, false));
			msg.setINERCH(msgClass.getMessageString(1));
			msg.setINGCIF(msgClass.getMessageNumber(19, false));
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTCLNI8000";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
