// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5009_TEXTRGDS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5009 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5009(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC5009_TEXTRGDS msg = new TC5009_TEXTRGDS(this.getContext());
		
		try
		{	
			int index = 0;
			StringBuffer strBuff = new StringBuffer();
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				if(index == 0)
				{
					//set Detail ingore TextAll
					msg.setTXNTYP(msgClass.getMessageNumber(1, 0));
					msg.setTXTKEY(msgClass.getMessageNumber(19, 0));
					msg.setTXNCAT(msgClass.getMessageString(6));
					msg.setTXTDAT(msgClass.getMessageNumber(8, 0));
					msg.setTXDTTM(msgClass.getMessageNumber(14, 0));
					msg.setTXUSER(msgClass.getMessageString(10));
					
					strBuff.append(msgClass.getMessageString(60, false));
					
					msg.setTXRMOD(msgClass.getMessageNumber(1, 0));
					msg.setTXRDAT(msgClass.getMessageNumber(8, 0));
					msg.setTXDLDT(msgClass.getMessageNumber(8, 0));
					msg.setTXOLIC(msgClass.getMessageString(40));
					msg.setTXDLBY(msgClass.getMessageString(10));
					msg.setTXWIND(msgClass.getMessageString(1));
					
					msg.setResponseCode("OK");
					msg.setResponseDescription("Successfully.");
				}
				else
				{
					//Concat Text to TextAll
					msgClass.getMessageNumber(1, 0);
					msgClass.getMessageNumber(19, 0);
					msgClass.getMessageString(6);
					msgClass.getMessageNumber(8, 0);
					msgClass.getMessageNumber(14, 0);
					msgClass.getMessageString(10);
					strBuff.append(msgClass.getMessageString(60, false));
					msgClass.getMessageNumber(1, 0);
					msgClass.getMessageNumber(8, 0);
					msgClass.getMessageNumber(8, 0);
					msgClass.getMessageString(40);
					msgClass.getMessageString(10);
					msgClass.getMessageString(1);
				}
				
				index += 1;
			}
			
			//Set AllText this field is all of note line
			msg.setAllText(strBuff.toString());
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5009";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
