// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5026_KNTRLL02DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5026 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5026(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5026_KNTRLL02DS msg = new TC5026_KNTRLL02DS(this.getContext());
				
				msg.setKNGACC(msgClass.getMessageNumber(19, 0));
				msg.setKNDTTM(msgClass.getMessageNumber(14, 0));
				msg.setKNKNTR(msgClass.getMessageString(6));
				msg.setKNRREF(msgClass.getMessageString(12));
				msg.setKNKRTN(msgClass.getMessageNumber(19, 0));
				msg.setKNSTAN(msgClass.getMessageNumber(6, 0));
				msg.setKNAUTP(msgClass.getMessageNumber(1, 0));
				msg.setWDDATE(msgClass.getMessageNumber(8, 0));
				msg.setWDTIME(msgClass.getMessageNumber(6, 0, true));
				msg.setKNMCC(msgClass.getMessageString(4));
				msg.setWDRESP(msgClass.getMessageString(3));
				msg.setWDBELS1(msgClass.getMessageNumber(15, 2));
				msg.setWDARJC(msgClass.getMessageString(4));
				msg.setKNASTS(msgClass.getMessageNumber(3, 0, true));
				msg.setKNSOVR(msgClass.getMessageString(1));
				msg.setKNBELB(msgClass.getMessageNumber(15, 2));
				msg.setKNBELS(msgClass.getMessageNumber(15, 2));
				msg.setKNBELI(msgClass.getMessageNumber(15, 2));
				msg.setKNBXAM(msgClass.getMessageNumber(15, 2));
				msg.setKNICTI(msgClass.getMessageString(1));
				msg.setWDNMOD(msgClass.getMessageString(1));
				msg.setKNTRXC(msgClass.getMessageString(4));
				msg.setTKTPAN(msgClass.getMessageNumber(19, 0));
				msg.setTKTKTP(msgClass.getMessageString(2));
				msg.setKNQRPI(msgClass.getMessageString(3));
				msg.setKNMPAN(msgClass.getMessageNumber(19, 0));
				msg.setWDDEVC(msgClass.getMessageString(5));

				
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5026_KNTRLL02DS msg = new TC5026_KNTRLL02DS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5026";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
