// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TCLNI8808Rs;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTCLNI8808 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTCLNI8808(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TCLNI8808Rs msg = new TCLNI8808Rs(this.getContext());
		
		try
		{
			// Start Detail for TC
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
		
			msg.setLWSACT(msgClass.getMessageNumber(19, false));
			msg.setLWSSTS(msgClass.getMessageString(1));
			msg.setLWSRSN(msgClass.getMessageString(2));
			msg.setLWSSEQ(msgClass.getMessageString(22));
			msg.setLWSTXN(msgClass.getMessageString(22));
			msg.setWRSNDSC(msgClass.getMessageString(50));
			
			msg.setResponseCode("000");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTCLNI8808";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
