// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC3603_KNTRSK25DS_Rs;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC3603 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC3603(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC3603_KNTRSK25DS_Rs msg = new TC3603_KNTRSK25DS_Rs(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKRKRTN(msgClass.getMessageNumber(19, false));
			msg.setKRBKRD(msgClass.getMessageNumber(11, false));
			msg.setKRMLMF(msgClass.getMessageString(1));
			msg.setIPINCO(msgClass.getMessageNumber(15, 2));
			msg.setIPOTAM(msgClass.getMessageNumber(15, 2));
			msg.setIPARBG(msgClass.getMessageString(80));
			msg.setIPCTCD(msgClass.getMessageString(3));
			msg.setIPTEL3(msgClass.getMessageString(20));
			msg.setIPTELA(msgClass.getMessageString(20));
			msg.setIPTELH(msgClass.getMessageString(20));
			msg.setIPTELHE(msgClass.getMessageNumber(7, false));
			msg.setIPTELAE(msgClass.getMessageNumber(7, false));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC3603";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
