// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5045_IPPINSDS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5045 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5045(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5045_IPPINSDS msg = new TC5045_IPPINSDS(this.getContext());
				
				msg.setPIORNO(msgClass.getMessageNumber(7,true));
				msg.setPIORLN(msgClass.getMessageNumber(3,true));
				msg.setPIPYSQ(msgClass.getMessageNumber(3,false));
				msg.setPIABEL(msgClass.getMessageNumber(15,2));
				msg.setPIABDL(msgClass.getMessageNumber(8,false));
				msg.setPIDTTM(msgClass.getMessageNumber(14,false));
				msg.setPIIBEL(msgClass.getMessageNumber(15,2));
				msg.setWDINST(msgClass.getMessageNumber(15,2));
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				
				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5045_IPPINSDS msg = new TC5045_IPPINSDS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5045";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
