// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC8214_KNTRSK09DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC8214 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC8214(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC8214_KNTRSK09DS msg = new TC8214_KNTRSK09DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKRKNTN1(msgClass.getMessageNumber(19, 0));
			msg.setKRKNTN2(msgClass.getMessageNumber(19, 0));
			msg.setKTKRTN(msgClass.getMessageNumber(19, 0));
			msg.setIPKIPN(msgClass.getMessageNumber(19, 0));
			msg.setKTSVID(msgClass.getMessageString(6));
			msg.setKRATP1(msgClass.getMessageString(1));
			msg.setKRCBIL(msgClass.getMessageString(1));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPLSNM(msgClass.getMessageString(40));
			msg.setIPCBIL(msgClass.getMessageString(1));
			msg.setWDYENO(msgClass.getMessageString(1));
			msg.setIPLTID(msgClass.getMessageString(6));
			msg.setWDIND1(msgClass.getMessageString(1));
			msg.setIPDTTM(msgClass.getMessageNumber(14, 0));
			msg.setKRDTTM(msgClass.getMessageNumber(14, 0));
			msg.setKRLBIL(msgClass.getMessageString(1));
			msg.setKTCLEC(msgClass.getMessageString(6));
			msg.setKTCBI2(msgClass.getMessageString(1));
			msg.setKTCBI3(msgClass.getMessageString(1));
			msg.setWDDEVC(msgClass.getMessageString(5));



			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC8214";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
