// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TCVC860072Rs;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTCVC860072 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTCVC860072(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TCVC860072Rs msg = new TCVC860072Rs(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setVI5ITM(msgClass.getMessageString(10));
			msg.setVIDESC(msgClass.getMessageString(50));
			msg.setVL1RPS(msgClass.getMessageNumber(17, 2));
			msg.setVI5AVI(msgClass.getMessageNumber(17, 2));
			msg.setVI5SUP(msgClass.getMessageNumber(19, 0));
			msg.setVI5MER(msgClass.getMessageString(40));
			msg.setVI5XD8(msgClass.getMessageNumber(8, false));
			msg.setV1CAMP(msgClass.getMessageString(10));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTCVC860072";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
