// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TCVC850070Rs;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTCVC850070 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTCVC850070(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
	
		
		try {
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length()) {
				
				TCVC850070Rs msg = new TCVC850070Rs(this.getContext());
				
				msg.setVHACNO(msgClass.getMessageNumber(19, 0));
				msg.setVHACTY(msgClass.getMessageString(1));
				msg.setVHCRDN(msgClass.getMessageNumber(19, 0));
				msg.setVHBATN(msgClass.getMessageNumber(9, 0));
				msg.setVHSEQN(msgClass.getMessageNumber(7, 0));
				msg.setVHSSEQ(msgClass.getMessageNumber(7, 0));
				msg.setVHTXCD(msgClass.getMessageNumber(4, 0));
				msg.setVHTGRP(msgClass.getMessageString(3));
				msg.setVHDORC(msgClass.getMessageString(1));
				msg.setVHTRX8(msgClass.getMessageNumber(8, false));
				msg.setVHTRDT(msgClass.getMessageNumber(8, false));
				msg.setVHTAMT(msgClass.getMessageNumber(17, 2));
				msg.setVHTCUR(msgClass.getMessageString(4));
				msg.setVHTAM2(msgClass.getMessageNumber(17, 2));
				msg.setVHTCU2(msgClass.getMessageString(4));
				msg.setVHSMER(msgClass.getMessageString(50));
				msg.setVHCHNL(msgClass.getMessageString(10));
				msg.setVHRDCD(msgClass.getMessageString(10));
				msg.setVHRISC(msgClass.getMessageString(50));
				msg.setVHQTY(msgClass.getMessageNumber(17, 2));
				msg.setVHSDTM(msgClass.getMessageNumber(6, 0));
				msg.setVHTSTS(msgClass.getMessageNumber(3, 0));
				msg.setVHOBNT(msgClass.getMessageNumber(9, 0));
				msg.setVHOSEQ(msgClass.getMessageNumber(7, 0));
				msg.setVHOSSQ(msgClass.getMessageNumber(7, 0));
				msg.setVMSCIF(msgClass.getMessageNumber(19, 0));
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				list.add(msg.getMendixObject());
				
			}
		}
		catch (Exception ex)
		{
			TCVC850070Rs msg = new TCVC850070Rs(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTCVC850070";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
