// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC8474_LIMRQS03DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC8474 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC8474(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC8474_LIMRQS03DS msg = new TC8474_LIMRQS03DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			

			msg.setLPKNTN(msgClass.getMessageNumber(19,0));
			msg.setLPLMNO(msgClass.getMessageNumber(9,0));
			msg.setLPRLIM(msgClass.getMessageNumber(11,0));
			msg.setLPALIM(msgClass.getMessageNumber(11,0));
			msg.setLPRSLM(msgClass.getMessageNumber(11,0));
			msg.setLPASLM(msgClass.getMessageNumber(11,0));
			msg.setLPRLIS(msgClass.getMessageNumber(11,0));
			msg.setLPALIS(msgClass.getMessageNumber(11,0));
			msg.setLPRSLS(msgClass.getMessageNumber(11,0));
			msg.setLPASLS(msgClass.getMessageNumber(11,0));
			msg.setLPREF(msgClass.getMessageString(15));
			msg.setLPEFDT(msgClass.getMessageNumber(8,0));
			msg.setLPRVDT(msgClass.getMessageNumber(8,0));
			msg.setLPEXDT(msgClass.getMessageNumber(8,0));
			msg.setLPLMST(msgClass.getMessageString(1));
			msg.setWDLMST(msgClass.getMessageString(1));
			msg.setLPAPRS(msgClass.getMessageString(3));
			msg.setLPUPDD(msgClass.getMessageNumber(8,0));
			msg.setLPUPBY(msgClass.getMessageString(10));
			msg.setLPACTV(msgClass.getMessageString(1));
			msg.setLPPCLM(msgClass.getMessageNumber(11,0));
			msg.setLPPSLM(msgClass.getMessageNumber(11,0));
			msg.setLPPCLS(msgClass.getMessageNumber(11,0));
			msg.setLPPSLS(msgClass.getMessageNumber(11,0));
			msg.setLPEDIT(msgClass.getMessageString(1));
			msg.setLPURGN(msgClass.getMessageString(3));
			msg.setLPLSDT(msgClass.getMessageNumber(8,0));
			msg.setLPAUAP(msgClass.getMessageString(1));
			msg.setLPDTTM(msgClass.getMessageNumber(14,0));
			msg.setLPAVOR(msgClass.getMessageString(3));
			msg.setWDSACC(msgClass.getMessageString(1));
			msg.setKRKNTN(msgClass.getMessageNumber(19,0));
			msg.setKRUPDT(msgClass.getMessageNumber(8,0));
			msg.setKRBKRD(msgClass.getMessageNumber(11,0));
			msg.setKRSLMT(msgClass.getMessageNumber(11,0));
			msg.setWDGLIM(msgClass.getMessageNumber(11,0));
			msg.setWDGSLM(msgClass.getMessageNumber(11,0));
			msg.setKRAVST(msgClass.getMessageNumber(3,0));
			msg.setKRRKID(msgClass.getMessageString(6));
			msg.setKRKNST(msgClass.getMessageNumber(3,0));
			msg.setKRATP1(msgClass.getMessageString(1));
			msg.setKRBCDE(msgClass.getMessageString(3));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPLSNM(msgClass.getMessageString(40));
			msg.setIPLCDE(msgClass.getMessageString(3));
			msg.setIPKRTN(msgClass.getMessageNumber(19,0));
			msg.setWDREQL(msgClass.getMessageString(1));
			msg.setKTEMNM(msgClass.getMessageString(26));
			msg.setKRACCP(msgClass.getMessageNumber(2,0));
			msg.setKRLMTF(msgClass.getMessageString(1));
			msg.setBSSCLN(msgClass.getMessageString(5));
			msg.setBSCRLN(msgClass.getMessageNumber(10,0));
			msg.setBSCRSC(msgClass.getMessageNumber(10,0));
			msg.setBSCRFL(msgClass.getMessageString(2));
			msg.setBSCSHR(msgClass.getMessageNumber(6,3));
			msg.setBSDEQH(msgClass.getMessageString(24));
			msg.setBSUPDD(msgClass.getMessageNumber(8,0));


			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC8474";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
