// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5210_CUSAUT01DS_Rsp;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5210 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5210(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass =  new MessageClass();
		TC5210_CUSAUT01DS_Rsp msg = new TC5210_CUSAUT01DS_Rsp(this.getContext());  //Current Balance
		
		
		try {
			
			//Start Detail 
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setIPKIPN(msgClass.getMessageNumber(19,0));
			msg.setKTKRTN(msgClass.getMessageNumber(19,0));
			msg.setIPMONM(msgClass.getMessageString(40));
			msg.setIPFDAT(msgClass.getMessageNumber(8,0));
			msg.setIPTELA(msgClass.getMessageString(15));
			msg.setIPTELH(msgClass.getMessageString(15));
			msg.setIPTEL3(msgClass.getMessageString(15));
			msg.setKRBKRD(msgClass.getMessageNumber(11,0));
			msg.setCHLPAY(msgClass.getMessageNumber(15,2));
			msg.setCHIBDT(msgClass.getMessageNumber(8,0));
			msg.setCHLSTA(msgClass.getMessageNumber(15,2));
			msg.setCHLSTR(msgClass.getMessageNumber(8,0));
			msg.setIPADR1(msgClass.getMessageString(40));
			msg.setIPADR2(msgClass.getMessageString(40));
			msg.setIPADR3(msgClass.getMessageString(40));
			msg.setIPADR4(msgClass.getMessageString(40));
			msg.setIPPNR(msgClass.getMessageString(9));
			msg.setIPCITY(msgClass.getMessageString(40));
			msg.setIPLSTE(msgClass.getMessageString(3));
			msg.setIPCNCD(msgClass.getMessageString(3));
			msg.setKRKNTN(msgClass.getMessageNumber(19,0));
			msg.setIPOLIC(msgClass.getMessageString(40));
			msg.setIPEMLP(msgClass.getMessageString(100));
			msg.setKRPLIM(msgClass.getMessageNumber(11,0));
			msg.setKRSLMT(msgClass.getMessageNumber(11,0));
			msg.setKRTLIM(msgClass.getMessageNumber(11,0));
			msg.setKRTLDT(msgClass.getMessageNumber(8,0));

			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
			
			
		
		} catch (Exception ex) {

			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5210";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
