// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1401_KNTEXS02DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC1401 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC1401(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC1401_KNTEXS02DS msg = new TC1401_KNTEXS02DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setLLKNTN(msgClass.getMessageNumber(19,0));
			msg.setLLPYDT(msgClass.getMessageNumber(8,0));
			msg.setKRSLDO(msgClass.getMessageNumber(15,2));
			msg.setLLCIN1(msgClass.getMessageNumber(15,2));
			msg.setLLCIN2(msgClass.getMessageNumber(15,2));
			msg.setLLCOTH(msgClass.getMessageNumber(15,2));
			msg.setLLCTOT(msgClass.getMessageNumber(15,2));
			msg.setLLPIN1(msgClass.getMessageNumber(15,2));
			msg.setLLPIN2(msgClass.getMessageNumber(15,2));
			msg.setLLPOTH(msgClass.getMessageNumber(15,2));
			msg.setLLPTOT(msgClass.getMessageNumber(15,2));
			msg.setLLJIN1(msgClass.getMessageNumber(15,2));
			msg.setLLJIN2(msgClass.getMessageNumber(15,2));
			msg.setLLJOTH(msgClass.getMessageNumber(15,2));
			msg.setLLJTOT(msgClass.getMessageNumber(15,2));
			msg.setLLFLDO(msgClass.getMessageNumber(15,2));
			msg.setLLFIN1(msgClass.getMessageNumber(15,2));
			msg.setLLFIN2(msgClass.getMessageNumber(15,2));
			msg.setLLFOTH(msgClass.getMessageNumber(15,2));
			msg.setLLFTOT(msgClass.getMessageNumber(15,2));
			msg.setKRPRBO(msgClass.getMessageNumber(15,2));
			msg.setLLUFLX(msgClass.getMessageNumber(15,2));

			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1401";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
