// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5445_TMPTRA01D;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5445 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5445(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5445_TMPTRA01D msg = new TC5445_TMPTRA01D(this.getContext());

				msg.setTRBNTN(msgClass.getMessageNumber(9, 0));
				msg.setTRBLON(msgClass.getMessageNumber(7, 0));
				msg.setTRPEK(msgClass.getMessageNumber(7, 0));
				msg.setTRTTYP(msgClass.getMessageNumber(4, 0));
				msg.setTRBDAT(msgClass.getMessageNumber(8, 0));
				msg.setTRBKID(msgClass.getMessageNumber(11, 0));
				msg.setTRBEL(msgClass.getMessageNumber(15, 2));
				msg.setTRCCDE(msgClass.getMessageString(3));
				msg.setTRREF(msgClass.getMessageString(15));
				msg.setTRCHID(msgClass.getMessageString(1));
				msg.setTRMTIN(msgClass.getMessageString(1));
				msg.setTRREFN(msgClass.getMessageString(15));
				msg.setTRBR(msgClass.getMessageNumber(5, 0));
				msg.setTRCANM(msgClass.getMessageString(40));
				msg.setTRRGKR(msgClass.getMessageString(1));
				msg.setTRDTTM(msgClass.getMessageNumber(14, 0));
				msg.setWDBBEL(msgClass.getMessageNumber(15, 2));
				msg.setWDBANT(msgClass.getMessageNumber(7, 0));
				msg.setWDREG(msgClass.getMessageNumber(15, 2));
				msg.setWDREGT(msgClass.getMessageNumber(7, 0));
				msg.setWDDIFF(msgClass.getMessageNumber(15, 2));
				msg.setWDDIFT(msgClass.getMessageNumber(7, 0));
				msg.setWDSUB1(msgClass.getMessageString(1));
				msg.setWDLINE(msgClass.getMessageNumber(4, 0));
				msg.setWDRKID(msgClass.getMessageString(6));
				msg.setWDTTYP1(msgClass.getMessageNumber(4, 0));
				msg.setWDKRTN(msgClass.getMessageNumber(19, 0));
				msg.setWDBEL(msgClass.getMessageNumber(15, 2));
				msg.setWDKNTR(msgClass.getMessageString(6));
				msg.setWDTRDT(msgClass.getMessageNumber(8, 0));
				msg.setWDVLDT(msgClass.getMessageNumber(8, 0));
				msg.setWDSUBA(msgClass.getMessageString(1));
				msg.setWDADES1(msgClass.getMessageString(50));
				msg.setWDRFN1(msgClass.getMessageString(15));
				msg.setWDOGDT(msgClass.getMessageNumber(8, 0));
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");

				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC5445_TMPTRA01D msg = new TC5445_TMPTRA01D(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5445";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
