// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC2211_LMTCTL02DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC2211 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC2211(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC2211_LMTCTL02DS msg = new TC2211_LMTCTL02DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setLMGNUM(msgClass.getMessageNumber(19, 0));
			msg.setLMGLMN(msgClass.getMessageNumber(19, 0));
			msg.setWDLLVL(msgClass.getMessageNumber(3, 0));
			msg.setWDKIPN(msgClass.getMessageNumber(19, 0));
			msg.setWDUINI(msgClass.getMessageString(40));
			msg.setWDULSN(msgClass.getMessageString(40));
			msg.setWDBKRD(msgClass.getMessageNumber(11, 0));
			msg.setWDSLMT(msgClass.getMessageNumber(11, 0));
			msg.setWDPRBO(msgClass.getMessageNumber(15, 2));
			msg.setWDEARM(msgClass.getMessageNumber(15, 2));
			msg.setWDUSGA(msgClass.getMessageNumber(15, 2));
			msg.setWDDBAL(msgClass.getMessageNumber(15, 2));
			msg.setWDUUTL(msgClass.getMessageNumber(11, 0));
			msg.setWDUAVI(msgClass.getMessageNumber(11, 0));
			msg.setWDUSAL(msgClass.getMessageNumber(11, 0));
			msg.setWDUSAV(msgClass.getMessageNumber(11, 0));
			msg.setWDUCAL(msgClass.getMessageNumber(11, 0));
			msg.setWDUCAV(msgClass.getMessageNumber(11, 0));
			msg.setWDUNOA(msgClass.getMessageNumber(5, 0));
			msg.setWDDESC(msgClass.getMessageString(25));
			msg.setWDSPKD(msgClass.getMessageNumber(1, 0));
			msg.setWDSPRK(msgClass.getMessageString(2));
			msg.setWDSPDT(msgClass.getMessageNumber(8, 0));
			msg.setWDRPTL(msgClass.getMessageString(1));
			msg.setWDCKUP(msgClass.getMessageString(1));
			msg.setWDSHRD(msgClass.getMessageString(1));
			msg.setWDGBAC(msgClass.getMessageNumber(19, 0));
			msg.setWDCRCC(msgClass.getMessageString(3));
			msg.setWDSTCC(msgClass.getMessageString(3));
			msg.setWDTCRL(msgClass.getMessageNumber(11, 0));
			msg.setWDTSTL(msgClass.getMessageNumber(11, 0));
			msg.setWDEXDT(msgClass.getMessageNumber(8, 0));
			msg.setLMLNUM(msgClass.getMessageNumber(19, 0));
			msg.setLMLLVL(msgClass.getMessageNumber(3, 0));
			msg.setLMDESC(msgClass.getMessageString(25));
			msg.setLMKIPN(msgClass.getMessageNumber(19, 0));
			msg.setWDINIT(msgClass.getMessageString(40));
			msg.setWDLSNM(msgClass.getMessageString(40));
			msg.setLMBKRD(msgClass.getMessageNumber(11, 0));
			msg.setLMSLMT(msgClass.getMessageNumber(11, 0));
			msg.setLMPRBO(msgClass.getMessageNumber(15, 2));
			msg.setLMEARM(msgClass.getMessageNumber(15, 2));
			msg.setLMUSGA(msgClass.getMessageNumber(15, 2));
			msg.setLMDBAL(msgClass.getMessageNumber(15, 2));
			msg.setWDUTIL(msgClass.getMessageNumber(15, 2));
			msg.setWDAVAI(msgClass.getMessageNumber(15, 2));
			msg.setLMSALC(msgClass.getMessageNumber(11, 0));
			msg.setWDSAAV(msgClass.getMessageNumber(11, 0));
			msg.setLMCALC(msgClass.getMessageNumber(11, 0));
			msg.setWDCAAV(msgClass.getMessageNumber(11, 0));
			msg.setLMNOAC(msgClass.getMessageNumber(5, 0));
			msg.setLMSPKD(msgClass.getMessageNumber(1, 0));
			msg.setLMSPRK(msgClass.getMessageString(2));
			msg.setWDNXAC(msgClass.getMessageString(1));
			msg.setLMDTTM(msgClass.getMessageNumber(14, 0));
			msg.setLMSPDT(msgClass.getMessageNumber(8, 0));
			msg.setLMRPTL(msgClass.getMessageString(1));
			msg.setLMCKUP(msgClass.getMessageString(1));
			msg.setLMSHRD(msgClass.getMessageString(1));
			msg.setLMGBAC(msgClass.getMessageNumber(19, 0));
			msg.setLMCRCC(msgClass.getMessageString(3));
			msg.setLMSTCC(msgClass.getMessageString(3));
			msg.setLMTCRL(msgClass.getMessageNumber(11, 0));
			msg.setLMTSTL(msgClass.getMessageNumber(11, 0));
			msg.setLMEXDT(msgClass.getMessageNumber(8, 0));	
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC2211";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
