// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9406_KNTRSK10DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC9406 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9406(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9406_KNTRSK10DS msg = new TC9406_KNTRSK10DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
						
			msg.setKRKNTN(msgClass.getMessageNumber(19,0));
			msg.setKRRKID(msgClass.getMessageString(6));
			msg.setKRKAID(msgClass.getMessageString(3));
			msg.setKRCCDE(msgClass.getMessageString(3));
			msg.setKRPGRP(msgClass.getMessageString(3));
			msg.setKRBKRD(msgClass.getMessageNumber(11,0));
			msg.setKRSLMT(msgClass.getMessageNumber(11,0));
			msg.setKRAVIF(msgClass.getMessageNumber(1,0));
			msg.setKRAVFA(msgClass.getMessageString(1));
			msg.setKRSTGR(msgClass.getMessageString(1));
			msg.setKRUSC1(msgClass.getMessageString(3));
			msg.setKRUSC2(msgClass.getMessageString(3));
			msg.setKRUSC3(msgClass.getMessageString(3));
			msg.setKRUSC4(msgClass.getMessageString(3));
			msg.setKRSTRC(msgClass.getMessageString(6));
			msg.setKRDTTM(msgClass.getMessageNumber(14,0));
			msg.setKRGACC(msgClass.getMessageNumber(19,0));
			msg.setKRPRIO(msgClass.getMessageNumber(1,0));
			msg.setKRTCGR(msgClass.getMessageString(3));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPKIPN(msgClass.getMessageNumber(19,0));
			msg.setIPCTCD(msgClass.getMessageString(3));
			msg.setKTKRTN(msgClass.getMessageNumber(19,0));
			msg.setKTSVID(msgClass.getMessageString(6));
			msg.setSRDESC(msgClass.getMessageString(25));
			msg.setSRKAID(msgClass.getMessageString(3));
			msg.setTXUSER(msgClass.getMessageString(10));
			msg.setGCDESC(msgClass.getMessageString(25));
			msg.setCGDESC(msgClass.getMessageString(25));
			msg.setIPLSNM(msgClass.getMessageString(40));
			msg.setIPFDAT(msgClass.getMessageNumber(8,0));
			msg.setKRAVST(msgClass.getMessageNumber(3,0));
			msg.setKRLMTF(msgClass.getMessageString(1));
			msg.setWDMM(msgClass.getMessageNumber(2,0));
			msg.setWDYY(msgClass.getMessageNumber(4,0));
			msg.setKRATML(msgClass.getMessageString(1));
			msg.setKRSEQ1(msgClass.getMessageNumber(4,0));
			msg.setKRMISF(msgClass.getMessageString(1));
			msg.setKRMISN(msgClass.getMessageString(32));
			msg.setKRMISP(msgClass.getMessageString(25));
			msg.setIPNAM2(msgClass.getMessageString(40));
			msg.setWDCORP(msgClass.getMessageNumber(19,0));
			msg.setWDSTMI(msgClass.getMessageString(1));
			msg.setKRGLPR(msgClass.getMessageNumber(2,0));			
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9406";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
