// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5031_KNTUTD03DSRsp;
import ktc_scs_schema.proxies.TC5036_IPPORD01DSRsp;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5031 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;

	public GetTC5031(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try {
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length()) {
				
				TC5031_KNTUTD03DSRsp msg = new TC5031_KNTUTD03DSRsp(this.getContext());
				
				msg.setKUKNTN(msgClass.getMessageNumber(19,0));
				msg.setKUPERI(msgClass.getMessageNumber(5,0));
				msg.setTRTYP(msgClass.getMessageNumber(1,0));
				msg.setTRBNTN(msgClass.getMessageNumber(9,0));
				msg.setTRBLON(msgClass.getMessageNumber(7,0));
				msg.setTRTRDT(msgClass.getMessageNumber(8,0));
				msg.setTRBDAT(msgClass.getMessageNumber(8,0));
				msg.setTRCANM(msgClass.getMessageString(40));
				msg.setTRTTYP(msgClass.getMessageNumber(4,0));
				msg.setDPSTAS(msgClass.getMessageString(1));
				msg.setTRBELB(msgClass.getMessageNumber(15,2));
				msg.setLINTYP(msgClass.getMessageNumber(1,0));
				msg.setKTKRTN(msgClass.getMessageNumber(19,0));
				
				msg.setResponseCode("OK");
				msg.setDescription("Successfully.");

				list.add(msg.getMendixObject());
			}
			
			
		} catch (Exception ex) {
			
			TC5036_IPPORD01DSRsp msg = new TC5036_IPPORD01DSRsp(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
			
		}
		
		return list;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5031";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
