// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC3616;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC3616 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC3616(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC3616 msg = new TC3616(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKTKRTN(msgClass.getMessageNumber(19,0));
			msg.setKTKPBL(msgClass.getMessageString(16));
			msg.setKTTYPE(msgClass.getMessageString(1));
			msg.setKTKPBLO(msgClass.getMessageString(16));
			
			msg.setCode("OK");
			msg.setDescription("Successfully.");

		}
		catch (Exception ex)
		{
			msg.setCode("ER");
			msg.setDescription(ex.getMessage());
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC3616";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
