// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1602_KORTRG12DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1602 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC1602(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC1602_KORTRG12DS msg = new TC1602_KORTRG12DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setKTKRTN(msgClass.getMessageNumber(19, false));
			msg.setKTRKID(msgClass.getMessageString(6));
			msg.setKTKNTN(msgClass.getMessageNumber(19, false));
			msg.setKTSVID(msgClass.getMessageString(6));
			msg.setKTSPLV(msgClass.getMessageNumber(3, false));
			msg.setKTCPGM(msgClass.getMessageString(3));
			msg.setKTKIPN(msgClass.getMessageNumber(19, false));
			msg.setKTLOPN(msgClass.getMessageNumber(11, false));
			msg.setKTEMNM(msgClass.getMessageString(26));
			msg.setKTEMN1(msgClass.getMessageString(26));
			msg.setKTEMDT(msgClass.getMessageNumber(8, false));
			msg.setKTGTDT(msgClass.getMessageNumber(4, true));
			msg.setKTGTDP(msgClass.getMessageNumber(4, true));
			msg.setKTGTST(msgClass.getMessageString(1));
			msg.setKTSPKD(msgClass.getMessageNumber(1, true));
			msg.setKTKRST(msgClass.getMessageNumber(3, true));
			msg.setKTSPDT(msgClass.getMessageNumber(8, true));
			msg.setKTKTTP(msgClass.getMessageString(3));
			msg.setKTUSER(msgClass.getMessageString(10));
			msg.setKTPVV(msgClass.getMessageString(4));
			msg.setKTKPBL(msgClass.getMessageString(16));
			msg.setKTDSKF(msgClass.getMessageNumber(8, true));
			msg.setKTFPKF(msgClass.getMessageNumber(1, false));
			msg.setKTPVKI(msgClass.getMessageNumber(2, false));
			msg.setKTSRVC(msgClass.getMessageNumber(3, true));
			msg.setKTAKFR(msgClass.getMessageNumber(3, false));
			msg.setKTWAMK(msgClass.getMessageNumber(13, false));
			msg.setKTAUDT(msgClass.getMessageNumber(8, true));
			msg.setKTNODT(msgClass.getMessageNumber(3, false));
			msg.setKTAMDT(msgClass.getMessageNumber(11, false));
			msg.setKTSADT(msgClass.getMessageNumber(8, true));
			msg.setKTNOPD(msgClass.getMessageNumber(3, false));
			msg.setKTAMPD(msgClass.getMessageNumber(11, false));
			msg.setKTNOD(msgClass.getMessageNumber(1, false));
			msg.setKTCVV(msgClass.getMessageNumber(3, false));
			msg.setKTIADT(msgClass.getMessageNumber(8, true));
			msg.setKTNIDT(msgClass.getMessageNumber(3, false));
			msg.setKTAIDT(msgClass.getMessageNumber(11, false));
			msg.setKTSIDT(msgClass.getMessageNumber(8, true));
			msg.setKTNIPD(msgClass.getMessageNumber(3, false));
			msg.setKTIAPD(msgClass.getMessageNumber(11, false));
			msg.setKTNTRD(msgClass.getMessageNumber(3, false));
			msg.setKTNTRC(msgClass.getMessageNumber(3, false));
			msg.setKTAATT(msgClass.getMessageNumber(3, false));
			msg.setKTCLEC(msgClass.getMessageString(6));
			msg.setKTCHR1(msgClass.getMessageString(1));
			msg.setKTREF(msgClass.getMessageString(15));
			msg.setKTPINR(msgClass.getMessageString(1));
			msg.setKTPNRI(msgClass.getMessageString(1));
			msg.setKTLPRD(msgClass.getMessageNumber(8, true));
			msg.setKTRNST(msgClass.getMessageNumber(3, true));
			msg.setKTRRJC(msgClass.getMessageNumber(3, true));
			msg.setKTRWDT(msgClass.getMessageNumber(8, true));
			msg.setKTAKDT(msgClass.getMessageNumber(8, true));
			msg.setKTREMC(msgClass.getMessageString(2));
			msg.setKTLEMD(msgClass.getMessageNumber(8, true));
			msg.setKTLPGD(msgClass.getMessageNumber(8, true));
			msg.setKTBKRD(msgClass.getMessageNumber(11, false));
			msg.setKTPRBO(msgClass.getMessageNumber(15, 2));
			msg.setKTCLDT(msgClass.getMessageNumber(8, true));
			msg.setKTTPDT(msgClass.getMessageNumber(8, true));
			msg.setKTAINB(msgClass.getMessageNumber(15, 2));
			msg.setKTFUDT(msgClass.getMessageNumber(8, true));
			msg.setKTOTYP(msgClass.getMessageString(6));
			msg.setKTCVV2(msgClass.getMessageNumber(3, false));
			msg.setKTATRA(msgClass.getMessageNumber(15, 2));
			msg.setKTARNT(msgClass.getMessageNumber(15, 2));
			msg.setKTLTXA(msgClass.getMessageNumber(15, 2));
			msg.setKTLSTR(msgClass.getMessageNumber(8, true));
			msg.setKTYTDT(msgClass.getMessageNumber(15, 2));
			msg.setKTLYTA(msgClass.getMessageNumber(15, 2));
			msg.setKTECHG(msgClass.getMessageString(1));
			msg.setKTDTTM(msgClass.getMessageNumber(14, true));
			msg.setKTCGEN(msgClass.getMessageString(6));
			msg.setKTCBI2(msgClass.getMessageString(1));
			msg.setKTCBI3(msgClass.getMessageString(1));
			msg.setKTADAT(msgClass.getMessageNumber(8, true));
			msg.setKTWACD(msgClass.getMessageString(1));
			msg.setKTAAY(msgClass.getMessageNumber(3, false));
			msg.setKTCMPD(msgClass.getMessageString(54));
			msg.setKTPMPD(msgClass.getMessageString(54));
			msg.setKTVECS(msgClass.getMessageString(3));
			msg.setKTICCI(msgClass.getMessageString(1));
			msg.setKTLEBD(msgClass.getMessageNumber(8, true));
			msg.setKTLPID(msgClass.getMessageNumber(8, true));
			msg.setKTFPIN(msgClass.getMessageNumber(8, true));
			msg.setKTICFD(msgClass.getMessageNumber(8, true));
			msg.setKTDEAC(msgClass.getMessageString(1));
			msg.setKTDEDT(msgClass.getMessageNumber(8, false));
			msg.setKTNCGN(msgClass.getMessageNumber(3, false));
			msg.setKTBR(msgClass.getMessageNumber(5, false));
			msg.setKTPHTO(msgClass.getMessageString(1));
			msg.setKTCSQN(msgClass.getMessageNumber(3, false));
			msg.setKTDECH(msgClass.getMessageString(2));
			msg.setKTCEVT(msgClass.getMessageString(1));
			msg.setWDKIPN(msgClass.getMessageNumber(19, false));
			msg.setWDRESU(msgClass.getMessageString(2));
			msg.setK2RQDT(msgClass.getMessageNumber(8, false));
			msg.setIPLSNM(msgClass.getMessageString(40));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPINIT(msgClass.getMessageString(40));
			msg.setIPNAM2(msgClass.getMessageString(40));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1602";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
