// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1600_INPART06DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1600 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC1600(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC1600_INPART06DS msg = new TC1600_INPART06DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setIPKIPN(msgClass.getMessageNumber(19, false));
			msg.setIPPENO(msgClass.getMessageNumber(11, false));
			msg.setIPITYP(msgClass.getMessageNumber(1, true));
			msg.setIPFRNM(msgClass.getMessageString(20));
			msg.setIPINIT(msgClass.getMessageString(40));
			msg.setIPLSNM(msgClass.getMessageString(40));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPNAM2(msgClass.getMessageString(40));
			msg.setIPEMNM(msgClass.getMessageString(26));
			msg.setIPEMN1(msgClass.getMessageString(26));
			msg.setIPHUS(msgClass.getMessageString(3));
			msg.setIPFLDT(msgClass.getMessageNumber(6, true));
			msg.setIPADRF(msgClass.getMessageString(1));
			msg.setIPSEQ1(msgClass.getMessageNumber(4, false));
			msg.setIPADR1(msgClass.getMessageString(40));
			msg.setIPADR2(msgClass.getMessageString(40));
			msg.setIPADR3(msgClass.getMessageString(40));
			msg.setIPADR4(msgClass.getMessageString(40));
			msg.setIPPNR(msgClass.getMessageString(9));
			msg.setIPCITY(msgClass.getMessageString(40));
			msg.setIPLSTE(msgClass.getMessageString(3));
			msg.setIPCNCD(msgClass.getMessageString(3));
			msg.setIPTELH(msgClass.getMessageString(20));
			msg.setIPTELA(msgClass.getMessageString(20));
			msg.setIPFAX1(msgClass.getMessageString(20));
			msg.setIPEMLP(msgClass.getMessageString(100));
			msg.setIPEML1(msgClass.getMessageString(30));
			msg.setIPCBIL(msgClass.getMessageString(1));
			msg.setIPNATI(msgClass.getMessageString(3));
			msg.setIPSEX(msgClass.getMessageNumber(1, true));
			msg.setIPFDAT(msgClass.getMessageNumber(8, false));
			msg.setIPFORT(msgClass.getMessageString(25));
			msg.setIPCIVS(msgClass.getMessageString(3));
			msg.setIPBERO(msgClass.getMessageNumber(3, false));
			msg.setIPTITL(msgClass.getMessageString(6));
			msg.setIPMMTL(msgClass.getMessageNumber(3, false));
			msg.setIPBRCD(msgClass.getMessageString(1));
			msg.setIPCTCD(msgClass.getMessageString(3));
			msg.setIPRISC(msgClass.getMessageString(3));
			msg.setIPLCDE(msgClass.getMessageString(3));
			msg.setIPCONO(msgClass.getMessageNumber(3, false));
			msg.setIPCODT(msgClass.getMessageNumber(8, true));
			msg.setIPPRVH(msgClass.getMessageString(1));
			msg.setIPOLAC(msgClass.getMessageNumber(19, false));
			msg.setIPAKRT(msgClass.getMessageString(1));
			msg.setIPBGNO(msgClass.getMessageNumber(19, false));
			msg.setIPBANM(msgClass.getMessageString(40));
			msg.setIPKNTL(msgClass.getMessageNumber(5, false));
			msg.setIPOLIC(msgClass.getMessageString(40));
			msg.setIPITP1(msgClass.getMessageString(3));
			msg.setIPNWIC(msgClass.getMessageString(40));
			msg.setIPITP2(msgClass.getMessageString(3));
			msg.setIPUSC1(msgClass.getMessageString(3));
			msg.setIPUSC2(msgClass.getMessageString(3));
			msg.setIPUSC3(msgClass.getMessageString(3));
			msg.setIPUSC4(msgClass.getMessageString(3));
			msg.setIPINCD(msgClass.getMessageString(1));
			msg.setIPHEDU(msgClass.getMessageString(3));
			msg.setIPRACE(msgClass.getMessageString(6));
			msg.setIPMONM(msgClass.getMessageString(40));
			msg.setIPLIAB(msgClass.getMessageString(1));
			msg.setIPCTNM(msgClass.getMessageString(40));
			msg.setIPRCTP(msgClass.getMessageString(1));
			msg.setIPREST(msgClass.getMessageString(1));
			msg.setIPMBRS(msgClass.getMessageNumber(6, true));
			msg.setIPDCSD(msgClass.getMessageString(1));
			msg.setIPBOD6(msgClass.getMessageNumber(19, false));
			msg.setIPDTTM(msgClass.getMessageNumber(14, true));
			msg.setIPTEL3(msgClass.getMessageString(20));
			msg.setIPRELG(msgClass.getMessageString(6));
			msg.setIPLBIL(msgClass.getMessageString(1));
			msg.setIPEXDT(msgClass.getMessageNumber(8, true));
			msg.setIPBVDT(msgClass.getMessageNumber(8, true));
			msg.setIPPSTS(msgClass.getMessageString(1));
			msg.setIPCIDT(msgClass.getMessageString(3));
			msg.setIPCLAS(msgClass.getMessageString(1));
			msg.setIPGSTI(msgClass.getMessageString(1));
			msg.setIPBR(msgClass.getMessageNumber(5, false));
			msg.setIPCIFN(msgClass.getMessageNumber(19, false));
			msg.setIPFRN1(msgClass.getMessageString(20));
			msg.setIPFRN2(msgClass.getMessageString(20));
			msg.setIPFRN3(msgClass.getMessageString(20));
			msg.setIPCHID(msgClass.getMessageString(1));
			msg.setIPSFMY(msgClass.getMessageString(1));
			msg.setIPCSTS(msgClass.getMessageString(1));
			msg.setIPMSTS(msgClass.getMessageString(1));
			msg.setIPEMTL(msgClass.getMessageNumber(3, false));
			msg.setIPHMTL(msgClass.getMessageNumber(3, false));
			msg.setIPTCUS(msgClass.getMessageNumber(19, false));
			msg.setIPYEAR1(msgClass.getMessageNumber(3, true));
			msg.setIPINCO(msgClass.getMessageNumber(15, 2));
			msg.setIPOTAM(msgClass.getMessageNumber(15, 2));
			msg.setIPARBG(msgClass.getMessageString(80));
			msg.setIPARB2(msgClass.getMessageString(80));
			msg.setIPRLNM(msgClass.getMessageString(40));
			msg.setIPTELJ(msgClass.getMessageString(15));
			msg.setIPRLSP(msgClass.getMessageString(6));
			msg.setIPPPTY(msgClass.getMessageString(3));
			msg.setWDSTAY(msgClass.getMessageNumber(6, true));
			msg.setWDEMPL(msgClass.getMessageNumber(4, true));
			msg.setIPANST(msgClass.getMessageString(3));
			msg.setIPINDS(msgClass.getMessageString(6));
			msg.setWIPBERO(msgClass.getMessageNumber(2, false));
			msg.setWDSTAF(msgClass.getMessageString(1));
			msg.setIPTELHE(msgClass.getMessageNumber(7, false));
			msg.setIPTELAE(msgClass.getMessageNumber(7, false));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1600";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
