// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9404_KNTRSK32DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC9404 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9404(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		MessageClass msgClass =  new MessageClass();
		TC9404_KNTRSK32DS msg = new TC9404_KNTRSK32DS(this.getContext());  //Current Balance
		
		
		try {
			
			//Start Detail 
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;					
			
			msg.setKRKNTN(msgClass.getMessageNumber(19,0));
			msg.setKRUPDT(msgClass.getMessageNumber(8,0));
			msg.setKRBKRD(msgClass.getMessageNumber(11,0));
			msg.setKRSLMT(msgClass.getMessageNumber(11,0));
			msg.setKRLMTF(msgClass.getMessageString(1));
			msg.setKROTBM(msgClass.getMessageString(1));
			msg.setKRKAID(msgClass.getMessageString(3));
			msg.setKRCCDE(msgClass.getMessageString(3));
			msg.setKRSLDO(msgClass.getMessageNumber(15,2));
			msg.setKRUSLD(msgClass.getMessageNumber(15,2));
			msg.setKRLBET(msgClass.getMessageNumber(15,2));
			msg.setWDTOTD(msgClass.getMessageNumber(15,2));
			msg.setWDCURD(msgClass.getMessageNumber(15,2));
			msg.setKRFSMD(msgClass.getMessageString(3));
			msg.setKRFSM1(msgClass.getMessageString(3));
			msg.setKRFSM2(msgClass.getMessageString(3));
			msg.setKRF2VF(msgClass.getMessageNumber(6,0));
			msg.setKRAAY(msgClass.getMessageNumber(3,0));
			msg.setCAALVL(msgClass.getMessageNumber(3,0));
			msg.setKRRSTD(msgClass.getMessageNumber(8,0));
			msg.setKRRLVL(msgClass.getMessageNumber(3,0));
			msg.setKRRES1(msgClass.getMessageNumber(15,2));
			msg.setKRRES2(msgClass.getMessageNumber(15,2));
			msg.setKRRES3(msgClass.getMessageNumber(15,2));
			msg.setKRRES4(msgClass.getMessageNumber(15,2));
			msg.setKRRES5(msgClass.getMessageNumber(15,2));
			msg.setKRRES6(msgClass.getMessageNumber(15,2));
			msg.setKRRES7(msgClass.getMessageNumber(15,2));
			msg.setKRRES8(msgClass.getMessageNumber(15,2));
			msg.setKRRES9(msgClass.getMessageNumber(15,2));
			msg.setKRRES10(msgClass.getMessageNumber(15,2));
			msg.setKRRES11(msgClass.getMessageNumber(15,2));
			msg.setKRRES12(msgClass.getMessageNumber(15,2));
			msg.setKRRES13(msgClass.getMessageNumber(15,2));
			msg.setKRRES14(msgClass.getMessageNumber(15,2));
			msg.setCATIA1(msgClass.getMessageNumber(3,0));
			msg.setCATIA2(msgClass.getMessageNumber(3,0));
			msg.setCATIA3(msgClass.getMessageNumber(3,0));
			msg.setCATIA4(msgClass.getMessageNumber(3,0));
			msg.setCATIA5(msgClass.getMessageNumber(3,0));
			msg.setCATIA6(msgClass.getMessageNumber(3,0));
			msg.setCATIA7(msgClass.getMessageNumber(3,0));
			msg.setCATIA8(msgClass.getMessageNumber(3,0));
			msg.setCATIA9(msgClass.getMessageNumber(3,0));
			msg.setCATIA10(msgClass.getMessageNumber(3,0));
			msg.setCATIA11(msgClass.getMessageNumber(3,0));
			msg.setCATIA12(msgClass.getMessageNumber(3,0));
			msg.setCATIA13(msgClass.getMessageNumber(3,0));
			msg.setCATIA14(msgClass.getMessageNumber(3,0));
			msg.setKRBPFR(msgClass.getMessageNumber(6,0));
			msg.setKRBETT(msgClass.getMessageNumber(6,0));
			msg.setKRABEL(msgClass.getMessageNumber(15,2));
			msg.setKRBEL1(msgClass.getMessageNumber(15,2));
			msg.setKRBEL2(msgClass.getMessageNumber(15,2));
			msg.setKRBEL3(msgClass.getMessageNumber(15,2));
			msg.setKRSBPK(msgClass.getMessageNumber(15,2));
			msg.setKRANTK(msgClass.getMessageNumber(3,0));
			msg.setKRAVST(msgClass.getMessageNumber(3,0));
			msg.setKRAVDT(msgClass.getMessageNumber(8,0));
			msg.setKRMCDE(msgClass.getMessageString(3));
			msg.setWDYENO(msgClass.getMessageString(1));
			msg.setWDBCHR(msgClass.getMessageString(1));
			msg.setNLNPLC(msgClass.getMessageString(6));
			msg.setKRHSLD(msgClass.getMessageNumber(15,2));
			msg.setKRHSFP(msgClass.getMessageNumber(15,2));
			msg.setKRUSC1(msgClass.getMessageString(3));
			msg.setKRUSC2(msgClass.getMessageString(3));
			msg.setKRUSC3(msgClass.getMessageString(3));
			msg.setKRUSC4(msgClass.getMessageString(3));
			msg.setKRCBIL(msgClass.getMessageString(1));
			msg.setKRAVFA(msgClass.getMessageString(1));
			msg.setKRSTGR(msgClass.getMessageString(1));
			msg.setKRBEVK(msgClass.getMessageString(1));
			msg.setKREXDT(msgClass.getMessageNumber(8,0));
			msg.setKRRKID(msgClass.getMessageString(6));
			msg.setKRPGRP(msgClass.getMessageString(3));
			msg.setKRKIPN(msgClass.getMessageNumber(19,0));
			msg.setKRLOPN(msgClass.getMessageNumber(11,0));
			msg.setKRACAT(msgClass.getMessageNumber(2,0));
			msg.setKRAVIF(msgClass.getMessageNumber(1,0));
			msg.setKRNOD(msgClass.getMessageNumber(1,0));
			msg.setKRSVID(msgClass.getMessageString(6));
			msg.setKRSPLV(msgClass.getMessageNumber(3,0));
			msg.setKRKNST(msgClass.getMessageNumber(3,0));
			msg.setKRUTKD(msgClass.getMessageNumber(1,0));
			msg.setKRINTF(msgClass.getMessageNumber(15,2));
			msg.setKRPRBO(msgClass.getMessageNumber(15,2));
			msg.setKRAINB(msgClass.getMessageNumber(15,2));
			msg.setKRAINF(msgClass.getMessageNumber(15,2));
			msg.setKRACRA(msgClass.getMessageNumber(15,2));
			msg.setKRACRF(msgClass.getMessageNumber(15,2));
			msg.setKRACAA(msgClass.getMessageNumber(15,2));
			msg.setKRACAF(msgClass.getMessageNumber(15,2));
			msg.setKRACIA(msgClass.getMessageNumber(15,2));
			msg.setKRACIF(msgClass.getMessageNumber(15,2));
			msg.setKRATAX(msgClass.getMessageNumber(15,2));
			msg.setKRATXF(msgClass.getMessageNumber(15,2));
			msg.setKRKRTS(msgClass.getMessageNumber(3,0));
			msg.setKRBFR1(msgClass.getMessageNumber(3,0));
			msg.setKRBFR2(msgClass.getMessageNumber(3,0));
			msg.setKRFORB(msgClass.getMessageNumber(1,0));
			msg.setKRFBET(msgClass.getMessageNumber(15,2));
			msg.setKRBKID(msgClass.getMessageNumber(11,0));
			msg.setKRAGDT(msgClass.getMessageNumber(8,0));
			msg.setKRAGIR(msgClass.getMessageNumber(19,0));
			msg.setKRBANM(msgClass.getMessageString(40));
			msg.setKRCACC(msgClass.getMessageNumber(19,0));
			msg.setKRIACC(msgClass.getMessageNumber(19,0));
			msg.setKRREF(msgClass.getMessageString(15));
			msg.setKRFBDT(msgClass.getMessageNumber(8,0));
			msg.setKRSLAD(msgClass.getMessageNumber(8,0));
			msg.setKRLMRJ(msgClass.getMessageNumber(8,0));
			msg.setKRNKDB(msgClass.getMessageNumber(8,0));
			msg.setKRSTDT(msgClass.getMessageNumber(8,0));
			msg.setKRTBDT(msgClass.getMessageNumber(8,0));
			msg.setKRIBDT(msgClass.getMessageNumber(8,0));
			msg.setKRAUDT(msgClass.getMessageNumber(8,0));
			msg.setKRAURJ(msgClass.getMessageNumber(8,0));
			msg.setKRSKKA(msgClass.getMessageNumber(8,0));
			msg.setKRSKUT(msgClass.getMessageNumber(8,0));
			msg.setKRRBDT(msgClass.getMessageNumber(8,0));
			msg.setKRSTMP(msgClass.getMessageNumber(6,0));
			msg.setKRANTA(msgClass.getMessageNumber(5,0));
			msg.setKRLPER(msgClass.getMessageNumber(6,0));
			msg.setKRIKPR(msgClass.getMessageNumber(6,0));
			msg.setKRIBID(msgClass.getMessageString(6));
			msg.setKRSCDT(msgClass.getMessageNumber(8,0));
			msg.setKRSCOR(msgClass.getMessageNumber(5,0));
			msg.setKRAUAP(msgClass.getMessageString(1));
			msg.setKRATML(msgClass.getMessageString(1));
			msg.setKRSATP(msgClass.getMessageString(1));
			msg.setKRSTRC(msgClass.getMessageString(6));
			msg.setKRACT1(msgClass.getMessageString(3));
			msg.setKRKTTP(msgClass.getMessageString(3));
			msg.setKRMISF(msgClass.getMessageString(1));
			msg.setKRATP1(msgClass.getMessageString(1));
			msg.setKRPDAY(msgClass.getMessageNumber(2,0));
			msg.setKRDBAL(msgClass.getMessageNumber(15,2));
			msg.setKRPLIM(msgClass.getMessageNumber(11,0));
			msg.setKRTLIM(msgClass.getMessageNumber(11,0));
			msg.setKRLFLG(msgClass.getMessageString(1));
			msg.setKRTLDT(msgClass.getMessageNumber(8,0));
			msg.setKRPOFF(msgClass.getMessageString(1));
			msg.setKRNPPD(msgClass.getMessageNumber(8,0));
			msg.setKRLADT(msgClass.getMessageNumber(8,0));
			msg.setKRADAT(msgClass.getMessageNumber(8,0));
			msg.setKRBCDE(msgClass.getMessageString(3));
			msg.setKRBCDT(msgClass.getMessageNumber(8,0));
			msg.setKRNTRD(msgClass.getMessageNumber(3,0));
			msg.setKRNTRC(msgClass.getMessageNumber(3,0));
			msg.setKRTAMD(msgClass.getMessageNumber(15,2));
			msg.setKRTAMC(msgClass.getMessageNumber(15,2));
			msg.setKRSPMD(msgClass.getMessageNumber(8,0));
			msg.setKRSPMA(msgClass.getMessageNumber(15,2));
			msg.setKRSPMN(msgClass.getMessageNumber(3,0));
			msg.setKRSPAM(msgClass.getMessageNumber(15,2));
			msg.setKRTPDT(msgClass.getMessageNumber(8,0));
			msg.setKRRDAT(msgClass.getMessageNumber(8,0));
			msg.setKRFUDT(msgClass.getMessageNumber(8,0));
			msg.setKRUCIA(msgClass.getMessageNumber(15,2));
			msg.setKRDTTM(msgClass.getMessageNumber(14,0));
			msg.setKRITFL(msgClass.getMessageNumber(11,0));
			msg.setKRITFB(msgClass.getMessageNumber(15,2));
			msg.setKRITFO(msgClass.getMessageNumber(15,2));
			msg.setKRITFA(msgClass.getMessageNumber(15,2));
			msg.setKRITFP(msgClass.getMessageNumber(15,2));
			msg.setKRAMTR(msgClass.getMessageNumber(15,2));
			msg.setKRRTYP(msgClass.getMessageNumber(2,0));
			msg.setKRSTRA(msgClass.getMessageString(1));
			msg.setKRLBIL(msgClass.getMessageString(1));
			msg.setKRSEQ1(msgClass.getMessageNumber(4,0));
			msg.setKRBR(msgClass.getMessageNumber(5,0));
			msg.setCAAPID(msgClass.getMessageString(3));
			msg.setCARCDE(msgClass.getMessageString(2));
			msg.setWDBRCD(msgClass.getMessageString(1));
			msg.setWDPRDT(msgClass.getMessageNumber(8,0));
			msg.setWDAVS1(msgClass.getMessageNumber(3,0));
			msg.setWDAGRP(msgClass.getMessageString(1));
			msg.setCACSTC(msgClass.getMessageString(3));
			msg.setCAPERM(msgClass.getMessageString(1));
			msg.setCAUSER(msgClass.getMessageString(10));
			msg.setCACLID(msgClass.getMessageString(6));
			msg.setCAQUID(msgClass.getMessageString(6));
			msg.setWDACID(msgClass.getMessageString(6));
			msg.setWDNRDT(msgClass.getMessageNumber(8,0));
			msg.setWDNTRM(msgClass.getMessageNumber(4,0));
			msg.setWDDLYN(msgClass.getMessageString(1));
			msg.setWDSTMD(msgClass.getMessageNumber(8,0));
			msg.setWDBEVK(msgClass.getMessageString(1));
			msg.setWDEXDT(msgClass.getMessageNumber(8,0));
			msg.setWDSLAD(msgClass.getMessageNumber(8,0));
			msg.setBLCKDL(msgClass.getMessageString(1));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setUSLSNM(msgClass.getMessageString(40));
			msg.setKXLOCD(msgClass.getMessageString(13));
			msg.setKXAOCD(msgClass.getMessageString(13));
			msg.setKXCHAN(msgClass.getMessageString(6));
			msg.setKRSTMI(msgClass.getMessageNumber(2,0));
			msg.setKRAMIL(msgClass.getMessageString(1));
			msg.setKRBETF(msgClass.getMessageNumber(5,2));
			msg.setKRNCBF(msgClass.getMessageString(1));
			msg.setLAINAM(msgClass.getMessageNumber(15,2));
			msg.setLLTERM(msgClass.getMessageNumber(5,0));
			msg.setLLTMCR(msgClass.getMessageNumber(5,0));
			msg.setKRUPDT8(msgClass.getMessageNumber(8,0));
			msg.setKRFUDT8(msgClass.getMessageNumber(8,0));
			msg.setLLORGA1(msgClass.getMessageNumber(15,2));
			msg.setLLINNB(msgClass.getMessageNumber(5,0));
			msg.setLLTMRM(msgClass.getMessageNumber(5,0));
			msg.setLLCINT(msgClass.getMessageNumber(17,5));
			msg.setLLINEX(msgClass.getMessageNumber(5,0));
			msg.setUPPTOT(msgClass.getMessageNumber(15,2));
			msg.setIPEMNM(msgClass.getMessageString(26));
			msg.setIPEMN1(msgClass.getMessageString(26));
			msg.setKTGTDT(msgClass.getMessageNumber(6,0));
			msg.setKTLEMD(msgClass.getMessageNumber(8,0));
			msg.setKTSPKD(msgClass.getMessageNumber(1,0));
			msg.setKTCMPC(msgClass.getMessageString(20));
			msg.setKRSTFR(msgClass.getMessageString(1));
			msg.setWGOPTB(msgClass.getMessageNumber(15,2));
			msg.setKRBETS(msgClass.getMessageNumber(2,0));
			msg.setKTKRTN(msgClass.getMessageNumber(19,0));
			msg.setLLORGA(msgClass.getMessageNumber(15,2));
			msg.setKRLALA(msgClass.getMessageNumber(15,2));
			msg.setKRUSGA(msgClass.getMessageNumber(15,2));
			msg.setWOBKRT(msgClass.getMessageNumber(19,0));
			msg.setKRACCP(msgClass.getMessageNumber(2,0));
			msg.setLLLXDT(msgClass.getMessageNumber(8,0));
			msg.setWDTPSD(msgClass.getMessageNumber(15,2));
	
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");						
		
		} catch (Exception ex) {

			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		
		return msg.getMendixObject();
				
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9404";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
