// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC3607_MessageOLPInterface;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC3607 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC3607(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC3607_MessageOLPInterface msg = new TC3607_MessageOLPInterface(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setZ1Z1(msgClass.getMessageNumber(4, true));
			msg.setZ1Z2(msgClass.getMessageNumber(19, false));
			msg.setZ1Z3(msgClass.getMessageString(6));
			msg.setZ1Z4(msgClass.getMessageNumber(15, 2, false));
			msg.setZ1Z6(msgClass.getMessageNumber(15, 2, false));
			msg.setZ1Z7(msgClass.getMessageNumber(10, true));
			msg.setZ1Z10(msgClass.getMessageNumber(8, false));
			msg.setZ1Z11(msgClass.getMessageNumber(6, true));
			msg.setZ1Z12(msgClass.getMessageNumber(6, true));
			msg.setZ1Z13(msgClass.getMessageNumber(6, true));
			msg.setZ1Z18(msgClass.getMessageNumber(4, true));
			msg.setZ1Z22(msgClass.getMessageNumber(3, true));
			msg.setZ1Z32(msgClass.getMessageNumber(11, true));
			msg.setZ1Z37(msgClass.getMessageString(12));
			msg.setZ1Z38(msgClass.getMessageString(6));
			msg.setZ1Z39(msgClass.getMessageString(2));
			msg.setZ1Z42(msgClass.getMessageString(15));
			msg.setZ1Z43(msgClass.getMessageString(40));
			msg.setZ1Z48(msgClass.getMessageString(256));
			msg.setZ1Z49(msgClass.getMessageNumber(3, true));
			msg.setZ1Z51(msgClass.getMessageNumber(3, true));
			msg.setIPINIT(msgClass.getMessageString(40));
			
			msg.setResponseCode(msg.getZ1Z39().trim());
			msg.setResponseDescription(MessageClass.getDescriptionForOLP(msg.getZ1Z39().trim()));
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC3607";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
