// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9209_CUSOBKDS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC9209 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9209(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9209_CUSOBKDS msg = new TC9209_CUSOBKDS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;

			msg.setCUKIPN(msgClass.getMessageNumber(19,0));
			msg.setCUACT3(msgClass.getMessageString(3));
			msg.setCUSEQ1(msgClass.getMessageNumber(4,0));
			msg.setCUBNM3(msgClass.getMessageString(40));
			msg.setCUBAC3(msgClass.getMessageNumber(19,0));
			msg.setCUBOD3(msgClass.getMessageNumber(11,0));
			msg.setCUDTTM(msgClass.getMessageNumber(14,0));



			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9209";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
