// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5556_INPART09DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5556 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5556(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC5556_INPART09DS msg = new TC5556_INPART09DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setIPKIPN(msgClass.getMessageNumber(19,0));
			msg.setIPINIT(msgClass.getMessageString(40));
			msg.setIPLSNM(msgClass.getMessageString(40));
			msg.setIPNAME(msgClass.getMessageString(40));
			msg.setIPNAM2(msgClass.getMessageString(40));
			msg.setIPADR1(msgClass.getMessageString(40));
			msg.setIPADR2(msgClass.getMessageString(40));
			msg.setIPADR3(msgClass.getMessageString(40));
			msg.setIPADR4(msgClass.getMessageString(40));
			msg.setIPCIFN(msgClass.getMessageNumber(19,0));
			msg.setIPFDAT(msgClass.getMessageNumber(8,0));
			msg.setIPOLIC(msgClass.getMessageString(40));
			msg.setIPITP1(msgClass.getMessageString(3));
			msg.setIPCTCD(msgClass.getMessageString(3));
			msg.setIPDTTM(msgClass.getMessageNumber(14,0));
			msg.setKRSTFR(msgClass.getMessageString(1));
			msg.setWDKYCF(msgClass.getMessageString(1));
			msg.setWDSPHF(msgClass.getMessageString(1));
			msg.setKTKRTN(msgClass.getMessageNumber(19,0));
			msg.setIPSPHI(msgClass.getMessageString(4));

			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}

//		}
//		catch (Exception ex)
//		{
//			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
//		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5556";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
