// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5411_ANSOKRDS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5411 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5411(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC5411_ANSOKRDS msg = new TC5411_ANSOKRDS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setANLOPN(msgClass.getMessageNumber(11,0));
			msg.setWDKNTN(msgClass.getMessageNumber(19,0));
			msg.setWDKRTN(msgClass.getMessageNumber(19,0));
			msg.setANKIPN(msgClass.getMessageNumber(19,0));
			msg.setANUPDT(msgClass.getMessageNumber(8,0));
			msg.setANATP1(msgClass.getMessageString(1));
			msg.setANKNTN(msgClass.getMessageNumber(19,0));
			msg.setANUDFC(msgClass.getMessageNumber(19,0));
			msg.setANSVID(msgClass.getMessageString(6));
			msg.setWDSVID(msgClass.getMessageString(25));
			msg.setWDNAM1(msgClass.getMessageString(40));
			msg.setWDNAM2(msgClass.getMessageString(40));
			msg.setANOTYP(msgClass.getMessageString(6));
			msg.setANBKID(msgClass.getMessageNumber(11,0));
			msg.setWDBPNM(msgClass.getMessageString(40));
			msg.setWDBNID(msgClass.getMessageString(6));
			msg.setANANBN(msgClass.getMessageString(6));
			msg.setANICRD(msgClass.getMessageNumber(19,0));
			msg.setANAPRF(msgClass.getMessageString(15));
			msg.setANINBN(msgClass.getMessageString(6));
			msg.setANIDNR(msgClass.getMessageString(40));
			msg.setANFSM1(msgClass.getMessageString(3));
			msg.setANFSM2(msgClass.getMessageString(3));
			msg.setANF2VF(msgClass.getMessageNumber(6,0));
			msg.setWDWACD(msgClass.getMessageString(1));
			msg.setANAAY(msgClass.getMessageNumber(3,0));
			msg.setWDTPDT(msgClass.getMessageString(1));
			msg.setANTPDT(msgClass.getMessageNumber(8,0));
			msg.setANKTTP(msgClass.getMessageString(3));
			msg.setANSATP(msgClass.getMessageString(1));
			msg.setANPINR(msgClass.getMessageString(1));
			msg.setANPHTO(msgClass.getMessageString(1));
			msg.setANCLEC(msgClass.getMessageString(6));
			msg.setANAVFA(msgClass.getMessageString(1));
			msg.setANSTGR(msgClass.getMessageString(1));
			msg.setANCBIL(msgClass.getMessageString(1));
			msg.setANPGRP(msgClass.getMessageString(3));
			msg.setANSCOR(msgClass.getMessageNumber(5,0));
			msg.setANSCDN(msgClass.getMessageNumber(1,0));
			msg.setANBKRD(msgClass.getMessageNumber(11,0));
			msg.setWDCCD1(msgClass.getMessageString(3));
			msg.setANSLMT(msgClass.getMessageNumber(11,0));
			msg.setANAVST(msgClass.getMessageNumber(3,0, true));
			msg.setWDBCDE(msgClass.getMessageString(3));
			msg.setWDKNST(msgClass.getMessageNumber(3,0));
			msg.setANSTDT(msgClass.getMessageNumber(8,0));
			msg.setANRVDT(msgClass.getMessageNumber(8,0));
			msg.setANAVOR(msgClass.getMessageString(3));
			msg.setANUAPV(msgClass.getMessageString(10));
			msg.setANUENT(msgClass.getMessageString(10));
			msg.setANEMNM(msgClass.getMessageString(26));
			msg.setANEMN1(msgClass.getMessageString(26));
			msg.setANRKID(msgClass.getMessageString(6));
			msg.setANKAID(msgClass.getMessageString(3));
			msg.setANMSOK(msgClass.getMessageString(1));
			msg.setANBMAN(msgClass.getMessageString(1));
			msg.setANBVDT(msgClass.getMessageNumber(8,0));
			msg.setANAGDT(msgClass.getMessageNumber(8,0));
			msg.setANOKRD(msgClass.getMessageNumber(11,0));
			msg.setANAVIF(msgClass.getMessageNumber(1,0));
			msg.setANAGIR(msgClass.getMessageNumber(19,0));
			msg.setANBANM(msgClass.getMessageString(40));
			msg.setANREF(msgClass.getMessageString(15));
			msg.setANIDTP(msgClass.getMessageString(3));
			msg.setANBFR1(msgClass.getMessageNumber(3,0));
			msg.setANBFR2(msgClass.getMessageNumber(3,0));
			msg.setANABEL(msgClass.getMessageNumber(15,2));
			msg.setANCCDE(msgClass.getMessageString(3));
			msg.setANNOD(msgClass.getMessageNumber(1,0));
			msg.setANGRDE(msgClass.getMessageString(1));
			msg.setANUDFA(msgClass.getMessageNumber(19,0));
			msg.setANNWIC(msgClass.getMessageString(30));
			msg.setANITP2(msgClass.getMessageString(3));
			msg.setANUSC1(msgClass.getMessageString(3));
			msg.setANUSC2(msgClass.getMessageString(3));
			msg.setANUSC3(msgClass.getMessageString(3));
			msg.setANUSC4(msgClass.getMessageString(3));
			msg.setANACT1(msgClass.getMessageString(3));
			msg.setANATML(msgClass.getMessageString(1));
			msg.setANURGN(msgClass.getMessageString(3));
			msg.setANCLCB(msgClass.getMessageString(6));
			msg.setANAPRS(msgClass.getMessageString(3));
			msg.setANEBTP(msgClass.getMessageNumber(1,0));
			msg.setANLTR2(msgClass.getMessageString(1));
			msg.setANFORB(msgClass.getMessageNumber(1,0));
			msg.setANUANA(msgClass.getMessageString(10));
			msg.setANAYDT(msgClass.getMessageNumber(8,0));
			msg.setANBDAT(msgClass.getMessageNumber(8,0));
			msg.setANFSMD(msgClass.getMessageString(3));
			msg.setANACLS(msgClass.getMessageString(1));
			msg.setANKIPI(msgClass.getMessageNumber(19,0));
			msg.setANDTTM(msgClass.getMessageNumber(14,0));
			msg.setANITFL(msgClass.getMessageNumber(11,0));
			msg.setANVRFI(msgClass.getMessageString(1));
			msg.setANSCRI(msgClass.getMessageString(1));
			msg.setANDOCI(msgClass.getMessageString(1));
			msg.setANBR(msgClass.getMessageNumber(5,0, true));
			msg.setWDFLAG(msgClass.getMessageString(1));
			msg.setANLOCD(msgClass.getMessageString(13));
			msg.setANAOCD(msgClass.getMessageString(13));
			msg.setANCHAN(msgClass.getMessageString(6));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5411";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
