// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5588_GLAMTH01DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5588 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5588(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC5588_GLAMTH01DS msg = new TC5588_GLAMTH01DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
						
			msg.setAMBNTN(msgClass.getMessageNumber(9,0, true));
			msg.setAMBLON(msgClass.getMessageNumber(7,0, true));
			msg.setAMGACC(msgClass.getMessageNumber(19,0));
			msg.setAMCCDE(msgClass.getMessageString(3));
			msg.setAMTLBL(msgClass.getMessageNumber(15,2));
			msg.setAMBLSQ(msgClass.getMessageNumber(3,0));
			msg.setAMNBRI(msgClass.getMessageNumber(3,0));
			msg.setAMTLUB(msgClass.getMessageNumber(15,2));
			msg.setAMBEL(msgClass.getMessageNumber(15,2));
			msg.setAMEFDT(msgClass.getMessageNumber(8,0));
			msg.setAMAMST(msgClass.getMessageNumber(1,0));
			msg.setAMNBDT(msgClass.getMessageNumber(8,0));
			msg.setAMTTYP(msgClass.getMessageNumber(4,0));
			msg.setAMDTTM(msgClass.getMessageNumber(14,0));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5588";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
