// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5418_RNTAVGDS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5418 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5418(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC5418_RNTAVGDS msg = new TC5418_RNTAVGDS(this.getContext());
		
		try
		{
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setRABNTN(msgClass.getMessageNumber(9,0, true));
			msg.setRABLON(msgClass.getMessageNumber(7,0, true));
			msg.setRAUBNT(msgClass.getMessageNumber(9,0, true));
			msg.setRAUBLO(msgClass.getMessageNumber(7,0, true));
			msg.setRATTYP(msgClass.getMessageNumber(4,0));
			msg.setRARKID(msgClass.getMessageString(6));
			msg.setRAKNTN(msgClass.getMessageNumber(19,0));
			msg.setRATRDT(msgClass.getMessageNumber(8,0));
			msg.setRABDAT(msgClass.getMessageNumber(8,0));
			msg.setRAVLDT(msgClass.getMessageNumber(8,0));
			msg.setRAPERI(msgClass.getMessageNumber(6,0));
			msg.setRABEL(msgClass.getMessageNumber(15,2));
			msg.setRACCDE(msgClass.getMessageString(3));
			msg.setTRADES(msgClass.getMessageString(50));
			msg.setBNUSER(msgClass.getMessageString(10));
			msg.setWDDATE(msgClass.getMessageNumber(8,0));
			msg.setWDTIME(msgClass.getMessageNumber(6,0));
			msg.setRATRST(msgClass.getMessageNumber(3,0));
			msg.setRABUST(msgClass.getMessageNumber(3,0));
			msg.setRAFKDR(msgClass.getMessageString(5));
			msg.setRAKORR(msgClass.getMessageString(1));
			msg.setBNEREF(msgClass.getMessageString(15));
			msg.setRAUTBN(msgClass.getMessageNumber(9,0));
			msg.setRAUTBL(msgClass.getMessageNumber(7,0));
			msg.setRABKID(msgClass.getMessageNumber(11,0));
			msg.setRADSCC(msgClass.getMessageString(1));
			msg.setRADTTM(msgClass.getMessageNumber(14,0));
			msg.setRAPEK(msgClass.getMessageNumber(7,0));
			msg.setRAKRTN(msgClass.getMessageNumber(19,0));
			msg.setRAMEAC(msgClass.getMessageNumber(5,0));
			msg.setRANOD(msgClass.getMessageNumber(1,0));
			msg.setRABELR(msgClass.getMessageNumber(15,2));
			msg.setRACCDR(msgClass.getMessageString(3));
			msg.setRANODR(msgClass.getMessageNumber(1,0));
			msg.setRARGKR(msgClass.getMessageString(1));
			msg.setRARGAR(msgClass.getMessageString(1));
			msg.setRATSRC(msgClass.getMessageString(1));
			msg.setRASSID(msgClass.getMessageString(4));
			msg.setRAGLRR(msgClass.getMessageNumber(13,0));
			msg.setRATAXR(msgClass.getMessageNumber(15,0));
			msg.setRAREFN(msgClass.getMessageString(15));
			msg.setRABR(msgClass.getMessageNumber(5,0));
			msg.setRAERPR(msgClass.getMessageNumber(5,3));
			msg.setRABPNM(msgClass.getMessageString(40));
			msg.setRAADR1(msgClass.getMessageString(40));
			msg.setRAPNR(msgClass.getMessageNumber(9,0));
			msg.setRACITY(msgClass.getMessageString(25));
			msg.setRACKRT(msgClass.getMessageNumber(19,0));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5418";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
