// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC7580Rs;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC7580 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC7580(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC7580Rs msg = new TC7580Rs(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setBKBKID(msgClass.getMessageNumber(11,0));
			msg.setBKTMID(msgClass.getMessageString(8));
			msg.setBKMCC(msgClass.getMessageString(4));
			msg.setBKCCDN(msgClass.getMessageNumber(3,0, true));
			msg.setBKBPNM(msgClass.getMessageString(40));
			msg.setBKBPN1(msgClass.getMessageString(40));
			msg.setBKCITY(msgClass.getMessageString(25));
			msg.setBKPNR(msgClass.getMessageString(9));
			msg.setBKVIND(msgClass.getMessageString(3));
			msg.setBKVMP(msgClass.getMessageNumber(19,0));
			msg.setBKMIND(msgClass.getMessageString(3));
			msg.setBKMMP(msgClass.getMessageNumber(19,0));
			msg.setBKJIND(msgClass.getMessageString(3));
			msg.setBKJMP(msgClass.getMessageNumber(19,0));
			msg.setBKCIND(msgClass.getMessageString(3));
			msg.setBKCMP(msgClass.getMessageNumber(19,0));
			msg.setBKWIND(msgClass.getMessageString(3));
			msg.setBKWMP(msgClass.getMessageNumber(19,0));
			msg.setBKPPCT(msgClass.getMessageString(99, false));
			msg.setBKPPBP(msgClass.getMessageString(99, false));
			msg.setBKPPPI(msgClass.getMessageString(99, false));
			msg.setMAID(msgClass.getMessageString(6));
			msg.setBKPFID(msgClass.getMessageNumber(11,0));
			msg.setBKCNCD(msgClass.getMessageString(3));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC7580";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
