// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC2404_KNTLNA01DS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC2404 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC2404(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC2404_KNTLNA01DS msg = new TC2404_KNTLNA01DS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			msg.setLAKNTN(msgClass.getMessageNumber(19,0));
			msg.setLASEQN(msgClass.getMessageNumber(5,0));
			msg.setLADUDT(msgClass.getMessageNumber(8,0));
			msg.setLACBAL(msgClass.getMessageNumber(15,2));
			msg.setLAINAM(msgClass.getMessageNumber(15,2));
			msg.setLARAT1(msgClass.getMessageNumber(5,3));
			msg.setLARAT2(msgClass.getMessageNumber(5,3));
			msg.setLANDAY(msgClass.getMessageNumber(5,0));
			msg.setLAPRAM(msgClass.getMessageNumber(15,2));
			msg.setLAINA1(msgClass.getMessageNumber(15,2));
			msg.setLAINA2(msgClass.getMessageNumber(15,2));
			msg.setLAAMPD(msgClass.getMessageNumber(15,2));
			msg.setLAPRP(msgClass.getMessageNumber(15,2));
			msg.setLAINP1(msgClass.getMessageNumber(15,2));
			msg.setLAINP2(msgClass.getMessageNumber(15,2));
			msg.setLAOHPD(msgClass.getMessageNumber(15,2));
			msg.setLAOSBA(msgClass.getMessageNumber(15,2));
			msg.setLAICDE(msgClass.getMessageString(3));
			msg.setLAIVR1(msgClass.getMessageNumber(5,3));
			msg.setLAIVR2(msgClass.getMessageNumber(5,3));
			msg.setLAPPID(msgClass.getMessageString(6));
			msg.setLAPPNT(msgClass.getMessageString(10));
			msg.setLASTDT(msgClass.getMessageNumber(8,0));
			msg.setLASTFV(msgClass.getMessageNumber(5,3));
			msg.setLANCPI(msgClass.getMessageNumber(19,7));
			msg.setLAXRTA(msgClass.getMessageNumber(19,7));
			msg.setLAXMPR1(msgClass.getMessageNumber(7,5));
			msg.setLAXMPR2(msgClass.getMessageNumber(7,5));
			msg.setLAXMPR(msgClass.getMessageNumber(7,5));
			msg.setLADTTM(msgClass.getMessageNumber(14,0));
			msg.setLAINDI(msgClass.getMessageString(1));
			msg.setUPAVDT(msgClass.getMessageNumber(8,0));

			
			msg.setCode("OK");
			msg.setDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setCode("ER");
			msg.setDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC2404";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
