// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1654Rs;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC1654 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String sKey;
	private java.lang.String moreRecord;

	public GetTC1654(IContext context, java.lang.String messageString, java.lang.String sKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.sKey = sKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC1654Rs msg = new TC1654Rs(this.getContext());
				
				msg.setTRBNTN(msgClass.getMessageNumber(9, true));
				msg.setTRBLON(msgClass.getMessageNumber(7, true));
				msg.setTRTTYP(msgClass.getMessageNumber(4, false));
				msg.setTRTRDT(msgClass.getMessageNumber(8, false));
				msg.setTRBDAT(msgClass.getMessageNumber(8, false));
				msg.setTRBEL(msgClass.getMessageNumber(15, 2));
				msg.setTRTSRC(msgClass.getMessageString(1));
				msg.setTRACQN(msgClass.getMessageNumber(23, false));
				msg.setTRKNTR(msgClass.getMessageString(6));
				msg.setTRCCDS(msgClass.getMessageString(3));
				msg.setTRBELS(msgClass.getMessageNumber(15, 2));
				msg.setBKBPNM(msgClass.getMessageString(40));
				msg.setBKCITY(msgClass.getMessageString(25));
				msg.setBKCNCD(msgClass.getMessageString(3));
				msg.setBKMSTE(msgClass.getMessageString(3));
				msg.setBMMCC(msgClass.getMessageString(4));
				msg.setPPMODP(msgClass.getMessageString(6));
				msg.setTRTYP(msgClass.getMessageNumber(1, true));
				msg.setIPNAME(msgClass.getMessageString(40));
				msg.setIPNAM2(msgClass.getMessageString(40));
				msg.setTRKRTN(msgClass.getMessageNumber(19, false));
				msg.setWDFLAG(msgClass.getMessageString(1));
				msg.setWDQRPI(msgClass.getMessageString(3));
				msg.setTRCCDE(msgClass.getMessageString(3));
				
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");
				msg.setSearchKey(sKey);
				msg.setMoreRecord(moreRecord);
				
				if (!msg.getTRBNTN().toString().equals(""))
				{
					list.add(msg.getMendixObject());
				}
			}
		}
		catch (Exception ex)
		{
			TC1654Rs msg = new TC1654Rs(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC1654";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
