// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC1651_ADDRESDS;
import ktc_scs_schema.proxies.TC5433_KNTRSK01DS;
import ktcmdwscsconnector.customs.MessageClass;

public class GetTC5433 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String messageString;
	private java.lang.String searchKey;
	private java.lang.String moreRecord;

	public GetTC5433(IContext context, java.lang.String messageString, java.lang.String searchKey, java.lang.String moreRecord)
	{
		super(context);
		this.messageString = messageString;
		this.searchKey = searchKey;
		this.moreRecord = moreRecord;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
			
			while(msgClass.intIndex < msgClass.MessageString.length())
			{
				TC5433_KNTRSK01DS msg = new TC5433_KNTRSK01DS(this.getContext());
				msg.setKTKRTN(msgClass.getMessageNumber(19, 0));
				msg.setKRKNTN(msgClass.getMessageNumber(19, 0));
				msg.setKRSVID(msgClass.getMessageString(6));
				msg.setWDSVID(msgClass.getMessageString(25));
				msg.setKRAVST(msgClass.getMessageNumber(3, 0));
				msg.setKRBCDE(msgClass.getMessageString(3));
				msg.setKRKNST(msgClass.getMessageNumber(3, 0));
				msg.setIPKIPN(msgClass.getMessageNumber(19, 0));
				msg.setIPNAME(msgClass.getMessageString(40));
				msg.setIPLSNM(msgClass.getMessageString(40));
				msg.setIPFRN1(msgClass.getMessageString(20));
				msg.setIPFRN2(msgClass.getMessageString(20));
				msg.setIPFRNM(msgClass.getMessageString(20));
				msg.setIPFRN3(msgClass.getMessageString(20));
				msg.setIPFDAT(msgClass.getMessageNumber(8, 0));
				msg.setIPCTCD(msgClass.getMessageString(3));
				msg.setWDPERD2(msgClass.getMessageString(25));
				msg.setIPYEAR1(msgClass.getMessageNumber(3, 0));
				msg.setWDMMDD(msgClass.getMessageNumber(4, 0));
				msg.setKRGACC(msgClass.getMessageNumber(19, 0));
				msg.setKRLOPN(msgClass.getMessageNumber(11, 0));
				msg.setKRAGIR(msgClass.getMessageNumber(19, 0));
				msg.setIPINIT(msgClass.getMessageString(40));
				msg.setIPNAM2(msgClass.getMessageString(40));
				msg.setKRRKID(msgClass.getMessageString(6));
				msg.setKRACCP(msgClass.getMessageNumber(2, 0));
				msg.setIPCBIL(msgClass.getMessageString(1));
				msg.setIPLBIL(msgClass.getMessageString(1));
				msg.setWDSTRF(msgClass.getMessageString(1));
				msg.setSearchKey(searchKey);
				msg.setMoreRecord(moreRecord);
				msg.setResponseCode("OK");
				msg.setResponseDescription("Successfully.");

				list.add(msg.getMendixObject());
			}
		}
		catch (Exception ex)
		{
			TC1651_ADDRESDS msg = new TC1651_ADDRESDS(this.getContext());
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
			
			list.add(msg.getMendixObject());
		}
		
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5433";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
