// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9204_CUSEMPDS;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC9204 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC9204(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageClass msgClass = new MessageClass();
		TC9204_CUSEMPDS msg = new TC9204_CUSEMPDS(this.getContext());
		
		try
		{
			// Start Detail
			msgClass.intIndex = 693;
			msgClass.MessageString = this.messageString;
						
			msg.setIPKIPN(msgClass.getMessageNumber(19,0));
			msg.setIPRCT1(msgClass.getMessageString(1));
			msg.setIPSEQ1(msgClass.getMessageNumber(4,0));
			msg.setIPARBG(msgClass.getMessageString(80));
			msg.setIPINDS(msgClass.getMessageString(6));
			msg.setIPANST(msgClass.getMessageString(3));
			msg.setIPANDT(msgClass.getMessageNumber(6,0));
			msg.setIPOCCP(msgClass.getMessageString(6));
			msg.setIPAINK(msgClass.getMessageString(3));
			msg.setIPOTSC(msgClass.getMessageString(3));
			msg.setIPINCO(msgClass.getMessageNumber(15,2));
			msg.setIPOTAM(msgClass.getMessageNumber(15,2));
			msg.setIPPSN1(msgClass.getMessageString(40));
			msg.setIPEAD1(msgClass.getMessageString(40));
			msg.setIPEAD2(msgClass.getMessageString(40));
			msg.setIPEAD3(msgClass.getMessageString(40));
			msg.setIPEAD4(msgClass.getMessageString(40));
			msg.setIPEPNR(msgClass.getMessageString(9));
			msg.setIPACTY(msgClass.getMessageString(40));
			msg.setIPESTE(msgClass.getMessageString(3));
			msg.setIPECNC(msgClass.getMessageString(3));
			msg.setIPTEL(msgClass.getMessageString(20));
			msg.setIPEXT1(msgClass.getMessageNumber(7,0));
			msg.setIPTEL3(msgClass.getMessageString(20));
			msg.setIPAFAX(msgClass.getMessageString(20));
			msg.setIPEMLO(msgClass.getMessageString(100));
			msg.setIPPEMP(msgClass.getMessageString(80));
			msg.setIPPANS(msgClass.getMessageString(3));
			msg.setIPPNDT(msgClass.getMessageNumber(6,0));
			msg.setIPOCP2(msgClass.getMessageString(6));
			msg.setIPAIN2(msgClass.getMessageString(3));
			msg.setIPPSN2(msgClass.getMessageString(25));
			msg.setIPINC2(msgClass.getMessageNumber(15,2));
			msg.setIPEAD5(msgClass.getMessageString(40));
			msg.setIPEAD6(msgClass.getMessageString(40));
			msg.setIPEAD7(msgClass.getMessageString(40));
			msg.setIPEAD8(msgClass.getMessageString(40));
			msg.setIPPPN1(msgClass.getMessageString(9));
			msg.setIPPCTY(msgClass.getMessageString(40));
			msg.setIPEST1(msgClass.getMessageString(3));
			msg.setIPECN1(msgClass.getMessageString(3));
			msg.setIPPTEL(msgClass.getMessageString(20));
			msg.setIPEXT2(msgClass.getMessageNumber(7,0));
			msg.setIPPFAX(msgClass.getMessageString(20));
			msg.setIPPEML(msgClass.getMessageString(100));
			msg.setIPARB2(msgClass.getMessageString(80));
			msg.setIPAPNR(msgClass.getMessageString(9));
			msg.setIPINDP(msgClass.getMessageString(8));
			msg.setIPMINC(msgClass.getMessageNumber(15,2));
			msg.setIPALLW(msgClass.getMessageNumber(15,2));
			msg.setIPCOMM(msgClass.getMessageNumber(15,2));
			msg.setIPEMP1(msgClass.getMessageString(1));
			msg.setIPCSEQ(msgClass.getMessageNumber(4,0));
			msg.setIPPEM2(msgClass.getMessageString(80));
			msg.setIPPSEQ(msgClass.getMessageNumber(4,0));
			msg.setIPDTTM(msgClass.getMessageNumber(14,0));
			msg.setIPSTFS(msgClass.getMessageString(6));
			msg.setIPSTFL(msgClass.getMessageString(1));
			
			msg.setResponseCode("OK");
			msg.setResponseDescription("Successfully.");
		}
		catch (Exception ex)
		{
			msg.setResponseCode("ER");
			msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
		}
		
		return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC9204";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
