// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC5557_INPART10DSRs;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetTC5557 extends CustomJavaAction<IMendixObject>
{
	private java.lang.String messageString;

	public GetTC5557(IContext context, java.lang.String messageString)
	{
		super(context);
		this.messageString = messageString;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
			MessageClass msgClass =  new MessageClass();
			TC5557_INPART10DSRs msg = new TC5557_INPART10DSRs(this.getContext()); 
				
				try
				{
					// Start Detail
					msgClass.intIndex = 693;
					msgClass.MessageString = this.messageString;
					
					msg.setIPKIPN(msgClass.getMessageNumber(19, 0, false));
					msg.setIPINIT(msgClass.getMessageString(40));
					msg.setIPLSNM(msgClass.getMessageString(40));
					msg.setIPNAME(msgClass.getMessageString(40));
					msg.setIPNAM2(msgClass.getMessageString(40));
					msg.setIPADR1(msgClass.getMessageString(40));
					msg.setIPADR2(msgClass.getMessageString(40));
					msg.setIPADR3(msgClass.getMessageString(40));
					msg.setIPADR4(msgClass.getMessageString(40));
					msg.setIPKRTN(msgClass.getMessageNumber(19, 0, false));
					msg.setKRLOPN(msgClass.getMessageNumber(11, 0, false));
					msg.setKRGACC(msgClass.getMessageNumber(19, 0, false));
					msg.setKRUPDT(msgClass.getMessageNumber(8, 0, false));
					msg.setKRRKID(msgClass.getMessageString(6));
					msg.setKRSVID(msgClass.getMessageString(6));
					msg.setKRAVST(msgClass.getMessageNumber(3, 0, true));
					msg.setKRKNST(msgClass.getMessageNumber(3, 0, true));
					msg.setKRKAID(msgClass.getMessageString(3));
					msg.setKRBKRD(msgClass.getMessageNumber(11, 0, false));
					msg.setKRSLMT(msgClass.getMessageNumber(11, 0, false));
					msg.setSRRTYP(msgClass.getMessageNumber(2, 0, false));
					msg.setWDKYCF(msgClass.getMessageString(1));
					msg.setWDSPHF(msgClass.getMessageString(1));
					msg.setWDSVID(msgClass.getMessageString(25));
					msg.setWDDTTM(msgClass.getMessageNumber(14, 0, false));
					msg.setANATP1(msgClass.getMessageString(1));
					msg.setKRCCDE(msgClass.getMessageString(3));
					msg.setKRSTFR(msgClass.getMessageString(1));
					msg.setKRKNTN(msgClass.getMessageNumber(19, 0, false));
					msg.setIPCNAM(msgClass.getMessageString(40));
					msg.setKRACCP(msgClass.getMessageNumber(2, 0, false));
					msg.setIPSPHI(msgClass.getMessageString(4));
					msg.setKRBCDE(msgClass.getMessageString(3));
					msg.setLMLLVL(msgClass.getMessageNumber(3, 0, false));
					msg.setLMDESC(msgClass.getMessageString(25));
					msg.setIPCNMT(msgClass.getMessageString(40));
					msg.setBSCRLN(msgClass.getMessageNumber(10,0, false));
					msg.setBSCRFL(msgClass.getMessageString(2));
					
					msg.setResponseCode("OK");
					msg.setResponseDescription("Successfully.");
					
				} catch (Exception ex) {

					msg.setResponseCode("ER");
					msg.setResponseDescription(ex.getMessage() + " [intIndex=" + msgClass.intIndex + ", Length=" + msgClass.MessageString.length() + "]");
				}
				
				
				return msg.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTC5557";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
