// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetCommsg12110 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.COMMSG12110 mxObject;

	public SetCommsg12110(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.COMMSG12110.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		StringBuffer sb = new StringBuffer();

		try {
			sb.append(MessageClass.setMessageString(this.mxObject.getCMTI(), 4));
			sb.append(MessageClass.setMessageString(this.mxObject.getCBIT(), 48));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC2(), 19));
			sb.append(MessageClass.setMessageString(this.mxObject.getC3(), 6));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC4(), 17));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC5(), 17));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC6(), 17));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC7(), 15));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC8(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC9(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC10(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC11(), 6));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC12(), 25));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC13(), 6));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC14(), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC15(), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC16(), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC17(), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC18(), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC19(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC20(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC21(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC22(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC23(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC24(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC25(), 2));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC26(), 2));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC27(), 1));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC28(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC29(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC30(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC31(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC32(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC33(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC34(), 28));
			sb.append(MessageClass.setMessageString(this.mxObject.getC35(), 42));
			sb.append(MessageClass.setMessageString(this.mxObject.getC36(), 4));
			sb.append(MessageClass.setMessageString(this.mxObject.getC37(), 12));
			sb.append(MessageClass.setMessageString(this.mxObject.getC38(), 6));
			sb.append(MessageClass.setMessageString(this.mxObject.getC39(), 2));
			sb.append(MessageClass.setMessageString(this.mxObject.getC40(), 3));
			sb.append(MessageClass.setMessageString(this.mxObject.getC41(), 8));
			sb.append(MessageClass.setMessageString(this.mxObject.getC42(), 15));
			sb.append(MessageClass.setMessageString(this.mxObject.getC43(), 40));
			sb.append(MessageClass.setMessageString(this.mxObject.getC44(), 25));
			sb.append(MessageClass.setMessageString(this.mxObject.getC45(), 76));
			sb.append(MessageClass.setMessageString(this.mxObject.getC46(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC47(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC48(), 55));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC49(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC50(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC51(), 3));
			sb.append(MessageClass.setMessageString(this.mxObject.getC52(), 16));
			sb.append(MessageClass.setMessageString(this.mxObject.getC53(), 18));
			sb.append(MessageClass.setMessageString(this.mxObject.getC54(), 28));
			sb.append(MessageClass.setMessageString(this.mxObject.getC55(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC56(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC57(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC58(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC59(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC60(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC61(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC62(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC63(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC64(), 16));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC65(), 1));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC66(), 1));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC67(), 2));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC68(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC69(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC70(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC71(), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC72(), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC73(), 6));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC74(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC75(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC76(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC77(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC78(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC79(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC80(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC81(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC82(), 12));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC83(), 12));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC84(), 12));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC85(), 12));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC86(), 17));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC87(), 17));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC88(), 17));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC89(), 17));
			sb.append(MessageClass.setMessageString(this.mxObject.getC90(), 42));
			sb.append(MessageClass.setMessageString(this.mxObject.getC91(), 1));
			sb.append(MessageClass.setMessageString(this.mxObject.getC92(), 2));
			sb.append(MessageClass.setMessageString(this.mxObject.getC93(), 5));
			sb.append(MessageClass.setMessageString(this.mxObject.getC94(), 7));
			sb.append(MessageClass.setMessageString(this.mxObject.getC95(), 42));
			sb.append(MessageClass.setMessageString(this.mxObject.getC96(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC97(), 17));
			sb.append(MessageClass.setMessageString(this.mxObject.getC98(), 25));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC99(), 11));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC100(), 11));
			sb.append(MessageClass.setMessageString(this.mxObject.getC101(), 17));
			sb.append(MessageClass.setMessageString(this.mxObject.getC102(), 28));
			sb.append(MessageClass.setMessageString(this.mxObject.getC103(), 28));
			sb.append(MessageClass.setMessageString(this.mxObject.getC104(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC105(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC106(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC107(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC108(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC109(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC110(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC111(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC112(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC113(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC114(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC115(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC116(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC117(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC118(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC119(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC120(), 28));
			sb.append(MessageClass.setMessageString(this.mxObject.getC121(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC122(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC123(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC124(), 35));
			sb.append(MessageClass.setMessageString(this.mxObject.getC125(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC126(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC127(), 55));
			sb.append(MessageClass.setMessageString(this.mxObject.getC128(), 64));
			sb.append(MessageClass.setMessageString(this.mxObject.getC130(), 24));
			sb.append(MessageClass.setMessageString(this.mxObject.getC131(), 40));
			sb.append(MessageClass.setMessageString(this.mxObject.getC132(), 8));
			sb.append(MessageClass.setMessageString(this.mxObject.getC133(), 8));
			sb.append(MessageClass.setMessageString(this.mxObject.getC134(), 82));
			sb.append(MessageClass.setMessageString(this.mxObject.getC135(), 30));
			sb.append(MessageClass.setMessageString(this.mxObject.getC136(), 16));
			sb.append(MessageClass.setMessageString(this.mxObject.getC137(), 4));
			sb.append(MessageClass.setMessageString(this.mxObject.getC138(), 16));
			sb.append(MessageClass.setMessageString(this.mxObject.getC139(), 32));
			sb.append(MessageClass.setMessageString(this.mxObject.getC142(), 10));
			sb.append(MessageClass.setMessageString(this.mxObject.getC143(), 40));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC144(), 2));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC145(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC146(), 6));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC147(), 12));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC148(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC149(), 12));
			sb.append(MessageClass.setMessageString(this.mxObject.getC150(), 16));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getC151(), 24));
			sb.append(MessageClass.setMessageString(this.mxObject.getC152(), 16));
			sb.append(MessageClass.setMessageString(this.mxObject.getC192(), 64));
			sb.append(MessageClass.setMessageString(this.mxObject.getC257(), 16));
			sb.append(MessageClass.setMessageString(this.mxObject.getC258(), 20));
			sb.append(MessageClass.setMessageString(this.mxObject.getC259(), 20));
			sb.append(MessageClass.setMessageString(this.mxObject.getC261(), 32));

			
		} catch (Exception ex) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}

		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetCommsg12110";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
