// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5589 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC5589_GLAMTH01DS mxObject;

	public SetTC5589(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC5589_GLAMTH01DS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		StringBuilder sb = new StringBuilder();
		
		try
		{
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMBNTN(), 9));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMBLON(), 7));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMGACC(), 19));
			sb.append(MessageClass.setMessageString(this.mxObject.getAMCCDE(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMTLBL(), 15));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMBLSQ(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMNBRI(), 3));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMTLUB(), 15));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMBEL(), 15));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMEFDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMAMST(), 1));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMNBDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMTTYP (), 4));
			sb.append(MessageClass.setMessageNumber(this.mxObject.getAMDTTM (), 14));
		}
		catch (Exception ex)
		{
			throw ex;
		}

		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5589";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
