// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5022 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String groupAccountNo;
	private java.lang.String transactionDate;

	public SetTC5022(IContext context, java.lang.String groupAccountNo, java.lang.String transactionDate)
	{
		super(context);
		this.groupAccountNo = groupAccountNo;
		this.transactionDate = transactionDate;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.groupAccountNo,  19)
			+ MessageClass.setMessageNumber("0",  19)
			+ MessageClass.setMessageNumber("0",  19)
			+ MessageClass.setMessageNumber("0",  9)
			+ MessageClass.setMessageNumber("0", 7)
			+ MessageClass.setMessageNumber(this.transactionDate,  8)
			+ MessageClass.setMessageNumber("0", 15)
			+ MessageClass.setMessageNumber("0", 4)
			+ MessageClass.setMessageString("", 1)
			+ MessageClass.setMessageString("", 6)
			+ MessageClass.setMessageString("", 25)
			+ MessageClass.setMessageNumber("0", 19)
			+ MessageClass.setMessageNumber("0", 15)
			+ MessageClass.setMessageString("", 3)
			+ MessageClass.setMessageNumber("0",  2);
		}
		catch (Exception ex)
		{
			throw ex;
		}
		return strMessageApplication;	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5022";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
