// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9001 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __request;
	private ktc_scs_schema.proxies.TC9001Rq request;

	public SetTC9001(IContext context, IMendixObject request)
	{
		super(context);
		this.__request = request;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.request = __request == null ? null : ktc_scs_schema.proxies.TC9001Rq.initialize(getContext(), __request);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getWDKRTN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getWDSRVT(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPKIPN1(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getANATP1(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPKIPN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPITP1(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPOLIC(), 40));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPFDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPSEX(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getWDPKIP(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPNAME(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPNAM2(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPTITL(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPINIT(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPLSNM(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getWDTITL2(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPTELHE(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPTELAE(), 7));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPTELH(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPTELA(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPTEL3(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPEMLP(), 100));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPARBG(), 80));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPARB2(), 80));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getWDPDAT(), 2));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPINCO(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getIPOTAM(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getKRBKRD(), 11));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPRLNM(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPTELJ(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPRLSP(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPHUS(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getWIPPPTY(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getWDSTAY(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getWIPBERO(), 2));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPOCCP(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getWDEMPL(), 4));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPANST(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPINDS(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getWDSTMI(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPNATI(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPHEDU(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPCIVS(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getIPCTCD(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.request.getWDSTAF(), 1));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9001";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
