// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC9207 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC9207;
	private ktc_scs_schema.proxies.TC9207_CUSCNODS TC9207;

	public SetTC9207(IContext context, IMendixObject TC9207)
	{
		super(context);
		this.__TC9207 = TC9207;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC9207 = __TC9207 == null ? null : ktc_scs_schema.proxies.TC9207_CUSCNODS.initialize(getContext(), __TC9207);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.TC9207.getCTKIPN(), 19)
					+ MessageClass.setMessageString(this.TC9207.getCTPHNT(), 6)
					+ MessageClass.setMessageNumber(this.TC9207.getCTSEQ1(), 4)
					+ MessageClass.setMessageString(this.TC9207.getCTTELN(), 20)
					+ MessageClass.setMessageNumber(this.TC9207.getCTEFDT(), 8)
					+ MessageClass.setMessageNumber(this.TC9207.getCTEXDT(), 8)
					+ MessageClass.setMessageNumber(this.TC9207.getCTDTTM(), 14)
					+ MessageClass.setMessageString(this.TC9207.getWDDESC(), 25)
					+ MessageClass.setMessageString(this.TC9207.getWDNAME(), 32);
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9207";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
