// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5588 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5588Rq;
	private ktc_scs_schema.proxies.TC5588_GLAMTH01DS TC5588Rq;

	public SetTC5588(IContext context, IMendixObject TC5588Rq)
	{
		super(context);
		this.__TC5588Rq = TC5588Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5588Rq = __TC5588Rq == null ? null : ktc_scs_schema.proxies.TC5588_GLAMTH01DS.initialize(getContext(), __TC5588Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMBNTN(), 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMBLON(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMGACC(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5588Rq.getAMCCDE(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMTLBL(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMBLSQ(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMNBRI(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMTLUB(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMBEL(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMEFDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMAMST(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMNBDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMTTYP (), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5588Rq.getAMDTTM (), 14));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5588";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
