// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC3615 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String authorisationGroup;
	private java.lang.String cardNumber;
	private java.lang.String authorisationMode;
	private java.lang.String domesticYN;
	private java.lang.String domesticSingleTrxLimit;
	private java.lang.String domesticTotalTrxLimit1Day;
	private java.lang.String domesticTotalAmountLimit1Day;
	private java.lang.String interSingleTrxLimit;
	private java.lang.String interTotalTrxLimit1Day;
	private java.lang.String interTotalAmountLimit1Day;

	public SetTC3615(IContext context, java.lang.String authorisationGroup, java.lang.String cardNumber, java.lang.String authorisationMode, java.lang.String domesticYN, java.lang.String domesticSingleTrxLimit, java.lang.String domesticTotalTrxLimit1Day, java.lang.String domesticTotalAmountLimit1Day, java.lang.String interSingleTrxLimit, java.lang.String interTotalTrxLimit1Day, java.lang.String interTotalAmountLimit1Day)
	{
		super(context);
		this.authorisationGroup = authorisationGroup;
		this.cardNumber = cardNumber;
		this.authorisationMode = authorisationMode;
		this.domesticYN = domesticYN;
		this.domesticSingleTrxLimit = domesticSingleTrxLimit;
		this.domesticTotalTrxLimit1Day = domesticTotalTrxLimit1Day;
		this.domesticTotalAmountLimit1Day = domesticTotalAmountLimit1Day;
		this.interSingleTrxLimit = interSingleTrxLimit;
		this.interTotalTrxLimit1Day = interTotalTrxLimit1Day;
		this.interTotalAmountLimit1Day = interTotalAmountLimit1Day;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageString(this.authorisationGroup, 3));				//	AAAUTG
			strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));					//	AAKRTN
			strMessageDetail.append(MessageClass.setMessageString(this.authorisationMode, 2));				//	AAAMOD
			strMessageDetail.append(MessageClass.setMessageString(this.domesticYN, 1));						//	AAMODI
			strMessageDetail.append(MessageClass.setMessageNumber(this.domesticSingleTrxLimit, 11));		//	AADAMA
			strMessageDetail.append(MessageClass.setMessageNumber(this.domesticTotalTrxLimit1Day, 3));		//	AADNOD
			strMessageDetail.append(MessageClass.setMessageNumber(this.domesticTotalAmountLimit1Day, 11));	//	AADAMD
			strMessageDetail.append(MessageClass.setMessageNumber(this.interSingleTrxLimit, 11));			//	AAIAMA
			strMessageDetail.append(MessageClass.setMessageNumber(this.interTotalTrxLimit1Day, 3));			//	AAINOD
			strMessageDetail.append(MessageClass.setMessageNumber(this.interTotalAmountLimit1Day, 11));		//	AAIAMD
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC3615";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
