// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5429 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC5429_KNTRLL03DS mxObject;

	public SetTC5429(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC5429_KNTRLL03DS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		String strMessageApplication = "";
		try
		{
			strMessageApplication = MessageClass.setMessageString(this.mxObject.getKNRREF(), 12)
				     + MessageClass.setMessageNumber(this.mxObject.getKNKRTN(), 19)
				     + MessageClass.setMessageNumber(this.mxObject.getKNSTAN(), 6)
				     + MessageClass.setMessageNumber(this.mxObject.getKNAUTP(), 1)
				     + MessageClass.setMessageNumber(this.mxObject.getKNDTTM(), 14)
				     + MessageClass.setMessageString(this.mxObject.getWDAUTP(), 25)
				     + MessageClass.setMessageNumber(this.mxObject.getKNKNTN(), 19)
				     + MessageClass.setMessageString(this.mxObject.getWDDESC(), 25)
				     + MessageClass.setMessageNumber(this.mxObject.getKNBELS(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKNBELB(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKNBELI(), 15)
				     + MessageClass.setMessageString(this.mxObject.getKNCCDS(), 3)
				     + MessageClass.setMessageString(this.mxObject.getKNCCDB(), 3)
				     + MessageClass.setMessageString(this.mxObject.getADCCDE(), 3)
				     + MessageClass.setMessageNumber(this.mxObject.getKNBXAM(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getWDAPDT(), 8)
				     + MessageClass.setMessageNumber(this.mxObject.getWDAPTM(), 6)
				     + MessageClass.setMessageNumber(this.mxObject.getWDSDT1(), 8)
				     + MessageClass.setMessageNumber(this.mxObject.getWDSTM1(), 6)
				     + MessageClass.setMessageNumber(this.mxObject.getWDRVDT(), 8)
				     + MessageClass.setMessageNumber(this.mxObject.getWDRVTM(), 6)
				     + MessageClass.setMessageNumber(this.mxObject.getKNCNDT(), 8)
				     + MessageClass.setMessageString(this.mxObject.getWDARJC(), 4)
				     + MessageClass.setMessageString(this.mxObject.getWDRJDS(), 25)
				     + MessageClass.setMessageString(this.mxObject.getKNIDRF(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKNFID(), 11)
				     + MessageClass.setMessageString(this.mxObject.getKNMCC(), 4)
				     + MessageClass.setMessageNumber(this.mxObject.getKNBKID(), 11)
				     + MessageClass.setMessageString(this.mxObject.getBKBPNM(), 40)
				     + MessageClass.setMessageNumber(this.mxObject.getKNMEAC(), 5)
				     + MessageClass.setMessageString(this.mxObject.getKNCATI(), 8)
				     + MessageClass.setMessageString(this.mxObject.getKNCANM(), 40)
				     + MessageClass.setMessageString(this.mxObject.getKNALIN(), 1)
				     + MessageClass.setMessageString(this.mxObject.getWDALRS(), 12)
				     + MessageClass.setMessageNumber(this.mxObject.getKNRVWD(), 8)
				     + MessageClass.setMessageString(this.mxObject.getKNDOMI(), 1)
				     + MessageClass.setMessageString(this.mxObject.getWDDOMI(), 1)
				     + MessageClass.setMessageString(this.mxObject.getKNUSER(), 10)
				     + MessageClass.setMessageNumber(this.mxObject.getKNGTDT(), 6)
				     + MessageClass.setMessageString(this.mxObject.getKNRKID(), 6)
				     + MessageClass.setMessageString(this.mxObject.getKNKNTR(), 6)
				     + MessageClass.setMessageNumber(this.mxObject.getKNASTS(), 3)
				     + MessageClass.setMessageString(this.mxObject.getKNASRC(), 1)
				     + MessageClass.setMessageString(this.mxObject.getKNSAFW(), 1)
				     + MessageClass.setMessageString(this.mxObject.getWDSAFW(), 1)
				     + MessageClass.setMessageString(this.mxObject.getKNAVRC(), 3)
				     + MessageClass.setMessageString(this.mxObject.getKNSOVR(), 1)
				     + MessageClass.setMessageString(this.mxObject.getWDSOVR(), 1)
				     + MessageClass.setMessageString(this.mxObject.getKNAUTG(), 3)
				     + MessageClass.setMessageString(this.mxObject.getKNTCGR(), 3)
				     + MessageClass.setMessageString(this.mxObject.getKNRESP(), 2)
				     + MessageClass.setMessageString(this.mxObject.getKNVLCD(), 4)
				     + MessageClass.setMessageString(this.mxObject.getWDBALI(), 1)
				     + MessageClass.setMessageString(this.mxObject.getKNPOSM(), 2)
				     + MessageClass.setMessageString(this.mxObject.getKNPOSD(), 2)
				     + MessageClass.setMessageNumber(this.mxObject.getKEAVST(), 3)
				     + MessageClass.setMessageString(this.mxObject.getKEBCDE(), 3)
				     + MessageClass.setMessageNumber(this.mxObject.getKEKNST(), 3)
				     + MessageClass.setMessageNumber(this.mxObject.getKESPKD(), 1)
				     + MessageClass.setMessageString(this.mxObject.getKESPRK(), 2)
				     + MessageClass.setMessageNumber(this.mxObject.getKEBKRD(), 11)
				     + MessageClass.setMessageNumber(this.mxObject.getKECSLD(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKEPRBO(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKESUBA(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKEGRPA(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKESGAV(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKETSLD(), 15)
				     + MessageClass.setMessageString(this.mxObject.getKERMK1(), 25)
				     + MessageClass.setMessageString(this.mxObject.getKERMK2(), 25)
				     + MessageClass.setMessageString(this.mxObject.getKERMK3(), 25)
				     + MessageClass.setMessageString(this.mxObject.getKERMK4(), 25)
				     + MessageClass.setMessageString(this.mxObject.getKERMK5(), 25)
				     + MessageClass.setMessageString(this.mxObject.getKERMK6(), 25)
				     + MessageClass.setMessageString(this.mxObject.getKEAPBY(), 15)
				     + MessageClass.setMessageNumber(this.mxObject.getKEUCIA(), 15)
				     + MessageClass.setMessageString(this.mxObject.getKNPRCD(), 6)
				     + MessageClass.setMessageNumber(this.mxObject.getKNSDTM(), 14)
				     + MessageClass.setMessageNumber(this.mxObject.getKNRSDT(), 14)
				     + MessageClass.setMessageString(this.mxObject.getKNALRS(), 40)
				     + MessageClass.setMessageNumber(this.mxObject.getTPGRTP(), 2)
				     + MessageClass.setMessageString(this.mxObject.getWDECI(), 3)
				     + MessageClass.setMessageString(this.mxObject.getAJCVCD(), 1)
				     + MessageClass.setMessageString(this.mxObject.getKNFBIN(), 1)
				     + MessageClass.setMessageString(this.mxObject.getSRNETW(), 3)
				     + MessageClass.setMessageString(this.mxObject.getKNPOSA(), 19)
				     + MessageClass.setMessageNumber(this.mxObject.getTKTPAN(), 19)
				     + MessageClass.setMessageString(this.mxObject.getTKTKTP(), 2)
				     + MessageClass.setMessageString(this.mxObject.getTKMTYP(), 2)
				     + MessageClass.setMessageNumber(this.mxObject.getKNMPAN(), 19)
					 + MessageClass.setMessageString(this.mxObject.getKNQRIN(), 1)
				     + MessageClass.setMessageString(this.mxObject.getWDDEVC(), 5);
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageApplication.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5429";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
