// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC9215 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC9215;
	private ktc_scs_schema.proxies.TC9215_ADDRES01DS TC9215;

	public SetTC9215(IContext context, IMendixObject TC9215)
	{
		super(context);
		this.__TC9215 = TC9215;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC9215 = __TC9215 == null ? null : ktc_scs_schema.proxies.TC9215_ADDRES01DS.initialize(getContext(), __TC9215);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.TC9215.getAXKIPN(), 19)
					+ MessageClass.setMessageString(this.TC9215.getAXADTP(), 1)
					+ MessageClass.setMessageNumber(this.TC9215.getAXSEQ1(), 4)
					+ MessageClass.setMessageString(this.TC9215.getAXADR1(), 40)
					+ MessageClass.setMessageString(this.TC9215.getAXADR2(), 40)
					+ MessageClass.setMessageString(this.TC9215.getAXADR3(), 40)
					+ MessageClass.setMessageString(this.TC9215.getAXADR4(), 40)
					+ MessageClass.setMessageString(this.TC9215.getAXPNR(), 9)
					+ MessageClass.setMessageString(this.TC9215.getAXCITY(), 40)
					+ MessageClass.setMessageString(this.TC9215.getAXLSTE(), 3)
					+ MessageClass.setMessageString(this.TC9215.getAXCNCD(), 3)
					+ MessageClass.setMessageString(this.TC9215.getAXADRF(), 1)
					+ MessageClass.setMessageString(this.TC9215.getWDCBIL(), 1)
					+ MessageClass.setMessageNumber(this.TC9215.getAXDTTM(), 14);
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9215";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
