// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9404 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC9404Rq;
	private ktc_scs_schema.proxies.TC9404_KNTRSK32DS TC9404Rq;

	public SetTC9404(IContext context, IMendixObject TC9404Rq)
	{
		super(context);
		this.__TC9404Rq = TC9404Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC9404Rq = __TC9404Rq == null ? null : ktc_scs_schema.proxies.TC9404_KNTRSK32DS.initialize(getContext(), __TC9404Rq);

		// BEGIN USER CODE
		StringBuffer sb = new StringBuffer();
		
		try {
			
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRKNTN(), 19));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRUPDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBKRD(), 11));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSLMT(), 11));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRLMTF(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKROTBM(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRKAID(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRCCDE(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSLDO(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRUSLD(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRLBET(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDTOTD(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDCURD(), 15));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRFSMD(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRFSM1(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRFSM2(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRF2VF(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAAY(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCAALVL(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRSTD(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRLVL(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES1(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES2(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES3(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES4(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES5(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES6(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES7(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES8(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES9(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES10(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES11(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES12(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES13(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRES14(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA1(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA2(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA3(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA4(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA5(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA6(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA7(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA8(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA9(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA10(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA11(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA12(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA13(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getCATIA14(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBPFR(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBETT(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRABEL(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBEL1(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBEL2(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBEL3(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSBPK(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRANTK(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAVST(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAVDT(), 8));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRMCDE(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getWDYENO(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getWDBCHR(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getNLNPLC(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRHSLD(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRHSFP(), 15));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRUSC1(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRUSC2(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRUSC3(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRUSC4(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRCBIL(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRAVFA(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRSTGR(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRBEVK(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKREXDT(), 8));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRRKID(), 6));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRPGRP(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRKIPN(), 19));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRLOPN(), 11));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACAT(), 2));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAVIF(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRNOD(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRSVID(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSPLV(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRKNST(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRUTKD(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRINTF(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRPRBO(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAINB(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAINF(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACRA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACRF(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACAA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACAF(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACIA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACIF(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRATAX(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRATXF(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRKRTS(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBFR1(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBFR2(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRFORB(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRFBET(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBKID(), 11));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAGDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAGIR(), 19));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRBANM(), 40));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRCACC(), 19));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRIACC(), 19));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRREF(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRFBDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSLAD(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRLMRJ(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRNKDB(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSTDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRTBDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRIBDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAUDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAURJ(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSKKA(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSKUT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRBDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSTMP(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRANTA(), 5));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRLPER(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRIKPR(), 6));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRIBID(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSCDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSCOR(), 5));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRAUAP(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRATML(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRSATP(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRSTRC(), 6));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRACT1(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRKTTP(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRMISF(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRATP1(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRPDAY(), 2));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRDBAL(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRPLIM(), 11));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRTLIM(), 11));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRLFLG(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRTLDT(), 8));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRPOFF(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRNPPD(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRLADT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRADAT(), 8));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRBCDE(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBCDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRNTRD(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRNTRC(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRTAMD(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRTAMC(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSPMD(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSPMA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSPMN(), 3));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSPAM(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRTPDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRDAT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRFUDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRUCIA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRDTTM(), 14));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRITFL(), 11));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRITFB(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRITFO(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRITFA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRITFP(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRAMTR(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRRTYP(), 2));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRSTRA(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRLBIL(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSEQ1(), 4));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBR(), 5));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getCAAPID(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getCARCDE(), 2));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getWDBRCD(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDPRDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDAVS1(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getWDAGRP(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getCACSTC(), 3));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getCAPERM(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getCAUSER(), 10));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getCACLID(), 6));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getCAQUID(), 6));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getWDACID(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDNRDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDNTRM(), 4));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getWDDLYN(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDSTMD(), 8));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getWDBEVK(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDEXDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDSLAD(), 8));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getBLCKDL(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getIPNAME(), 40));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getUSLSNM(), 40));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKXLOCD(), 13));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKXAOCD(), 13));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKXCHAN(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRSTMI(), 2));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRAMIL(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBETF(), 5));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRNCBF(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLAINAM(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLTERM(), 5));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLTMCR(), 5));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRUPDT8(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRFUDT8(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLORGA1(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLINNB(), 5));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLTMRM(), 5));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLCINT(), 17));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLINEX(), 5));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getUPPTOT(), 15));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getIPEMNM(), 26));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getIPEMN1(), 26));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKTGTDT(), 6));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKTLEMD(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKTSPKD(), 1));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKTCMPC(), 20));
			sb.append(MessageClass.setMessageString(this.TC9404Rq.getKRSTFR(), 1));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWGOPTB(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRBETS(), 2));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKTKRTN(), 19));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLORGA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRLALA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRUSGA(), 15));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWOBKRT(), 19));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getKRACCP(), 2));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getLLLXDT(), 8));
			sb.append(MessageClass.setMessageNumber(this.TC9404Rq.getWDTPSD(), 15));
			
		} catch (Exception ex) {

			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9404";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
