// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5413 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __SPKORTDS;
	private ktc_scs_schema.proxies.TC5413_SPKORTDS SPKORTDS;

	public SetTC5413(IContext context, IMendixObject SPKORTDS)
	{
		super(context);
		this.__SPKORTDS = SPKORTDS;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.SPKORTDS = __SPKORTDS == null ? null : ktc_scs_schema.proxies.TC5413_SPKORTDS.initialize(getContext(), __SPKORTDS);

		// BEGIN USER CODE
		String strMessageApplication = "";
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.SPKORTDS.getSKKRTN(), 19)
					+ MessageClass.setMessageNumber(this.SPKORTDS.getSKSFDN(), 8)
					+ MessageClass.setMessageString(this.SPKORTDS.getSKRREF(), 12);
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageApplication.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5413";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
