// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5919 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5919;
	private ktc_scs_schema.proxies.TC5919_KNTUT201DS TC5919;

	public SetTC5919(IContext context, IMendixObject TC5919)
	{
		super(context);
		this.__TC5919 = TC5919;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5919 = __TC5919 == null ? null : ktc_scs_schema.proxies.TC5919_KNTUT201DS.initialize(getContext(), __TC5919);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.TC5919.getKUKNTN(), 19)
					+ MessageClass.setMessageNumber(this.TC5919.getKUPERI(),  5)
					+ MessageClass.setMessageNumber(this.TC5919.getKUAINB(), 15)
					+ MessageClass.setMessageNumber(this.TC5919.getKUPTHP(), 15)
					+ MessageClass.setMessageNumber(this.TC5919.getKUPTHI(), 15)
					+ MessageClass.setMessageNumber(this.TC5919.getKUPTHU(), 15)
					+ MessageClass.setMessageNumber(this.TC5919.getKUPTHC(), 15)
					+ MessageClass.setMessageNumber(this.TC5919.getKUPTHV(), 15)
					+ MessageClass.setMessageNumber(this.TC5919.getKUINNB(),  5)
					+ MessageClass.setMessageNumber(this.TC5919.getKUAAMT(), 15)
					+ MessageClass.setMessageString(this.TC5919.getKUCANM(), 40)
					+ MessageClass.setMessageString(this.TC5919.getKUDTTM(), 14)
					+ MessageClass.setMessageString(this.TC5919.getKUDESC(), 25)
					+ MessageClass.setMessageNumber(this.TC5919.getKUSEQN(),  5);
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5919";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
