// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5304 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC5304_AUTPGRDS mxObject;

	public SetTC5304(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC5304_AUTPGRDS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		String strMessageApplication = "";
		try
		{
			strMessageApplication = MessageClass.setMessageString(this.mxObject.getSCRKID(), 6)
					+ MessageClass.setMessageString(this.mxObject.getSCPGRP(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getSCDTTM(), 14)
					+ MessageClass.setMessageNumber(this.mxObject.getSCPDAY(), 2)
					+ MessageClass.setMessageString(this.mxObject.getWDFLAG(), 1);
		}
		catch (Exception ex)
		{
			throw ex;
		}
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5304";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
