// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC3401 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC3401Rq;
	private ktc_scs_schema.proxies.TC3401_KNTEXS05DS TC3401Rq;

	public SetTC3401(IContext context, IMendixObject TC3401Rq)
	{
		super(context);
		this.__TC3401Rq = TC3401Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC3401Rq = __TC3401Rq == null ? null : ktc_scs_schema.proxies.TC3401_KNTEXS05DS.initialize(getContext(), __TC3401Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLKNTN(), 19));	
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLTERM(), 5));
			strMessageDetail.append(MessageClass.setMessageString(this.TC3401Rq.getLLTMCD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLTMCR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLLXDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLINPD(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLINEX(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLINNB(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLAINAM(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLADUDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC3401Rq.getLLDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC3401Rq.getLXYON(), 1));
			
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC3401";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
