// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5031 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String accountNumber;

	public SetTC5031(IContext context, java.lang.String accountNumber)
	{
		super(context);
		this.accountNumber = accountNumber;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder sb = new StringBuilder();
		
		try {
			
			sb.append(MessageClass.setMessageNumber(this.accountNumber, 19));	//	KUKNTN
			sb.append(MessageClass.setMessageNumber("0", 5));
			sb.append(MessageClass.setMessageNumber("0", 1));
			sb.append(MessageClass.setMessageNumber("0", 9));
			sb.append(MessageClass.setMessageNumber("0", 7));
			sb.append(MessageClass.setMessageNumber("0", 8));
			sb.append(MessageClass.setMessageNumber("0", 8));
			sb.append(MessageClass.setMessageString("0", 40));
			sb.append(MessageClass.setMessageNumber("0", 4));
			sb.append(MessageClass.setMessageString("0", 1));
			sb.append(MessageClass.setMessageNumber("0", 15));
			sb.append(MessageClass.setMessageNumber("0", 1));
			sb.append(MessageClass.setMessageNumber("0", 19));
		}
		catch (Exception ex) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5031";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
