// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5412 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __request;
	private ktc_scs_schema.proxies.TC5412Rq request;

	public SetTC5412(IContext context, IMendixObject request)
	{
		super(context);
		this.__request = request;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.request = __request == null ? null : ktc_scs_schema.proxies.TC5412Rq.initialize(getContext(), __request);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.request.getKTKRTN(), 19));	//	KTKRTN
		}
		catch (Exception ex) {

			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5412";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
