// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5208 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5208Rq;
	private ktc_scs_schema.proxies.TC5208_CUSSPODS TC5208Rq;

	public SetTC5208(IContext context, IMendixObject TC5208Rq)
	{
		super(context);
		this.__TC5208Rq = TC5208Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5208Rq = __TC5208Rq == null ? null : ktc_scs_schema.proxies.TC5208_CUSSPODS.initialize(getContext(), __TC5208Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5208Rq.getIPKIPN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRLSP(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5208Rq.getIPSEQ1(), 4));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRLNM(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPOLI3(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPITP3(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRAD1(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRAD2(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRAD3(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRAD4(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRPNR(), 9));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRCTY(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRSTE(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRCNC(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPEMLP(), 100));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPNWI4(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPTELJ(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPTELK(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPTEL3(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPOCC1(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5208Rq.getIPANVE(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPOCC2(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5208Rq.getIPODT2(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPSPNM(), 32));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPRCTP(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPITP4(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPNATI(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5208Rq.getIPTELJE(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5208Rq.getIPTELKE(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5208Rq.getIPDTTM(), 14));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5208";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
