// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5210 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String customerNumber;
	private java.lang.String cardNumber;

	public SetTC5210(IContext context, java.lang.String customerNumber, java.lang.String cardNumber)
	{
		super(context);
		this.customerNumber = customerNumber;
		this.cardNumber = cardNumber;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{

			strMessageDetail.append(MessageClass.setMessageNumber(this.customerNumber, 19));		//	IPKIPN
			strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));			//	KTKRTN
			strMessageDetail.append(MessageClass.setMessageString("", 40));							//	IPMONM
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));							//	IPFDAT
			strMessageDetail.append(MessageClass.setMessageString("", 15));							//	IPTELA
			strMessageDetail.append(MessageClass.setMessageString("", 15));							//	IPTELH
			strMessageDetail.append(MessageClass.setMessageString("", 15));							//	IPTEL3
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						//	KRBKRD
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));						//	CHLPAY
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));							//	CHIBDT
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));						//	CHLSTA
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));							//	CHLSTR
			strMessageDetail.append(MessageClass.setMessageString("", 40));							//	IPADR1
			strMessageDetail.append(MessageClass.setMessageString("", 40));							//	IPADR2
			strMessageDetail.append(MessageClass.setMessageString("", 40));							//	IPADR3
			strMessageDetail.append(MessageClass.setMessageString("", 40));							//	IPADR4
			strMessageDetail.append(MessageClass.setMessageString("", 9));							//	IPPNR
			strMessageDetail.append(MessageClass.setMessageString("", 40));							//	IPCITY
			strMessageDetail.append(MessageClass.setMessageString("", 3));							//	IPLSTE
			strMessageDetail.append(MessageClass.setMessageString("", 3));							//	IPCNCD
			strMessageDetail.append(MessageClass.setMessageNumber("0", 19));						//	KRKNTN
			strMessageDetail.append(MessageClass.setMessageString("", 40));							//	IPOLIC
			strMessageDetail.append(MessageClass.setMessageString("", 100));						//	IPEMLP
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						//	KRPLIM
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						//	KRSLMT
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						//	KRTLIM
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));							//	KRTLDT


		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5210";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
