// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC3613 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String cardNumber;
	private java.lang.String deactivationFlag;
	private java.lang.String activationChannel;
	private java.lang.String expiryDate;
	private java.lang.String IDNumber;
	private java.lang.String mobileNumber;

	public SetTC3613(IContext context, java.lang.String cardNumber, java.lang.String deactivationFlag, java.lang.String activationChannel, java.lang.String expiryDate, java.lang.String IDNumber, java.lang.String mobileNumber)
	{
		super(context);
		this.cardNumber = cardNumber;
		this.deactivationFlag = deactivationFlag;
		this.activationChannel = activationChannel;
		this.expiryDate = expiryDate;
		this.IDNumber = IDNumber;
		this.mobileNumber = mobileNumber;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));			//	KTKRTN
			strMessageDetail.append(MessageClass.setMessageString(this.deactivationFlag, 1));		//	KTDEAC
			strMessageDetail.append(MessageClass.setMessageString(this.activationChannel, 2));		//	KTDECH
			strMessageDetail.append(MessageClass.setMessageString("", 3));							//	KRBCDE
			strMessageDetail.append(MessageClass.setMessageNumber(this.expiryDate, 6));				//	KTGTDT
			strMessageDetail.append(MessageClass.setMessageString(this.IDNumber, 4));				//	IPOLIC
			strMessageDetail.append(MessageClass.setMessageString(this.mobileNumber, 20));			//	iPTELH
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC3613";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
