// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5089 extends CustomJavaAction<java.lang.String>
{
	public SetTC5089(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber("0", 9));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 7));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 9));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 7));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 4));
			strMessageDetail.append(MessageClass.setMessageString("", 6));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 19));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageString("", 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
			strMessageDetail.append(MessageClass.setMessageString("", 5));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 14));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageString("", 15));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5089";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
