// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC2405 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC2405;
	private ktc_scs_schema.proxies.TC2405_KNTPPD01DS TC2405;

	public SetTC2405(IContext context, IMendixObject TC2405)
	{
		super(context);
		this.__TC2405 = TC2405;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC2405 = __TC2405 == null ? null : ktc_scs_schema.proxies.TC2405_KNTPPD01DS.initialize(getContext(), __TC2405);

		// BEGIN USER CODE
		String strMessageApplication = "";

		try {
			strMessageApplication = MessageClass.setMessageNumber(this.TC2405.getLPSEQN(), 5, 0)
					+ MessageClass.setMessageNumber(this.TC2405.getLPTERM(), 5, 0)
					+ MessageClass.setMessageString(this.TC2405.getLPICDE(), 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPRAT1(), 5, 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPRAT2(), 5, 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPIVR1(), 5, 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPSTFV(), 5, 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPEFIR(), 5, 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPEFFR(), 5, 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPEFTR(), 5, 3)
					+ MessageClass.setMessageNumber(this.TC2405.getLPGACC(), 19, 0)
					+ MessageClass.setMessageNumber(this.TC2405.getLPKNTN(), 19, 0)
					+ MessageClass.setMessageString(this.TC2405.getLPPPID(), 6)
					+ MessageClass.setMessageString(this.TC2405.getLPPPNT(), 10)
					+ MessageClass.setMessageString(this.TC2405.getLPPPNM(), 1)
					+ MessageClass.setMessageNumber(this.TC2405.getLPSTDT(), 8, 0)
					+ MessageClass.setMessageNumber(this.TC2405.getLPENDT(), 8, 0)
					+ MessageClass.setMessageNumber(this.TC2405.getLPTMPR(), 5, 0)
					+ MessageClass.setMessageNumber(this.TC2405.getLPDTTM(), 14, 0)
					+ MessageClass.setMessageNumber(this.TC2405.getLPDISR(), 5, 2);
			
		} catch (Exception ex) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}

		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC2405";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
