// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5030 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5030Rq;
	private ktc_scs_schema.proxies.TC5030_DISPHS01DS TC5030Rq;

	public SetTC5030(IContext context, IMendixObject TC5030Rq)
	{
		super(context);
		this.__TC5030Rq = TC5030Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5030Rq = __TC5030Rq == null ? null : ktc_scs_schema.proxies.TC5030_DISPHS01DS.initialize(getContext(), __TC5030Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5030Rq.getDPKNTN(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5030Rq.getDPBNTN(), 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5030Rq.getDPBLON(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5030Rq.getDPDTTM(), 14));		
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5030";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
