// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5186 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5186Rq;
	private ktc_scs_schema.proxies.TC5186_FINFSLDS TC5186Rq;

	public SetTC5186(IContext context, IMendixObject TC5186Rq)
	{
		super(context);
		this.__TC5186Rq = TC5186Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5186Rq = __TC5186Rq == null ? null : ktc_scs_schema.proxies.TC5186_FINFSLDS.initialize(getContext(), __TC5186Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5186Rq.getFSPGMN(), 10));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5186Rq.getFSFILN(), 10));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5186";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
