// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC1211 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC1211;
	private ktc_scs_schema.proxies.TC1211_LMTCTL01DS TC1211;

	public SetTC1211(IContext context, IMendixObject TC1211)
	{
		super(context);
		this.__TC1211 = TC1211;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC1211 = __TC1211 == null ? null : ktc_scs_schema.proxies.TC1211_LMTCTL01DS.initialize(getContext(), __TC1211);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.TC1211.getLMGNUM(), 19)
					+ MessageClass.setMessageNumber(this.TC1211.getLMLNUM(), 19)
					+ MessageClass.setMessageNumber(this.TC1211.getLMLLVL(), 3)
					+ MessageClass.setMessageNumber(this.TC1211.getLMGLMN(), 19)
					+ MessageClass.setMessageNumber(this.TC1211.getLMKIPN(), 19)
					+ MessageClass.setMessageString(this.TC1211.getIPLSNM(), 40)
					+ MessageClass.setMessageString(this.TC1211.getIPINIT(), 40)
					+ MessageClass.setMessageString(this.TC1211.getIPNAME(), 40)
					+ MessageClass.setMessageNumber(this.TC1211.getKTKRTN(), 19)
					+ MessageClass.setMessageString(this.TC1211.getKTRKID(), 6)
					+ MessageClass.setMessageNumber(this.TC1211.getKTKIPN(), 19)
					+ MessageClass.setMessageNumber(this.TC1211.getLMBKRD(), 11)
					+ MessageClass.setMessageNumber(this.TC1211.getWDUTIL(), 15)
					+ MessageClass.setMessageNumber(this.TC1211.getWDAVAI(), 15)
					+ MessageClass.setMessageNumber(this.TC1211.getLMGBAC(), 19)
					+ MessageClass.setMessageString(this.TC1211.getWDTYPE(), 1)
					+ MessageClass.setMessageNumber(this.TC1211.getLMDTTM(), 14)
					+ MessageClass.setMessageNumber(this.TC1211.getLMBKRT(), 19)
					+ MessageClass.setMessageNumber(this.TC1211.getWDNOLM(), 5)
					+ MessageClass.setMessageNumber(this.TC1211.getWDNOAC(), 5);
		}
		catch (Exception ex)
		{
			throw ex;
		}
		return strMessageApplication;	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC1211";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
