// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC9409 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC9409;
	private ktc_scs_schema.proxies.TC9409_GIRINSDS TC9409;

	public SetTC9409(IContext context, IMendixObject TC9409)
	{
		super(context);
		this.__TC9409 = TC9409;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC9409 = __TC9409 == null ? null : ktc_scs_schema.proxies.TC9409_GIRINSDS.initialize(getContext(), __TC9409);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.TC9409.getGIKNTN(), 19)
					+ MessageClass.setMessageNumber(this.TC9409.getKRUPDT(), 8)
					+ MessageClass.setMessageNumber(this.TC9409.getGIAVST(), 3)
					+ MessageClass.setMessageString(this.TC9409.getKRPGRP(), 3)
					+ MessageClass.setMessageString(this.TC9409.getGIINST(), 1)
					+ MessageClass.setMessageNumber(this.TC9409.getGIFIXP(), 15)
					+ MessageClass.setMessageNumber(this.TC9409.getKRSKUT(), 8)
					+ MessageClass.setMessageNumber(this.TC9409.getKRNPPD(), 8)
					+ MessageClass.setMessageNumber(this.TC9409.getGISTDT(), 8)
					+ MessageClass.setMessageNumber(this.TC9409.getGIERDT(), 8)
					+ MessageClass.setMessageNumber(this.TC9409.getGIEFDT(), 8)
					+ MessageClass.setMessageString(this.TC9409.getGITMOD(), 3)
					+ MessageClass.setMessageString(this.TC9409.getGITMRS(), 3)
					+ MessageClass.setMessageNumber(this.TC9409.getGILETA(), 15)
					+ MessageClass.setMessageNumber(this.TC9409.getGILETD(), 8)
					+ MessageClass.setMessageString(this.TC9409.getGIDBB(), 6)
					+ MessageClass.setMessageString(this.TC9409.getGIDBR(), 5)
					+ MessageClass.setMessageString(this.TC9409.getGIDBAN(), 19)
					+ MessageClass.setMessageString(this.TC9409.getGIDBAT(), 3)
					+ MessageClass.setMessageNumber(this.TC9409.getGIMAXA(), 15)
					+ MessageClass.setMessageNumber(this.TC9409.getGIMINA(), 15)
					+ MessageClass.setMessageString(this.TC9409.getGIDDAN(), 12)
					+ MessageClass.setMessageNumber(this.TC9409.getGIRSEQ(), 5)
					+ MessageClass.setMessageString(this.TC9409.getGIRMK(), 25)
					+ MessageClass.setMessageNumber(this.TC9409.getGIDTTM(), 14)
					+ MessageClass.setMessageNumber(this.TC9409.getKTKRTN(), 19)
					+ MessageClass.setMessageNumber(this.TC9409.getKRKNST(), 3)
					+ MessageClass.setMessageString(this.TC9409.getIPNAME(), 40)
					+ MessageClass.setMessageString(this.TC9409.getIPOLIC(), 40)
					+ MessageClass.setMessageString(this.TC9409.getIPNWIC(), 40)
					+ MessageClass.setMessageString(this.TC9409.getKRKAID(), 3)
					+ MessageClass.setMessageString(this.TC9409.getKADESC(), 25)
					+ MessageClass.setMessageString(this.TC9409.getWDNFND(), 1)
					+ MessageClass.setMessageNumber(this.TC9409.getGILEFT(), 8)
					+ MessageClass.setMessageNumber(this.TC9409.getGIDDMD(), 2);
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9409";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
