// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9001Rq_LoanInstallmentTier;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9001_LoanInstallmentTier extends CustomJavaAction<java.lang.String>
{
	private java.util.List<IMendixObject> __request;
	private java.util.List<ktc_scs_schema.proxies.TC9001Rq_LoanInstallmentTier> request;

	public SetTC9001_LoanInstallmentTier(IContext context, java.util.List<IMendixObject> request)
	{
		super(context);
		this.__request = request;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.request = new java.util.ArrayList<ktc_scs_schema.proxies.TC9001Rq_LoanInstallmentTier>();
		if (__request != null)
			for (IMendixObject __requestElement : __request)
				this.request.add(ktc_scs_schema.proxies.TC9001Rq_LoanInstallmentTier.initialize(getContext(), __requestElement));

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			for (int i = 0; i < 6; i++)
			{
				if (this.request.size() > 0 && i < this.request.size())
				{
					TC9001Rq_LoanInstallmentTier obj = (TC9001Rq_LoanInstallmentTier) this.request.get(i);
					
					strMessageDetail.append(MessageClass.setMessageNumber(obj.getWDTTRM(), 3));
					strMessageDetail.append(MessageClass.setMessageString(obj.getWDTINC(), 3));
					strMessageDetail.append(MessageClass.setMessageNumber(obj.getWDTINA(), 15));
				}
				else
				{
					strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
					strMessageDetail.append(MessageClass.setMessageString("", 3));
					strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
				}
			}
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9001_LoanInstallmentTier";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
