// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9048 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC9048_IPPORD04DS mxObject;

	public SetTC9048(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC9048_IPPORD04DS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication =	MessageClass.setMessageNumber(this.mxObject.getPPBNTN(), 9)
					+ MessageClass.setMessageNumber(this.mxObject.getPPBLON(), 7)
					+ MessageClass.setMessageNumber(this.mxObject.getPPORNO(), 7)
					+ MessageClass.setMessageNumber(this.mxObject.getPPORLN(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getPPBKID(), 11)
					+ MessageClass.setMessageNumber(this.mxObject.getPPMCTC(), 4)
					+ MessageClass.setMessageString(this.mxObject.getPPCCDE(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getPPINTC(), 4)
					+ MessageClass.setMessageNumber(this.mxObject.getPPNBRI(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getPPORDT(), 8)
					+ MessageClass.setMessageNumber(this.mxObject.getPPORAM(), 15)
					+ MessageClass.setMessageString(this.mxObject.getPPORST(), 1)
					+ MessageClass.setMessageString(this.mxObject.getPPCCRS(), 3)
					+ MessageClass.setMessageString(this.mxObject.getPPEREF(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getPPKRTN(), 19)
					+ MessageClass.setMessageString(this.mxObject.getPPPYFQ(), 1)
					+ MessageClass.setMessageString(this.mxObject.getPPKNTR(), 6)
					+ MessageClass.setMessageString(this.mxObject.getPPIPSV(), 3)
					+ MessageClass.setMessageString(this.mxObject.getPPPGDS(), 40)
					+ MessageClass.setMessageString(this.mxObject.getPPAUST(), 1)
					+ MessageClass.setMessageNumber(this.mxObject.getPPPRBO(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getPPORBL(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getPPBLSQ(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getPPNBDT(), 8)
					+ MessageClass.setMessageNumber(this.mxObject.getPPDTTM(), 14)
					+ MessageClass.setMessageString(this.mxObject.getPPTMID(), 8)
					+ MessageClass.setMessageString(this.mxObject.getPPTMBT(), 8)
					+ MessageClass.setMessageString(this.mxObject.getPPMODP(), 6)
					+ MessageClass.setMessageString(this.mxObject.getMXARJC(), 4)
					+ MessageClass.setMessageNumber(this.mxObject.getTRBNTN(), 9)
					+ MessageClass.setMessageNumber(this.mxObject.getTRBLON(), 7)
					+ MessageClass.setMessageNumber(this.mxObject.getTRTTYP(), 4)
					+ MessageClass.setMessageString(this.mxObject.getTRKORR(), 1)
					+ MessageClass.setMessageNumber(this.mxObject.getTRTRST(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getTRBDAT(), 8)
					+ MessageClass.setMessageString(this.mxObject.getTRCANM(), 40)
					+ MessageClass.setMessageNumber(this.mxObject.getKTSPKD(), 1)
					+ MessageClass.setMessageNumber(this.mxObject.getKRAVST(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getKTKNTN(), 19)
					+ MessageClass.setMessageNumber(this.mxObject.getKRGACC(), 19)
					+ MessageClass.setMessageNumber(this.mxObject.getKRKNST(), 3)
					+ MessageClass.setMessageString(this.mxObject.getKRRKID(), 6)
					+ MessageClass.setMessageString(this.mxObject.getKRCCDE(), 3)
					+ MessageClass.setMessageString(this.mxObject.getWDNAME(), 40)
					+ MessageClass.setMessageNumber(this.mxObject.getWDIBEL(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getWDPBEL(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getWDTBEL(), 15)
					+ MessageClass.setMessageString(this.mxObject.getPCMMTP(), 2)
					+ MessageClass.setMessageString(this.mxObject.getWDORST(), 1)
					+ MessageClass.setMessageString(this.mxObject.getWDBPNM(), 40)
					+ MessageClass.setMessageNumber(this.mxObject.getPPINTI(), 4)
					+ MessageClass.setMessageNumber(this.mxObject.getWDUNBL(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getWDTBIL(), 15)
					+ MessageClass.setMessageString(this.mxObject.getPPSTAS(), 1)
					+ MessageClass.setMessageString(this.mxObject.getPPTSRC(), 1)
					+ MessageClass.setMessageNumber(this.mxObject.getTRVLDT(), 8)
					+ MessageClass.setMessageNumber(this.mxObject.getPPUBNT(), 9)
					+ MessageClass.setMessageNumber(this.mxObject.getPPUBLO(), 7)
					+ MessageClass.setMessageNumber(this.mxObject.getPPIPRT(), 5)
					+ MessageClass.setMessageString(this.mxObject.getPPUPBY(), 10);
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}

		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9048";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
