// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC9201 extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long totalLine;
	private IMendixObject __TC9201;
	private ktc_scs_schema.proxies.TC9201_TEXTRGDS TC9201;

	public SetTC9201(IContext context, java.lang.Long totalLine, IMendixObject TC9201)
	{
		super(context);
		this.totalLine = totalLine;
		this.__TC9201 = TC9201;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC9201 = __TC9201 == null ? null : ktc_scs_schema.proxies.TC9201_TEXTRGDS.initialize(getContext(), __TC9201);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		List<String> textLine = new ArrayList<String>();
		
		int sIdx = 0;
		int eIdx = 59;
		
		try
		{		
			//Split Text Line
			for (int i = 0; i < this.totalLine; i++) 
			{
				//TODO

				if(this.TC9201.getAllText().length() > eIdx)
				{
					textLine.add(this.TC9201.getAllText().trim().substring(sIdx, eIdx));
				}
				else
				{
					textLine.add(this.TC9201.getAllText().trim().substring(sIdx, this.TC9201.getAllText().length()));
				}

				sIdx = eIdx;
				eIdx = eIdx + 59;
			}
			//Set Value
			for (int i = 0; i < this.totalLine; i++) {
				
				strMessageDetail.append(MessageClass.setMessageNumber(this.TC9201.getTXNTYP(), 1));				
				strMessageDetail.append(MessageClass.setMessageNumber(this.TC9201.getTXTKEY(), 19));
				strMessageDetail.append(MessageClass.setMessageString(this.TC9201.getTXNCAT(), 6));
				strMessageDetail.append(MessageClass.setMessageNumber(this.TC9201.getTXTDAT(), 8));
				strMessageDetail.append(MessageClass.setMessageNumber(this.TC9201.getTXDTTM(), 14));
				strMessageDetail.append(MessageClass.setMessageString(this.TC9201.getTXUSER(), 10));
				strMessageDetail.append(MessageClass.setMessageString(textLine.get(i), 60));
				strMessageDetail.append(MessageClass.setMessageNumber(this.TC9201.getTXRMOD(), 1));
				strMessageDetail.append(MessageClass.setMessageNumber(this.TC9201.getTXRDAT(), 8));
				strMessageDetail.append(MessageClass.setMessageNumber(this.TC9201.getTXDLDT(), 8));
				strMessageDetail.append(MessageClass.setMessageString(this.TC9201.getTXOLIC(), 40));
				strMessageDetail.append(MessageClass.setMessageString(this.TC9201.getTXDLBY(), 10));
				strMessageDetail.append(MessageClass.setMessageString(this.TC9201.getTXWIND(), 1));
			}
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9201";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
