// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9192 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String customerNumber;
	private java.lang.String bankCode;
	private java.lang.String bankAccountType;
	private java.lang.String bankAccountNumber;
	private java.lang.String bankAccSeqNo;
	private java.lang.String bankAccountStatus;
	private java.lang.String dateAndTime;
	private java.lang.String accountOwnerFlag;
	private java.lang.String othPayeeID;
	private java.lang.String othPayeeName;
	private java.lang.String othPayeeIDType;
	private java.lang.String othPayeeAddress;
	private java.lang.String channel;

	public SetTC9192(IContext context, java.lang.String customerNumber, java.lang.String bankCode, java.lang.String bankAccountType, java.lang.String bankAccountNumber, java.lang.String bankAccSeqNo, java.lang.String bankAccountStatus, java.lang.String dateAndTime, java.lang.String accountOwnerFlag, java.lang.String othPayeeID, java.lang.String othPayeeName, java.lang.String othPayeeIDType, java.lang.String othPayeeAddress, java.lang.String channel)
	{
		super(context);
		this.customerNumber = customerNumber;
		this.bankCode = bankCode;
		this.bankAccountType = bankAccountType;
		this.bankAccountNumber = bankAccountNumber;
		this.bankAccSeqNo = bankAccSeqNo;
		this.bankAccountStatus = bankAccountStatus;
		this.dateAndTime = dateAndTime;
		this.accountOwnerFlag = accountOwnerFlag;
		this.othPayeeID = othPayeeID;
		this.othPayeeName = othPayeeName;
		this.othPayeeIDType = othPayeeIDType;
		this.othPayeeAddress = othPayeeAddress;
		this.channel = channel;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();

		try {
			
			strMessageDetail.append(MessageClass.setMessageNumber(this.customerNumber, 19));	//	IDKIPN
			strMessageDetail.append(MessageClass.setMessageString(this.bankCode, 6));			//	IDDBB
			strMessageDetail.append(MessageClass.setMessageString(this.bankAccountType, 3));	//	IDDBAT
			strMessageDetail.append(MessageClass.setMessageString(this.bankAccountNumber, 19));	//	IDDBAN
			strMessageDetail.append(MessageClass.setMessageNumber(this.bankAccSeqNo, 2));		//	IDDBSQ
			strMessageDetail.append(MessageClass.setMessageString(this.bankAccountStatus, 1));	//	IDDBST
			strMessageDetail.append(MessageClass.setMessageNumber(this.dateAndTime, 14));		//	IDDTTM
			strMessageDetail.append(MessageClass.setMessageNumber(this.dateAndTime, 14));		//	IDCDTM
			strMessageDetail.append(MessageClass.setMessageString(this.accountOwnerFlag, 3));	//	IDOFLG
			strMessageDetail.append(MessageClass.setMessageString(this.othPayeeID, 40));		//	IDOLIC
			strMessageDetail.append(MessageClass.setMessageString(this.othPayeeIDType, 3));		//	IDOITP
			strMessageDetail.append(MessageClass.setMessageString(this.othPayeeAddress, 200));	//	IDOADR
			strMessageDetail.append(MessageClass.setMessageString(this.othPayeeName, 80));		//	IDONAM
			strMessageDetail.append(MessageClass.setMessageString(this.channel, 3));			//	IDCHNL
			//strMessageDetail.append(MessageClass.setMessageString(this.aliasName, 80));			//	IDALIS
			
		} catch (Exception ex) {
			throw ex;
		}

		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9192";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
