// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC2229 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC2229;
	private ktc_scs_schema.proxies.TC2229_LMTCTL08DS TC2229;

	public SetTC2229(IContext context, IMendixObject TC2229)
	{
		super(context);
		this.__TC2229 = TC2229;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC2229 = __TC2229 == null ? null : ktc_scs_schema.proxies.TC2229_LMTCTL08DS.initialize(getContext(), __TC2229);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.TC2229.getLMKIPN(), 19)
					+ MessageClass.setMessageString(this.TC2229.getIPLSNM(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPINIT(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPNAME(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPNAM2(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPADR1(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPADR2(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPADR3(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPADR4(), 40)
					+ MessageClass.setMessageNumber(this.TC2229.getWDKIPN(), 19)
					+ MessageClass.setMessageString(this.TC2229.getWDLSNM(), 40)
					+ MessageClass.setMessageString(this.TC2229.getWDINIT(), 40)
					+ MessageClass.setMessageString(this.TC2229.getWDNAME(), 40)
					+ MessageClass.setMessageString(this.TC2229.getWDNAM2(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIPOLIC(), 40)
					+ MessageClass.setMessageNumber(this.TC2229.getLMGBAC(), 19)
					+ MessageClass.setMessageNumber(this.TC2229.getLMSPKD(), 1)
					+ MessageClass.setMessageString(this.TC2229.getLMSPRK(), 2)
					+ MessageClass.setMessageNumber(this.TC2229.getLMGNUM(), 19)
					+ MessageClass.setMessageString(this.TC2229.getIGNAME(), 40)
					+ MessageClass.setMessageString(this.TC2229.getIGACTV(), 1)
					+ MessageClass.setMessageNumber(this.TC2229.getIPFDAT(), 8)
					+ MessageClass.setMessageNumber(this.TC2229.getLMLNUM(), 19)
					+ MessageClass.setMessageNumber(this.TC2229.getLMLLVL(), 3)
					+ MessageClass.setMessageString(this.TC2229.getLMDESC(), 25)
					+ MessageClass.setMessageString(this.TC2229.getLMSHRD(), 1)
					+ MessageClass.setMessageNumber(this.TC2229.getLMBKRD(), 11)
					+ MessageClass.setMessageString(this.TC2229.getLMCRCC(), 3)
					+ MessageClass.setMessageNumber(this.TC2229.getWDAVAI(), 15)
					+ MessageClass.setMessageNumber(this.TC2229.getLMPRBO(), 15)
					+ MessageClass.setMessageNumber(this.TC2229.getLMEARM(), 15)
					+ MessageClass.setMessageNumber(this.TC2229.getLMUSGA(), 15)
					+ MessageClass.setMessageNumber(this.TC2229.getLMDBAL(), 15)
					+ MessageClass.setMessageNumber(this.TC2229.getLMSALC(), 11)
					+ MessageClass.setMessageNumber(this.TC2229.getWDSAAV(), 11)
					+ MessageClass.setMessageNumber(this.TC2229.getLMCALC(), 11)
					+ MessageClass.setMessageNumber(this.TC2229.getWDCAAV(), 11)
					+ MessageClass.setMessageNumber(this.TC2229.getLMGLMN(), 19)
					+ MessageClass.setMessageNumber(this.TC2229.getLMDTTM(), 14)
					+ MessageClass.setMessageNumber(this.TC2229.getLMBKRT(), 19);
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC2229";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
