// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC8214 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String accountNo1;
	private java.lang.String accountNo2;
	private java.lang.String cardNo;

	public SetTC8214(IContext context, java.lang.String accountNo1, java.lang.String accountNo2, java.lang.String cardNo)
	{
		super(context);
		this.accountNo1 = accountNo1;
		this.accountNo2 = accountNo2;
		this.cardNo = cardNo;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuffer sb = new StringBuffer();

		try {

			sb.append(MessageClass.setMessageNumber(this.accountNo1, 19));
			sb.append(MessageClass.setMessageNumber(this.accountNo2, 12));
			sb.append(MessageClass.setMessageNumber(this.cardNo, 19));

		} catch (Exception ex) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}

		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC8214";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
