// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTCLNI8000 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __tcLNI8000Rq;
	private ktc_scs_schema.proxies.TCLNI8000Rq tcLNI8000Rq;

	public SetTCLNI8000(IContext context, IMendixObject tcLNI8000Rq)
	{
		super(context);
		this.__tcLNI8000Rq = tcLNI8000Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.tcLNI8000Rq = __tcLNI8000Rq == null ? null : ktc_scs_schema.proxies.TCLNI8000Rq.initialize(getContext(), __tcLNI8000Rq);

		// BEGIN USER CODE
		StringBuilder sb = new StringBuilder();
		
		try
		{
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINCIFN(), 19));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINIDT(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getININM(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINISCO(), 3));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINBIR8(), 8));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINGEN(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINENM1(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINENM2(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINESA1(), 10));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINTNM1(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINTNM2(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINESA2(), 10));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINHPHN(), 20));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINOPHN(), 20));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINMPHN(), 20));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINEMIL(), 100));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINEMPL(), 80));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINEMP2(), 80));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINRESTY(), 2));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINRESP(), 6));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINOCCU(), 10));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINNAT(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINMARI(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getININDI(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINSTAF(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINADTY(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINADD1(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINADD2(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINADD3(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINADD4(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINCITY(), 200));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINSTAT(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINZIP(), 9));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2ADTY(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2ADD1(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2ADD2(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2ADD3(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2ADD4(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2CITY(), 200));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2STAT(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI2ZIP(), 9));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3ADTY(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3ADD1(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3ADD2(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3ADD3(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3ADD4(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3CITY(), 200));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3STAT(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI3ZIP(), 9));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4ADTY(), 1));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4ADD1(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4ADD2(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4ADD3(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4ADD4(), 40));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4CITY(), 200));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4STAT(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getI4ZIP(), 9));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINTYPE(), 10));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINCURR(), 4));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINODT8(), 8));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINTERM(), 5));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINTMCD(), 1));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINLAMT(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINPFRE(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINPFRQ(), 1));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINPDUE(), 8));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINPDAY(), 2));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINCARP(), 25));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINPROV(), 3));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINCARC(), 25));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINMAKE(), 5));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINMODE(), 5));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINCPAM(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getREVAM1(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getREVAM2(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getREVAM3(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getREVAM4(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getREVAM5(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getREVAC1(), 19));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getREVAC2(), 19));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getREVCOA(), 20));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getREVCOB(), 20));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getREVCOC(), 20));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getREVCO1(), 10));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getREVCO2(), 10));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getREVCO3(), 10));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINCCINS(), 3));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINCTOV(), 3));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getININS8(), 8));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINENS8(), 8));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINIAMT(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINPMAT(), 17, 2));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINACT(), 3));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINCST8(), 8));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINCEN8(), 8));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINACTA(), 17, 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getMATDT8(), 8));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINCOM(), 2));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINBRN(), 5));
			sb.append(MessageClass.setMessageString(this.tcLNI8000Rq.getINERCH(), 1));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8000Rq.getINGCIF(), 19));
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTCLNI8000";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
