// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9401 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC8401_SPKORTDS mxObject;

	public SetTC9401(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC8401_SPKORTDS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		StringBuilder strMessageApplication = new StringBuilder();
		
		try
		{
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKKRTN(), 19));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSFDN(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKRREF(), 12));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTKNTN(), 19));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getKTEMNM(), 40));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKRKID(), 6));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSRNETW(), 3));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTKRST(), 3));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTDN(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKSPTM(), 6));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKNSTS(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKNDAT(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTSPKD(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKSPRK(), 2));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKAKTK(), 2));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKVIPA(), 15));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKRESP(), 2));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKARJC(), 4));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHG(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKUSER(), 10));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTDI(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG1(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD1(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD1(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG2(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD2(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD2(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG3(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD3(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD3(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG4(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD4(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD4(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG5(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD5(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD5(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG6(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD6(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD6(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG7(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD7(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD7(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG8(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD8(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD8(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG9(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD9(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD9(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKREG0(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKSTD0(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKCHD0(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKTSRC(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKDTTM(), 14));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKLSTS(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKRREL(), 12));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getSKTSST(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKRRET(), 12));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTFPKF(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getKTKTTP(), 3));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTGTDT(), 6));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTGTDP(), 6));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getKTGTST(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTEMDT(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTSPDT(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTAUDT(), 8));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getWDIND(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getWDOURCRD(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getWDSTPI(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getWDINTSTP(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSRCPGM(), 3));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKYDTTM(), 14));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getKTDTTM(), 14));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getWDSPKD(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getWDFOUND(), 1));
			strMessageApplication.append(MessageClass.setMessageString(this.mxObject.getSKSPR2(), 3));
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9401";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
