// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5410 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String accountNumber;
	private java.lang.String cardNumber;

	public SetTC5410(IContext context, java.lang.String accountNumber, java.lang.String cardNumber)
	{
		super(context);
		this.accountNumber = accountNumber;
		this.cardNumber = cardNumber;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			return MessageClass.setMessageNumber(this.accountNumber, 19)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageNumber("0", 3)
					+ MessageClass.setMessageString("", 3)
					+ MessageClass.setMessageString("", 1)
					+ MessageClass.setMessageNumber("0", 15)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageString("", 3)
					+ MessageClass.setMessageString("", 3)
					+ MessageClass.setMessageNumber("0", 15)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageString("", 6)
					+ MessageClass.setMessageString("", 5)
					+ MessageClass.setMessageString("", 19)
					+ MessageClass.setMessageString("", 3)
					+ MessageClass.setMessageNumber("0", 15)
					+ MessageClass.setMessageNumber("0", 15)
					+ MessageClass.setMessageString("", 12)
					+ MessageClass.setMessageNumber("0", 5)
					+ MessageClass.setMessageString("", 25)
					+ MessageClass.setMessageNumber("0", 14)
					+ MessageClass.setMessageNumber(this.cardNumber, 19);
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5410";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
