// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC9204 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC9204Rq;
	private ktc_scs_schema.proxies.TC9204_CUSEMPDS TC9204Rq;

	public SetTC9204(IContext context, IMendixObject TC9204Rq)
	{
		super(context);
		this.__TC9204Rq = TC9204Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC9204Rq = __TC9204Rq == null ? null : ktc_scs_schema.proxies.TC9204_CUSEMPDS.initialize(getContext(), __TC9204Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPKIPN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPRCT1(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPSEQ1(), 4));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPARBG(), 80));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPINDS(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPANST(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPANDT(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPOCCP(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPAINK(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPOTSC(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPINCO(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPOTAM(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPSN1(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD1(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD2(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD3(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD4(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEPNR(), 9));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPACTY(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPESTE(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPECNC(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPTEL(), 20));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPEXT1(), 7));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPTEL3(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPAFAX(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEMLO(), 100));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPEMP(), 80));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPANS(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPPNDT(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPOCP2(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPAIN2(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPSN2(), 25));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPINC2(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD5(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD6(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD7(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEAD8(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPPN1(), 9));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPCTY(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEST1(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPECN1(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPTEL(), 20));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPEXT2(), 7));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPFAX(), 20));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPEML(), 100));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPARB2(), 80));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPAPNR(), 9));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPINDP(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPMINC(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPALLW(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPCOMM(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPEMP1(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPCSEQ(), 4));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPPEM2(), 80));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPPSEQ(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9204Rq.getIPDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPSTFS(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9204Rq.getIPSTFL(), 1));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9204";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
