// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5207 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5207Rq;
	private ktc_scs_schema.proxies.TC5207_CUSOCSDS TC5207Rq;

	public SetTC5207(IContext context, IMendixObject TC5207Rq)
	{
		super(context);
		this.__TC5207Rq = TC5207Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5207Rq = __TC5207Rq == null ? null : ktc_scs_schema.proxies.TC5207_CUSOCSDS.initialize(getContext(), __TC5207Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5207Rq.getOCKIPN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5207Rq.getOCOCCN(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5207Rq.getOCSEQ1(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5207Rq.getOCOCCD(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5207Rq.getOCDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5207Rq.getOCREMK(), 30));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5207";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
