// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC8738 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC8738Rq;
	private ktc_scs_schema.proxies.TC8738_KNTAVTDS TC8738Rq;

	public SetTC8738(IContext context, IMendixObject TC8738Rq)
	{
		super(context);
		this.__TC8738Rq = TC8738Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC8738Rq = __TC8738Rq == null ? null : ktc_scs_schema.proxies.TC8738_KNTAVTDS.initialize(getContext(), __TC8738Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAKAID(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKACCDE(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKADESC(), 25));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKALIMI(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKALIMA(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKALIRE(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAVGN(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAVGP(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAKSOT(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKANOLA(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAVR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKABETS(), 2));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKABETF(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKALALA(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKARSTB(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAKNTF(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAVIF(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAPRIO(), 2));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAGLPR(), 2));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKASPER(), 12));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAABFM(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKABFR1(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKABFR2(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAUTKD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMRKD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKARDGR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMCAP(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKASCAP(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAPCAP(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAAPID(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAUPKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAOPKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKASKKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAAV(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAFSM1(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAFSM2(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAVLDM(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAITPN(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAAB(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAACKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKARAKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAKBKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAKAKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAAKR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAPNRC(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKANOD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMUPR(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAWACD(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKASSTS(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKASTDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAGEM(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKARMOD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKARDAY(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAGBET(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAGBEF(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAAY(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAPPA(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAPVA(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAFLST(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAWINT(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAPPI(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAPVI(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAGRCL(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAPGRD(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAYBSE(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAIFDY(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMALD(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMOLI(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMRND(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMALV(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKARNDI(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKAOTBM(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMARR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMAXR(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMAXO(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAMSLM(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKANSLM(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKADTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getKAAAY1(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getAIDRPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getAIERPR(), 5));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getAIICDE(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getAIMRPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getAIOTPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getAITRPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getWDCOPY(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getWDKAID(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getICMRPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getICTRPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getICDRPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getICOTPR(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getICUSGR(), 5));
			strMessageDetail.append(MessageClass.setMessageString(this.TC8738Rq.getKASTFS(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC8738Rq.getAISMRP(), 5));
			
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC8738";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
