// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5581 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC5581_GLAMTS01DS mxObject;

	public SetTC5581(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC5581_GLAMTS01DS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		//String strMessageApplication = "";
		StringBuffer strMessageApplication = new StringBuffer();
		
		try
		{
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMBNTN(), 9));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMBLON(), 7));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMGACC(), 19));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMSEQ1(), 4));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMBEL(), 15));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMSCHD(), 8));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMAMST(), 1));
			strMessageApplication.append(MessageClass.setMessageNumber(this.mxObject.getAMDTTM(), 14));
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5581";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
