// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTCLNI8808 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __tcLNI8808Rq;
	private ktc_scs_schema.proxies.TCLNI8808Rq tcLNI8808Rq;

	public SetTCLNI8808(IContext context, IMendixObject tcLNI8808Rq)
	{
		super(context);
		this.__tcLNI8808Rq = tcLNI8808Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.tcLNI8808Rq = __tcLNI8808Rq == null ? null : ktc_scs_schema.proxies.TCLNI8808Rq.initialize(getContext(), __tcLNI8808Rq);

		// BEGIN USER CODE
		StringBuilder sb = new StringBuilder();
		
		try
		{
			sb.append(MessageClass.setMessageNumber(this.tcLNI8808Rq.getLWSACT(), 19));
			sb.append(MessageClass.setMessageNumber(this.tcLNI8808Rq.getLWSTAM(), 17,2));
			sb.append(MessageClass.setMessageString(this.tcLNI8808Rq.getLWSSEQ(), 22));
			
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTCLNI8808";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
