// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import java.text.SimpleDateFormat;
import java.util.Date;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC3607 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String cardNumber;
	private java.lang.String transactionAmount;
	private java.lang.String transactionKey;
	private java.lang.String authCode;
	private java.lang.String authType;

	public SetTC3607(IContext context, java.lang.String cardNumber, java.lang.String transactionAmount, java.lang.String transactionKey, java.lang.String authCode, java.lang.String authType)
	{
		super(context);
		this.cardNumber = cardNumber;
		this.transactionAmount = transactionAmount;
		this.transactionKey = transactionKey;
		this.authCode = authCode;
		this.authType = authType;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			Date dt = new Date();
			SimpleDateFormat sdf = new SimpleDateFormat("MMddhhmmss");
			
			if (this.authType.toString().trim().toUpperCase().equals("Q"))
			{
				strMessageDetail.append("0100");
				strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));
				strMessageDetail.append("280000");
				strMessageDetail.append(MessageClass.setMessageNumber(this.transactionAmount, 15, 2));
				strMessageDetail.append(MessageClass.setMessageNumber(this.transactionAmount, 15, 2));
				strMessageDetail.append(sdf.format(dt));
				strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
				strMessageDetail.append(MessageClass.setMessageNumber("0", 6));
				strMessageDetail.append(MessageClass.setMessageNumber("0", 6));
				strMessageDetail.append(MessageClass.setMessageNumber("0", 6));
				strMessageDetail.append("5999");
				strMessageDetail.append("000");
				strMessageDetail.append(MessageClass.setMessageNumber("0", 11));
				strMessageDetail.append(MessageClass.setMessageString("", 12));
				strMessageDetail.append(MessageClass.setMessageString("", 6));
				strMessageDetail.append(MessageClass.setMessageString("", 2));
				strMessageDetail.append(MessageClass.setMessageString("", 15));
				strMessageDetail.append(MessageClass.setMessageString("", 40));
				strMessageDetail.append(MessageClass.setMessageString("P", 256));
				strMessageDetail.append("764");
				strMessageDetail.append("764");
				strMessageDetail.append(MessageClass.setMessageString("", 40));
			}
			else if (this.authType.toString().trim().toUpperCase().equals("V"))
			{
				strMessageDetail.append("0400");
				strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));
				strMessageDetail.append("280000");
				strMessageDetail.append(MessageClass.setMessageNumber(this.transactionAmount, 15, 2));
				strMessageDetail.append(MessageClass.setMessageNumber(this.transactionAmount, 15, 2));
				strMessageDetail.append(sdf.format(dt));
				strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
				strMessageDetail.append(this.transactionKey.toString().trim().substring(0, 6));
				strMessageDetail.append(MessageClass.setMessageNumber("0", 6));
				strMessageDetail.append(MessageClass.setMessageNumber("0", 6));
				strMessageDetail.append("5999");
				strMessageDetail.append("000");
				strMessageDetail.append(MessageClass.setMessageNumber("0", 11));
				strMessageDetail.append(MessageClass.setMessageString(this.transactionKey.toString().trim().substring(6), 12));
				strMessageDetail.append(MessageClass.setMessageString(this.authCode, 6));
				strMessageDetail.append(MessageClass.setMessageString("", 2));
				strMessageDetail.append(MessageClass.setMessageString("", 15));
				strMessageDetail.append(MessageClass.setMessageString("", 40));
				strMessageDetail.append(MessageClass.setMessageString("P", 256));
				strMessageDetail.append("764");
				strMessageDetail.append("764");
				strMessageDetail.append(MessageClass.setMessageString("", 40));
			}
			else
			{
				strMessageDetail.append("");
			}
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC3607";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
