// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktc_scs_schema.proxies.TC9001Rq_Plastic;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9001_Plastic extends CustomJavaAction<java.lang.String>
{
	private java.util.List<IMendixObject> __request;
	private java.util.List<ktc_scs_schema.proxies.TC9001Rq_Plastic> request;

	public SetTC9001_Plastic(IContext context, java.util.List<IMendixObject> request)
	{
		super(context);
		this.__request = request;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.request = new java.util.ArrayList<ktc_scs_schema.proxies.TC9001Rq_Plastic>();
		if (__request != null)
			for (IMendixObject __requestElement : __request)
				this.request.add(ktc_scs_schema.proxies.TC9001Rq_Plastic.initialize(getContext(), __requestElement));

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			if (this.request.size() > 0)
			{
				TC9001Rq_Plastic obj = (TC9001Rq_Plastic)this.request.get(0);
				
				strMessageDetail.append(MessageClass.setMessageNumber(obj.getKTKRTN(), 19));
				strMessageDetail.append(MessageClass.setMessageString(obj.getANEMNM(), 26));
				strMessageDetail.append(MessageClass.setMessageString(obj.getANEMN1(), 26));
				strMessageDetail.append(MessageClass.setMessageString(obj.getWDDESP(), 6));
				strMessageDetail.append(MessageClass.setMessageString(obj.getANCLCB(), 1));
				strMessageDetail.append(MessageClass.setMessageString(obj.getWANUAPV(), 6));
				strMessageDetail.append(MessageClass.setMessageString(obj.getANEAPN(), 20));
				strMessageDetail.append(MessageClass.setMessageString(obj.getWDRUSH(), 1));
				strMessageDetail.append(MessageClass.setMessageString(obj.getKTCBI2(), 1));
				strMessageDetail.append(MessageClass.setMessageString(obj.getKTCBI3(), 1));
			}
			else
			{
				strMessageDetail.append(MessageClass.setMessageNumber("0", 19));
				strMessageDetail.append(MessageClass.setMessageString("", 26));
				strMessageDetail.append(MessageClass.setMessageString("", 26));
				strMessageDetail.append(MessageClass.setMessageString("", 2));
				strMessageDetail.append(MessageClass.setMessageString("", 6));
				strMessageDetail.append(MessageClass.setMessageString("", 6));
				strMessageDetail.append(MessageClass.setMessageString("", 20));
				strMessageDetail.append(MessageClass.setMessageString("", 1));
				strMessageDetail.append(MessageClass.setMessageString("", 1));
				strMessageDetail.append(MessageClass.setMessageString("", 1));
			}
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9001_Plastic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
