// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC2406 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String accountNo;
	private java.lang.String installmentNumber;
	private java.lang.String dueDate;

	public SetTC2406(IContext context, java.lang.String accountNo, java.lang.String installmentNumber, java.lang.String dueDate)
	{
		super(context);
		this.accountNo = accountNo;
		this.installmentNumber = installmentNumber;
		this.dueDate = dueDate;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String strMessageApplication = "";

		try {
				strMessageApplication = MessageClass.setMessageNumber(this.accountNo, 19)
					+ MessageClass.setMessageNumber(this.dueDate, 8)
					+ MessageClass.setMessageNumber(this.installmentNumber, 5);
				
		} catch (Exception ex) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}

		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC2406";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
