// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC1240 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC1240Rq;
	private ktc_scs_schema.proxies.TC1240_ACCASO03DS TC1240Rq;

	public SetTC1240(IContext context, IMendixObject TC1240Rq)
	{
		super(context);
		this.__TC1240Rq = TC1240Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC1240Rq = __TC1240Rq == null ? null : ktc_scs_schema.proxies.TC1240_ACCASO03DS.initialize(getContext(), __TC1240Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASPRAC(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASKNTN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1240Rq.getASACTP(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1240Rq.getASCANM(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1240Rq.getASRKID(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASORGA(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASRAT1(), 5));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASSLDO(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASCDUE(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASLBET(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASRES1(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASTDUE(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1240Rq.getASKNTR(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASKRTN(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASIBDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASAINB(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASBELP(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASKNST(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1240Rq.getASAVST(), 3));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC1240";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
