// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC9210 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC9210Rq;
	private ktc_scs_schema.proxies.TC9210_CUSOCSDS TC9210Rq;

	public SetTC9210(IContext context, IMendixObject TC9210Rq)
	{
		super(context);
		this.__TC9210Rq = TC9210Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC9210Rq = __TC9210Rq == null ? null : ktc_scs_schema.proxies.TC9210_CUSOCSDS.initialize(getContext(), __TC9210Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9210Rq.getOCKIPN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9210Rq.getOCOCCN(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9210Rq.getOCSEQ1(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9210Rq.getOCOCCD(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC9210Rq.getOCDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC9210Rq.getOCREMK(), 30));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9210";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
