// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC3603 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String cardNumber;
	private java.lang.String permCreditLimit;
	private java.lang.String manualCreditLimitFlag;
	private java.lang.String cardIncome;
	private java.lang.String loanIncome;
	private java.lang.String companyName;
	private java.lang.String customerType;
	private java.lang.String mobilePhone;
	private java.lang.String officePhone;
	private java.lang.String homePhone;
	private java.lang.String officePhoneExt;
	private java.lang.String homePhoneExt;

	public SetTC3603(IContext context, java.lang.String cardNumber, java.lang.String permCreditLimit, java.lang.String manualCreditLimitFlag, java.lang.String cardIncome, java.lang.String loanIncome, java.lang.String companyName, java.lang.String customerType, java.lang.String mobilePhone, java.lang.String officePhone, java.lang.String homePhone, java.lang.String officePhoneExt, java.lang.String homePhoneExt)
	{
		super(context);
		this.cardNumber = cardNumber;
		this.permCreditLimit = permCreditLimit;
		this.manualCreditLimitFlag = manualCreditLimitFlag;
		this.cardIncome = cardIncome;
		this.loanIncome = loanIncome;
		this.companyName = companyName;
		this.customerType = customerType;
		this.mobilePhone = mobilePhone;
		this.officePhone = officePhone;
		this.homePhone = homePhone;
		this.officePhoneExt = officePhoneExt;
		this.homePhoneExt = homePhoneExt;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));			//	KRKRTN
			strMessageDetail.append(MessageClass.setMessageNumber(this.permCreditLimit, 11));		//	KRBKRD
			strMessageDetail.append(MessageClass.setMessageString(this.manualCreditLimitFlag, 1));	//	KRMLMF
			strMessageDetail.append(MessageClass.setMessageNumber(this.cardIncome, 15));			//	IPINCO
			strMessageDetail.append(MessageClass.setMessageNumber(this.loanIncome, 15));			//	IPOTAM
			strMessageDetail.append(MessageClass.setMessageString(this.companyName, 80));			//	IPARBG
			strMessageDetail.append(MessageClass.setMessageString(this.customerType, 3));			//	IPCTCD
			strMessageDetail.append(MessageClass.setMessageString(this.mobilePhone, 20));			//	IPTEL3
			strMessageDetail.append(MessageClass.setMessageString(this.officePhone, 20));			//	IPTELA
			strMessageDetail.append(MessageClass.setMessageString(this.homePhone, 20));				//	IPTELH
			strMessageDetail.append(MessageClass.setMessageNumber(this.homePhoneExt, 7));			//	IPTELHE
			strMessageDetail.append(MessageClass.setMessageNumber(this.officePhoneExt, 7));			//	IPTELAE
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC3603";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
