// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC1242 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC1242_KNTUTD02DS mxObject;

	public SetTC1242(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC1242_KNTUTD02DS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		String strMessageApplication = "";

		try {
			strMessageApplication = MessageClass.setMessageNumber(this.mxObject.getKUKNTN(), 19)
					+ MessageClass.setMessageNumber(this.mxObject.getKUPERI(),  5)
					+ MessageClass.setMessageNumber(this.mxObject.getKUSTMD(),  8)
					+ MessageClass.setMessageNumber(this.mxObject.getKUSKUT(),  8)
					+ MessageClass.setMessageNumber(this.mxObject.getKUSLMT(), 11)
					+ MessageClass.setMessageNumber(this.mxObject.getKUISLD(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getKUUSLD(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getKURES1(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getWDMTHA(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getKULBET(), 15)
					+ MessageClass.setMessageString(this.mxObject.getWDINDI(), 1)
					+ MessageClass.setMessageNumber(this.mxObject.getKRUSGA(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getKRUSG2(), 15)
					+ MessageClass.setMessageNumber(this.mxObject.getKRSLDO(), 15)
					+ MessageClass.setMessageString(this.mxObject.getKRSTGR(), 1);
		}catch (Exception ex) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC1242";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
