// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5087 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5087Rq;
	private ktc_scs_schema.proxies.TC5087_INBETR05DS TC5087Rq;

	public SetTC5087(IContext context, IMendixObject TC5087Rq)
	{
		super(context);
		this.__TC5087Rq = TC5087Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5087Rq = __TC5087Rq == null ? null : ktc_scs_schema.proxies.TC5087_INBETR05DS.initialize(getContext(), __TC5087Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINBNTN(), 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINBLON(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINTTYP(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINKRTN(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINKNTN(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINTRDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINVLDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINBDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINTRST(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINBUST(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5087Rq.getINFKOD(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINBKID(), 11));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5087Rq.getINRKID(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINBKMK(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINBEL(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5087Rq.getINCCDE(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINUBNT(), 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINUBLO(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDTTY2(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDKRT2(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDBKM2(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDBEL2(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5087Rq.getWDCCD2(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDBKI2(), 11));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5087Rq.getWDRKI2(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDTRD2(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDVLD2(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getWDTRS2(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5087Rq.getWDATKD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINAMT1(), 15, 2));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINAMT2(), 15, 2));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINSTRDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5087Rq.getINENDDT(), 8));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5087";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
