// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC8047 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String batchNo;
	private java.lang.String batchSeqNo;
	private java.lang.String cardNumber;
	private java.lang.String orderNo;
	private java.lang.String orderLine;
	private java.lang.String PPBNTN;
	private java.lang.String PPBLON;

	public SetTC8047(IContext context, java.lang.String batchNo, java.lang.String batchSeqNo, java.lang.String cardNumber, java.lang.String orderNo, java.lang.String orderLine, java.lang.String PPBNTN, java.lang.String PPBLON)
	{
		super(context);
		this.batchNo = batchNo;
		this.batchSeqNo = batchSeqNo;
		this.cardNumber = cardNumber;
		this.orderNo = orderNo;
		this.orderLine = orderLine;
		this.PPBNTN = PPBNTN;
		this.PPBLON = PPBLON;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.PPBNTN, 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.PPBLON, 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.orderNo,  7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.orderLine, 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));
			strMessageDetail.append(MessageClass.setMessageNumber("0",  4));
			strMessageDetail.append(MessageClass.setMessageString("", 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 4));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageString("", 3));
			strMessageDetail.append(MessageClass.setMessageString("", 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageString("", 6));
			strMessageDetail.append(MessageClass.setMessageString("", 3));
			strMessageDetail.append(MessageClass.setMessageString("", 40));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 14));
			strMessageDetail.append(MessageClass.setMessageString("", 8));
			strMessageDetail.append(MessageClass.setMessageString("", 8));
			strMessageDetail.append(MessageClass.setMessageString("", 6));
			strMessageDetail.append(MessageClass.setMessageString("", 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.batchNo, 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.batchSeqNo, 7));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 4));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
			strMessageDetail.append(MessageClass.setMessageString("", 40));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 1));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 19));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 19));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));
			strMessageDetail.append(MessageClass.setMessageString("", 6));
			strMessageDetail.append(MessageClass.setMessageString("", 3));
			strMessageDetail.append(MessageClass.setMessageString("", 40));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageString("", 2));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageString("", 40));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 4));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 15));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageString("", 1));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 8));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 9));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 7));
			strMessageDetail.append(MessageClass.setMessageNumber("0", 5));
			strMessageDetail.append(MessageClass.setMessageString("", 10));
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC8047";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
