// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC1243 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC1243Rq;
	private ktc_scs_schema.proxies.TC1243_IPPORD04DS TC1243Rq;

	public SetTC1243(IContext context, IMendixObject TC1243Rq)
	{
		super(context);
		this.__TC1243Rq = TC1243Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC1243Rq = __TC1243Rq == null ? null : ktc_scs_schema.proxies.TC1243_IPPORD04DS.initialize(getContext(), __TC1243Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPBNTN(), 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPBLON(),7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPORNO(),7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPORLN(),3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPBKID(),11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPMCTC(),4));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPCCDE(),3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPINTC(),4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPNBRI(),3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPORDT(),8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPORAM(),15));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPORST(),1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPCCRS(),3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPEREF(),15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPKRTN(),19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPPYFQ(),1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPKNTR(),6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPIPSV(),3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPPGDS(),40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPAUST(),1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPPRBO(),15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPORBL(),15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPBLSQ(),3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPNBDT(),8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getPPDTTM(),14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPTMID(),8));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPTMBT(),8));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getPPMODP(),6));
			strMessageDetail.append(MessageClass.setMessageString(this.TC1243Rq.getMXARJC(),4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getTRBNTN(),9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC1243Rq.getTRBLON(),7));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC1243";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
