// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9051 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC9051_KORTRG14DS mxObject;

	public SetTC9051(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC9051_KORTRG14DS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication =	MessageClass.setMessageNumber(this.mxObject.getKTKRTN(), 19)
					+ MessageClass.setMessageNumber(this.mxObject.getKTKNTN(), 19)
					+ MessageClass.setMessageNumber(this.mxObject.getKTKIPN(), 19)
					+ MessageClass.setMessageNumber(this.mxObject.getKTLOPN(), 11)
					+ MessageClass.setMessageString(this.mxObject.getIPINIT(), 40)
					+ MessageClass.setMessageString(this.mxObject.getIPLSNM(), 40)
					+ MessageClass.setMessageString(this.mxObject.getIPNAME(), 32)
					+ MessageClass.setMessageString(this.mxObject.getIPNAM2(), 40)
					+ MessageClass.setMessageString(this.mxObject.getKTEMNM(), 26)
					+ MessageClass.setMessageString(this.mxObject.getKTEMN1(), 26)
					+ MessageClass.setMessageNumber(this.mxObject.getKTKRST(), 3)
					+ MessageClass.setMessageString(this.mxObject.getKTKTTP(), 3)
					+ MessageClass.setMessageNumber(this.mxObject.getKTGTDT(), 6)
					+ MessageClass.setMessageNumber(this.mxObject.getKTGTDP(), 6)
					+ MessageClass.setMessageNumber(this.mxObject.getKTSPKD(), 1)
					+ MessageClass.setMessageString(this.mxObject.getKTRKID(), 6)
					+ MessageClass.setMessageString(this.mxObject.getKTCPGM(), 3)
					+ MessageClass.setMessageString(this.mxObject.getKTPNRI(), 1)
					+ MessageClass.setMessageString(this.mxObject.getKTPINR(), 1)
					+ MessageClass.setMessageNumber(this.mxObject.getKTLPRD(), 8)
					+ MessageClass.setMessageNumber(this.mxObject.getKTFPKF(), 1)
					+ MessageClass.setMessageNumber(this.mxObject.getKTDSKF(), 8)
					+ MessageClass.setMessageNumber(this.mxObject.getKTDTTM(), 14)
					+ MessageClass.setMessageNumber(this.mxObject.getKTEMDT(), 8);
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}

		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9051";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
