// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5150 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5150Rq;
	private ktc_scs_schema.proxies.TC5150_BUTIKR03DS TC5150Rq;

	public SetTC5150(IContext context, IMendixObject TC5150Rq)
	{
		super(context);
		this.__TC5150Rq = TC5150Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5150Rq = __TC5150Rq == null ? null : ktc_scs_schema.proxies.TC5150_BUTIKR03DS.initialize(getContext(), __TC5150Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKBKID(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKKIPN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKBPNM(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKBPN1(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKNAME(), 32));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKEMNM(), 26));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKPNR(), 9));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKCITY(), 25));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKMSTE(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKCNCD(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKMARE(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKVATC(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKCCA(), 7));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKVMCC(), 4));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKEMCC(), 4));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKMMCC(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKTFTG(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKRDVG(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKRDVM(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKSTLM(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKRDST(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKRDSP(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKCCDE(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKSTTP(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKSTPR(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKSSTS(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKATUS(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKCLEC(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5150Rq.getBKDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5150Rq.getBKMODE(), 1));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5150";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
