// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC9047 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __mxObject;
	private ktc_scs_schema.proxies.TC8047_IPPORD04DS mxObject;

	public SetTC9047(IContext context, IMendixObject mxObject)
	{
		super(context);
		this.__mxObject = mxObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.mxObject = __mxObject == null ? null : ktc_scs_schema.proxies.TC8047_IPPORD04DS.initialize(getContext(), __mxObject);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPBNTN(),  9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPBLON(),  7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPORNO(),  7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPORLN(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPBKID(), 11));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPMCTC(),  4));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPCCDE(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPINTC(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPNBRI(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPORDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPORAM(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPORST(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPCCRS(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPEREF(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPKRTN(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPPYFQ(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPKNTR(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPIPSV(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPPGDS(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPAUST(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPPRBO(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPORBL(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPBLSQ(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPNBDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPTMID(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPTMBT(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPMODP(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getMXARJC(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getTRBNTN(), 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getTRBLON(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getTRTTYP(), 4));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getTRKORR(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getTRTRST(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getTRBDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getTRCANM(), 40));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getKTSPKD  (), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getKRAVST(), 3));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getKTKNTN(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getKRGACC(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getKRKNST(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getKRRKID(), 6));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getKRCCDE(), 3));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getWDNAME(), 40));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getWDIBEL(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getWDPBEL(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getWDTBEL(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPCMMTP(), 2));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getWDORST(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getWDBPNM(), 40));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPINTI(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getWDUNBL(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getWDTBIL(), 15));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPSTAS(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPTSRC(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getTRVLDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPUBNT(), 9));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPUBLO(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.mxObject.getPPIPRT(), 5));
			strMessageDetail.append(MessageClass.setMessageString(this.mxObject.getPPUPBY(), 10));
		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC9047";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
