// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5009 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5009Rq;
	private ktc_scs_schema.proxies.TC5009_TEXTRGDS TC5009Rq;

	public SetTC5009(IContext context, IMendixObject TC5009Rq)
	{
		super(context);
		this.__TC5009Rq = TC5009Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5009Rq = __TC5009Rq == null ? null : ktc_scs_schema.proxies.TC5009_TEXTRGDS.initialize(getContext(), __TC5009Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
				
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5009Rq.getTXNTYP(), 1));			
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5009Rq.getTXTKEY(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5009Rq.getTXNCAT(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5009Rq.getTXTDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5009Rq.getTXDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5009Rq.getTXUSER(), 10));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5009Rq.getTXTEXT(), 60));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5009Rq.getTXRMOD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5009Rq.getTXRDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5009Rq.getTXDLDT(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5009Rq.getTXOLIC(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5009Rq.getTXDLBY(), 10));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5009Rq.getTXWIND(), 1));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5009";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
