// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5006 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5006Rq;
	private ktc_scs_schema.proxies.TC5006_TEXTRGDS TC5006Rq;

	public SetTC5006(IContext context, IMendixObject TC5006Rq)
	{
		super(context);
		this.__TC5006Rq = TC5006Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5006Rq = __TC5006Rq == null ? null : ktc_scs_schema.proxies.TC5006_TEXTRGDS.initialize(getContext(), __TC5006Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
				
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5006Rq.getTXNTYP(), 1));			
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5006Rq.getTXTKEY(), 19));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5006Rq.getTXNCAT(), 6));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5006Rq.getTXTDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5006Rq.getTXDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5006Rq.getTXUSER(), 10));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5006Rq.getTXTEXT(), 60));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5006Rq.getTXRMOD(), 1));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5006Rq.getTXRDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5006Rq.getTXDLDT(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5006Rq.getTXOLIC(), 40));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5006Rq.getTXDLBY(), 10));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5006Rq.getTXWIND(), 1));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5006";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
