// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5081 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String accountNo;
	private java.lang.String transactionDate;
	private java.lang.String batchNo;
	private java.lang.String batchSequenceNo;

	public SetTC5081(IContext context, java.lang.String accountNo, java.lang.String transactionDate, java.lang.String batchNo, java.lang.String batchSequenceNo)
	{
		super(context);
		this.accountNo = accountNo;
		this.transactionDate = transactionDate;
		this.batchNo = batchNo;
		this.batchSequenceNo = batchSequenceNo;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String strMessageApplication = "";
		
		try
		{
			strMessageApplication = MessageClass.setMessageNumber("0",  19)
				+ MessageClass.setMessageNumber("0",  19)
				+ MessageClass.setMessageNumber(this.accountNo,  19)
				+ MessageClass.setMessageNumber(this.batchNo,  9)
				+ MessageClass.setMessageNumber(this.batchSequenceNo, 7)
				+ MessageClass.setMessageNumber(this.transactionDate,  8)
				+ MessageClass.setMessageNumber("0", 15)
				+ MessageClass.setMessageNumber("0", 4)
				+ MessageClass.setMessageString("", 1)
				+ MessageClass.setMessageString("", 6)
				+ MessageClass.setMessageString("", 25)
				+ MessageClass.setMessageNumber("0", 19)
				+ MessageClass.setMessageNumber("0", 15)
				+ MessageClass.setMessageString("", 3)
				+ MessageClass.setMessageNumber("0",  2);

		}
		catch (Exception ex)
		{
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(ex.getMessage());
		}
		
		return strMessageApplication;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5081";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
