// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SetTC5091 extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __TC5091Rq;
	private ktc_scs_schema.proxies.TC5091_DISPTR02DS TC5091Rq;

	public SetTC5091(IContext context, IMendixObject TC5091Rq)
	{
		super(context);
		this.__TC5091Rq = TC5091Rq;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.TC5091Rq = __TC5091Rq == null ? null : ktc_scs_schema.proxies.TC5091_DISPTR02DS.initialize(getContext(), __TC5091Rq);

		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		try
		{
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPBNTN(), 9));			
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPBLON(), 7));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPTTYP(), 4));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPKRTN(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPKNTN(), 19));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPVLDT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPBDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5091Rq.getDPSTAS(), 1));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5091Rq.getDPDPRE(), 2));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPAMT(), 15));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPRDAT(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPSTLC(), 8));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getDPDTTM(), 14));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5091Rq.getIPNAME(), 32));
			strMessageDetail.append(MessageClass.setMessageString(this.TC5091Rq.getIPLSNM(), 40));
			strMessageDetail.append(MessageClass.setMessageNumber(this.TC5091Rq.getWDFLAG(), 1));
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5091";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
