// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5061 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String groupAccountNumber;

	public SetTC5061(IContext context, java.lang.String groupAccountNumber)
	{
		super(context);
		this.groupAccountNumber = groupAccountNumber;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
				StringBuilder strMessageDetail = new StringBuilder();
				
				try
				{
					strMessageDetail.append(MessageClass.setMessageNumber(this.groupAccountNumber, 19));
				}
				catch (Exception ex)
				{
					throw ex;
				}
				
				return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5061";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
