// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC1615 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String cardNumber;
	private java.lang.String authorisationMode;
	private java.lang.String authorisationGroup;
	private java.lang.String domesticYN;

	public SetTC1615(IContext context, java.lang.String cardNumber, java.lang.String authorisationMode, java.lang.String authorisationGroup, java.lang.String domesticYN)
	{
		super(context);
		this.cardNumber = cardNumber;
		this.authorisationMode = authorisationMode;
		this.authorisationGroup = authorisationGroup;
		this.domesticYN = domesticYN;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder strMessageDetail = new StringBuilder();
		
		try
		{
			strMessageDetail.append(MessageClass.setMessageString(this.authorisationGroup, 3));		//	AAAUTG
			strMessageDetail.append(MessageClass.setMessageNumber(this.cardNumber, 19));			//	AAKRTN
			strMessageDetail.append(MessageClass.setMessageString(this.authorisationMode, 2));		//	AAAMOD
			strMessageDetail.append(MessageClass.setMessageString(this.domesticYN, 1));				//	AAMODI
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						// 	AADAMA
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));							// 	AADNOD
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						//	AADAMD
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						//	AAIAMA
			strMessageDetail.append(MessageClass.setMessageNumber("0", 3));							//	AAINOD
			strMessageDetail.append(MessageClass.setMessageNumber("0", 11));						//	AAIAMD
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageDetail.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC1615";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
