// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ktc_scs_schema.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ktcmdwscsconnector.customs.MessageClass;

public class SetTC5406 extends CustomJavaAction<java.lang.String>
{
	private java.lang.String accountNumber;
	private java.lang.String updateDate;
	private java.lang.String limitRqsNo;
	private java.lang.String limitAdjustmentStatus;
	private java.lang.String limitAdjTextDesc;

	public SetTC5406(IContext context, java.lang.String accountNumber, java.lang.String updateDate, java.lang.String limitRqsNo, java.lang.String limitAdjustmentStatus, java.lang.String limitAdjTextDesc)
	{
		super(context);
		this.accountNumber = accountNumber;
		this.updateDate = updateDate;
		this.limitRqsNo = limitRqsNo;
		this.limitAdjustmentStatus = limitAdjustmentStatus;
		this.limitAdjTextDesc = limitAdjTextDesc;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String strMessageApplication = "";
		try
		{
			strMessageApplication = MessageClass.setMessageNumber(this.accountNumber, 19)
					+ MessageClass.setMessageNumber(this.updateDate, 8)
					+ MessageClass.setMessageNumber(this.limitRqsNo, 9)
					+ MessageClass.setMessageString(this.limitAdjustmentStatus, 1)
					+ MessageClass.setMessageString(this.limitAdjTextDesc, 10)
					+ MessageClass.setMessageString("", 3)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageNumber("0", 8)
					+ MessageClass.setMessageString("", 3)
					+ MessageClass.setMessageString("", 1)
					+ MessageClass.setMessageString("", 3)
					+ MessageClass.setMessageString("", 15)
					+ MessageClass.setMessageString("", 1)
					+ MessageClass.setMessageString("", 10)
					+ MessageClass.setMessageNumber("0", 14)
					+ MessageClass.setMessageString("", 1)
					+ MessageClass.setMessageString("", 10)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageNumber("0", 11)
					+ MessageClass.setMessageString("", 1);
		}
		catch (Exception ex)
		{
			throw ex;
		}
		
		return strMessageApplication.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetTC5406";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
